### ISSUE TITLE
Refactor of misspelled or badly chosen variable names

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#1]
In OpenMMfrenergyst.cpp and openmmmd.cpp make sure variable names are consistantant and correctly spelled.

**Comment by jmichel80** [comment]
Also consider renaming file names, for instance 
openmmfrenergyst --> openmmfreeenergysingletopology

openmmacceleratedmdintegrator and openmmintegrator are broken/deprecated
openmmfrenergydt is buggy/untested 

It may make sense to have openmmfreenergysingletopology inherit from openmmmdintegrator

**Comment by ppxasjsm** [comment]
Ok. Also feel free to add more issues as you can think of them. At this point you know better where issues might lie.

**Comment by ppxasjsm** [comment]
I didn't rename the two classes because the names are pretty long as they are. 
I think a future reshuffle of them will be worthwhile with an OpenMM base class and anything else will depend on this. For now I'll leave it as is and try and implement a couple of other features first.
