### ISSUE TITLE
cannot build sire corelib and wrappers without openmm

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#10]
Need to edit code in corelib/SireMove and wrapper/move/ to detect that OpenMM is not available.

**Comment by ppxasjsm** [comment]
I had a look it this together with building things with travis. Withouth openmm I get the following build error:
```
TBB_LIBRARY

    linked by target "SireMM" in directory /home/travis/build/michellab/Sire/corelib/src/libs/SireMM

TBB_MALLOC_LIBRARY

    linked by target "SireMM" in directory /home/travis/build/michellab/Sire/corelib/src/libs/SireMM
```
The Cmake file seems to check for openmm, I don't really see where the problem occurs.

**Comment by jmichel80** [comment]
I think this is a bug with the sire cmake configs. I cc'ed chris as I'm not
sure whether he is receiving the github posts.

I normally work around this by typing ccmake . and then regenerate config.
I don't know why this needs to be done periodically. Obviously could be a
problem for automated builds.

Short term) Is there a way to build that fix in a travis build script?

Julien

--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

On Fri, Jul 3, 2015 at 2:55 PM, ppxasjsm <notifications@github.com> wrote:

> I had a look it this together with building things with travis. Withouth
> openmm I get the following build error:
>
> TBB_LIBRARY
>
>     linked by target "SireMM" in directory /home/travis/build/michellab/Sire/corelib/src/libs/SireMM
>
> TBB_MALLOC_LIBRARY
>
>     linked by target "SireMM" in directory /home/travis/build/michellab/Sire/corelib/src/libs/SireMM
>
> The Cmake file seems to check for openmm, I don't really see where the
> problem occurs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/10#issuecomment-118357648>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
I am trying to include an openmm installation first which should solve the problem.

**Comment by jmichel80** [comment]
Hi Julien,

No, I am not seeing the github emails (or have too aggressive email
filters...). There are definitely problems with the cmake files when trying
to detect OpenMM. I am surprised that there is a TBB error. This suggests
that the tbb library is, for some reason, not being correctly built and
located in the build/bundled directory (where all dependencies should be
built). Could you send me a more detailed bug report and I can then work
out what is going wrong?

  Thanks,

  Christopher


On 3 July 2015 at 15:01, Julien Michel <julien.michel@ed.ac.uk> wrote:

> I think this is a bug with the sire cmake configs. I cc'ed chris as I'm
> not sure whether he is receiving the github posts.
>
> I normally work around this by typing ccmake . and then regenerate config.
> I don't know why this needs to be done periodically. Obviously could be a
> problem for automated builds.
>
> Short term) Is there a way to build that fix in a travis build script?
>
> Julien
>
> --------------------------------------------------------------
> Dr. Julien Michel,
> Royal Society University Research Fellow
> Room 263, School of Chemistry
> Joseph Black Building, University of Edinburgh
> David Brewster Road
>
> Edinburgh
>
> EH9 3FJ
> United Kingdom
> phone:   +44 (0)131 650 4797
> http://www.julienmichel.net/
> -------------------------------------------------------------
>
> On Fri, Jul 3, 2015 at 2:55 PM, ppxasjsm <notifications@github.com> wrote:
>
>> I had a look it this together with building things with travis. Withouth
>> openmm I get the following build error:
>>
>> TBB_LIBRARY
>>
>>     linked by target "SireMM" in directory /home/travis/build/michellab/Sire/corelib/src/libs/SireMM
>>
>> TBB_MALLOC_LIBRARY
>>
>>     linked by target "SireMM" in directory /home/travis/build/michellab/Sire/corelib/src/libs/SireMM
>>
>> The Cmake file seems to check for openmm, I don't really see where the
>> problem occurs.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/michellab/Sire/issues/10#issuecomment-118357648>.
>>
>
>
> The University of Edinburgh is a charitable body, registered in
> Scotland, with registration number SC005336.
>
>


-- 
---------------------------------------------------------
Christopher Woods
+44 (0) 7786 264562
http://chryswoods.com

**Comment by ppxasjsm** [comment]
Here is the complete installation log from the failed install:
https://travis-ci.org/michellab/Sire/builds/69433800

I haven't tried reproducing this locally. This is only an issue with the automatic build, continous integration tool travis. 

If you need more information/or cant read the log output I have sent you, let me know. 
Best,
-Toni

**Comment by ppxasjsm** [comment]
I am trying to understand the cmake files for sire. I have absolutely zero experience in writing my own cmake files, so maybe I am missing obvious things here. 

Here is what I don't quite understand. Certain variables such as SIRE_OpenMM_LIB are supposedly set in the findOpenMM.cmake file and then stored, but when I try and get information regarding them, they don't seem to exist, i.e.:
```
if ( NOT ${SIRE_FOUND_OPENMM} )
    # look for OpenMM in the system
    # Now look for OpenMM
    option (OPENMM_HOME "The location of the OpenMM installation" "/usr/local/openmm")
    set(OpenMM_ROOT_DIR "${OPENMM_HOME}")
    FIND_PACKAGE( OpenMM )

    save_sire_variable( "SIRE_OpenMM_FOUND" "${OpenMM_FOUND}" )

    if ( ${OpenMM_FOUND} )
       message( STATUS "Found OpenMM at ${OpenMM_ROOT_DIR}" )
       save_sire_variable( "SIRE_OpenMM_INCLUDE_DIR" "${OpenMM_INCLUDE_DIR}" )
       save_sire_variable( "SIRE_OpenMM_LIBRARIES" "${OpenMM_LIBRARIES}" )
       save_sire_variable( "SIRE_OpenMM_LIBRARY_DIR" "${OpenMM_LIBRARY_DIR}" )
       message( STATUS "Sire openmm include dir: ${SIRE_OpenMM_INCLUDE_DIR}" )
       message( STATUS "Sire openmm libraries: ${SIRE_OpenMM_LIBRARIES}" )
       message( STATUS "Sire openmm libraries dir: ${SIRE_OpenMM_LIBRARY_DIR}" )
    else()
       message( STATUS "Could not find OpenMM. OpenMM support is disabled." )
    endif()
```
The output I get is:
```
-- Found OpenMM: /home/ppxasjsm/Software/openmm
-- Found OpenMM at /home/ppxasjsm/Software/openmm
-- Sire openmm include dir:
-- Sire openmm libraries:
-- Sire openmm libraries dir:
```
Somehow Sire installs fine with using the OPENMM_ROOT_DIR=/home/ppxasjsm/Software/openmm variable, where this installation of OpenMM is from source. 

However, when I try and install using an anaconda version of OpenMM, the install fails. I again set a bunch of environment variables, which don't seem to be read, I get the same output again, but the install fails around the time for when it comes to compiling for dcd file support. An identical set of libraries is now found in /home/ppxasjsm/anaconda/include  and */lib respectively. The installation works fine. 

Also I guess the main problem of trying to build with no OPENMM_ROOT_DIR environment variable set (and no installation in /usr/local/openmm) will always fail, but I haven't quite moved onto that problem yet.

**Comment by jmichel80** [comment]
Can you write how you set OPENMM_ROOT_DIR and how you call cmake when using
OpenMM via anaconda?

If you can do this interactively, check the result of your config attempt
with ccmake rather than trying to compile immediately after.

If I remember well, you need indeed to disable the build of somd is
OPENMM_ROOT_DIR is not set.

--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

On Thu, Jul 16, 2015 at 11:13 AM, ppxasjsm <notifications@github.com> wrote:

> I am trying to understand the cmake files for sire. I have absolutely zero
> experience in writing my own cmake files, so maybe I am missing obvious
> things here.
>
> Here is what I don't quite understand. Certain variables such as
> SIRE_OpenMM_LIB are supposedly set in the findOpenMM.cmake file and then
> stored, but when I try and get information regarding them, they don't seem
> to exist, i.e.:
>
> if ( NOT ${SIRE_FOUND_OPENMM} )
>     # look for OpenMM in the system
>     # Now look for OpenMM
>     option (OPENMM_HOME "The location of the OpenMM installation" "/usr/local/openmm")
>     set(OpenMM_ROOT_DIR "${OPENMM_HOME}")
>     FIND_PACKAGE( OpenMM )
>
>     save_sire_variable( "SIRE_OpenMM_FOUND" "${OpenMM_FOUND}" )
>
>     if ( ${OpenMM_FOUND} )
>        message( STATUS "Found OpenMM at ${OpenMM_ROOT_DIR}" )
>        save_sire_variable( "SIRE_OpenMM_INCLUDE_DIR" "${OpenMM_INCLUDE_DIR}" )
>        save_sire_variable( "SIRE_OpenMM_LIBRARIES" "${OpenMM_LIBRARIES}" )
>        save_sire_variable( "SIRE_OpenMM_LIBRARY_DIR" "${OpenMM_LIBRARY_DIR}" )
>        message( STATUS "Sire openmm include dir: ${SIRE_OpenMM_INCLUDE_DIR}" )
>        message( STATUS "Sire openmm libraries: ${SIRE_OpenMM_LIBRARIES}" )
>        message( STATUS "Sire openmm libraries dir: ${SIRE_OpenMM_LIBRARY_DIR}" )
>     else()
>        message( STATUS "Could not find OpenMM. OpenMM support is disabled." )
>     endif()
>
> The output I get is:
>
> -- Found OpenMM: /home/ppxasjsm/Software/openmm
> -- Found OpenMM at /home/ppxasjsm/Software/openmm
> -- Sire openmm include dir:
> -- Sire openmm libraries:
> -- Sire openmm libraries dir:
>
> Somehow Sire installs fine with using the
> OPENMM_ROOT_DIR=/home/ppxasjsm/Software/openmm variable, where this
> installation of OpenMM is from source.
>
> However, when I try and install using an anaconda version of OpenMM, the
> install fails. I again set a bunch of environment variables, which don't
> seem to be read, I get the same output again, but the install fails around
> the time for when it comes to compiling for dcd file support. An identical
> set of libraries is now found in /home/ppxasjsm/anaconda/include and */lib
> respectively. The installation works fine.
>
> Also I guess the main problem of trying to build with no OPENMM_ROOT_DIR
> environment variable set (and no installation in /usr/local/openmm) will
> always fail, but I haven't quite moved onto that problem yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/10#issuecomment-121917035>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
Compiling Sire with anaconda works fine now. 
 If I set the following environment variables the compilation runs ok:
```
    - PATH=$HOME/miniconda/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/miniconda/lib/:$LD_LIBRARY_PATH 
    - LIBRARY_PATH=$HOME/miniconda/lib/:$LIBRARY_PATH
    - OPENMM_PLUGIN_DIR=$HOME/miniconda/lib/plugins
    - OPENMM_ROOT_DIR=$HOME/miniconda
    - PYTHONPATH=$HOME/miniconda/lib/python2.7/site-packages:$PYTHONPATH
    - OPENMM_INCLUDE_PATH=$HOME/miniconda/include 
    - OPENMM_LIB_PATH=$HOME/miniconda/lib/
    - CPLUS_INCLUDE_PATH=$HOME/miniconda/include 
    - OPENMMDIR=$HOME/miniconda/include 
```
For the compilation I do:
```
   mkdir build
   cd build
   cmake -DSIRE_DISABLE_AVX=ON ../corelib
   make -j 2
   make install
```


I don't think I need all of these environment variables, and clearly some of them are not used by the cmake files at all, but this was the set of variables Gaetano had defined at some point with which the install worked. Also the comment in the findOpenMM.cmake file is misleading:

```
# The script defines defines: 
#  OpenMM_FOUND     
#  OpenMM_ROOT_DIR
#  OpenMM_INCLUDE_DIR
#  OpenMM_LIBRARY_DIR
#  OpenMM_LIBRARIES      
#  OpenMM_LIBRARIES_D   - debug version of libraries 
#  OpenMM_PLUGIN_DIR
#
```

I am guessing CPLUS_INCLUDE_PATH=$HOME/miniconda/include,   LD_LIBRARY_PATH=$HOME/miniconda/lib/:$LD_LIBRARY_PATH 
and LIBRARY_PATH=$HOME/miniconda/lib/:$LIBRARY_PATH should be sufficient when the OPENMM_ROOT_DIR is defined. 

To me a compile option such as:
```
cmake ../corelib -DSIRE_OPENMM_SUPPORT=on -DSIRE_OPENMM_ROOT_DIR=path/to/openmm
```
where the latter option is only needed if openmm is not installed in the default location /usr/local/openmm. This then avoids having to set unnecessary enviroment variables and can easily control a compilation with and without OpenMM. 
An option like this doesn't currently exist and I am just oblivious to it?

**Comment by jmichel80** [comment]
You are correct it looks like there is no simple way to build sire without
openmm if openmm has been detected. It is something that should be fixed
and we should have a SIRE_DISABLE_OPENMM flag available via ccmake (or by
exporting the correct environment variable to cmake).
>
>



-- 
--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
I have found the problem why Sire doesn't build without openMM. The dcd_writer.h/cpp files were doubly defined. I will get rid of this now so Sire can be build without openmm, but I think I will have a look at implementing an OPENMM_FLAG properly once I have completed the other tasks, since it will take me a little while to understand who to write cmake files properly.

**Comment by ppxasjsm** [comment]
So corelib can be build without openmm, by doing the above. However, the resulting build is not clean and all openmm libraries are still somehow available in the include directories of Sire. I'll have a proper look at this soon.

**Comment by ppxasjsm** [comment]
Both corelib and wrapper now compile with or without OpenMM present.
