### ISSUE TITLE
somd-freenrg crashing after 81 cycles

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#100]
Has anyone seen this before ? The output happens for all windows of a test free energy run I am doing at the moment. 

(...)
Cycle =  80 
Cycle =  81 

Starting /home/julien/sire.app/bin/somd-freenrg: number of threads equals 16
Traceback (most recent call last):
  File "/home/julien/sire.app/pkgs/sire-2016.1.0/share/Sire/scripts/somd-freenrg.py", line 142, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/home/julien/sire.app/lib/python3.5/site-packages/Sire/Tools/__init__.py", line 140, in inner
    retval = func()
  File "/home/julien/sire.app/lib/python3.5/site-packages/Sire/Tools/OpenMMMD.py", line 1556, in runFreeNrg
    grads[lambda_val.val].accumulate(gradients[i-1])
IndexError: list index out of range
srun: error: mechagodzilla: task 0: Exited with exit code 1

**Comment by jmichel80** [comment]
The offending code causing this involves the dictionary grads. This doesn't seem to be used at all to produce output and is probably a relic of past versions. grads should be removed

    #grads = {}
    #grads[lambda_val.val] = AverageAndStddev()
    s1 = timer.elapsed() / 1000.
    for i in range(cycle_start, cycle_end):
        print("\nCycle = ", i, "\n")
        system = moves.move(system, nmoves.val, True)
        if save_coords.val:
            writeSystemData(system, moves, trajectory, i, softcore_lambda)

        mdmoves = moves.moves()[0]
        integrator = mdmoves.integrator()

        #saving all data
        beg = (nmoves.val*(i-1))
        end = nmoves.val*(i-1)+nmoves.val
        steps = list(range(beg, end, energy_frequency.val))
        outdata = getAllData(integrator, steps)
        gradients = integrator.getGradients()
        fmt =" ".join(["%8d"] + ["%25.8e"] + ["%25.8e"] + ["%25.8e"] + ["%25.8e"] + ["%25.15e"]*(len(lambda_array.val)))
        np.savetxt(outfile, outdata, fmt=fmt)


        mean_gradient = np.average(gradients)
        outgradients.write("%5d %20.10f\n" % (i, mean_gradient))
        print (i, cycle_start, cycle_end, gradients)
        #for gradient in gradients:
        #    grads[lambda_val.val].accumulate(gradients[i-1])
    s2 = timer.elapsed() / 1000.

**Comment by ppxasjsm** [comment]
Not seen this before. I'll add it to the list of fixes.

**Comment by jmichel80** [comment]
Fixed in feature_nosoluteconstraints

**Comment by ppxasjsm** [comment]
So we can close the issue?

**Comment by jmichel80** [comment]
Wait we have merged in devel.
Will request merge next week if the current batch of sims worked ok.

**Comment by ppxasjsm** [comment]
ok! I will need a bit of time to digest code changes probably.
