### ISSUE TITLE
Travis CI build is timing out

### ISSUE THREAD

**Issue by chryswoods** [michellab/Sire#111]
The switch to a new GCC, and turning on C++-14 support, means that the time to compile Sire has increased. It now takes more than 50 minutes on Travis, which is the maximum time limit. I have emailed Travis support to see if they can increase the time limit for Sire jobs (I've requested 75 minutes). We will see how it goes...

**Comment by ppxasjsm** [comment]
Any reason, why compile time would increase so drastically?

**Comment by chryswoods** [comment]
Later GCCs seem to be slower. C++-14 is harder to parse.

**Comment by chryswoods** [comment]
Travis have got back to me with a very kind reply, and have increased our maximum build time to 90 minutes. I've started a build now to see if it is enough.

**Comment by ppxasjsm** [comment]
Great!

**Comment by chryswoods** [comment]
It all works. Total build with unit tests takes just over 58 minutes using GCC 5.4
