### ISSUE TITLE
OpenMM unit test fails

### ISSUE THREAD

**Issue by chryswoods** [michellab/Sire#112]
One of the OpenMM unit tests always fails (and has done since it was added, if I remember correctly). The output is;

======================================================================
FAIL: test_setup_openmmd.test_nve
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chris/sire.app/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/chris/sire.app/pkgs/sire-2016.2.0/share/Sire/test/SireUnitTests/unittests/OpenMM/test_setup_openmmd.py", line 226, in test_nve
    assert(percent_fluc<0.1)

-------------------- >> begin captured stdout << ---------------------
++++++++++++++++++++++++0++++++++++++++++++++
Potential energy is -5746.47 kcal mol-1 and kinetic energy is 1781.27 kcal mol-1
Total energy from sire is: -3965.21 kcal mol-1
++++++++++++++++++++++++1++++++++++++++++++++
Potential energy is -5776.4 kcal mol-1 and kinetic energy is 1548.76 kcal mol-1
Total energy from sire is: -4227.64 kcal mol-1
++++++++++++++++++++++++2++++++++++++++++++++
Potential energy is -5969.05 kcal mol-1 and kinetic energy is 1799.74 kcal mol-1
Total energy from sire is: -4169.31 kcal mol-1
++++++++++++++++++++++++3++++++++++++++++++++
Potential energy is -5859.16 kcal mol-1 and kinetic energy is 1775 kcal mol-1
Total energy from sire is: -4084.16 kcal mol-1
++++++++++++++++++++++++4++++++++++++++++++++
Potential energy is -5987.21 kcal mol-1 and kinetic energy is 1789.92 kcal mol-1
Total energy from sire is: -4197.29 kcal mol-1
++++++++++++++++++++++++5++++++++++++++++++++
Potential energy is -5720.19 kcal mol-1 and kinetic energy is 1794.97 kcal mol-1
Total energy from sire is: -3925.22 kcal mol-1
++++++++++++++++++++++++6++++++++++++++++++++
Potential energy is -5584.61 kcal mol-1 and kinetic energy is 1426.4 kcal mol-1
Total energy from sire is: -4158.21 kcal mol-1
++++++++++++++++++++++++7++++++++++++++++++++
Potential energy is -5962.73 kcal mol-1 and kinetic energy is 1659.44 kcal mol-1
Total energy from sire is: -4303.3 kcal mol-1
++++++++++++++++++++++++8++++++++++++++++++++
Potential energy is -5892.37 kcal mol-1 and kinetic energy is 1852.9 kcal mol-1
Total energy from sire is: -4039.47 kcal mol-1
++++++++++++++++++++++++9++++++++++++++++++++
Potential energy is -5940.31 kcal mol-1 and kinetic energy is 1733.61 kcal mol-1
Total energy from sire is: -4206.7 kcal mol-1
Percent fluctuations are: 2.77977397027 

--------------------- >> end captured stdout << ----------------------

Could this be fixed, or the test removed and this code disabled? Ideally all tests should pass before we ship 2016.3.

  Thanks :-)

**Comment by ppxasjsm** [comment]
I'll fix it. Am at a conference today/tomorrow though.

**Comment by chryswoods** [comment]
Thanks, and no rush. Just wanted to flag it before making a release. My hope is to make the release in the week of the 19th Dec. I want to get into the habit of regular releases, which can happen when all of the unit tests are shown as passing.

**Comment by ppxasjsm** [comment]
So this has been temporarily fixed. But will need attention for the next release! I'll leave it open for that reason.

**Comment by chryswoods** [comment]
Did you fix the unit test or the code? I ask as I have just recompiled and rerun and still see the test as failing, and don't know what I did wrong ;-(

**Comment by ppxasjsm** [comment]
I mainly removed the part of the test that failed. It failed not because there was something wrong with the code, but because the test was wrong.

**Comment by ppxasjsm** [comment]
I nolonger get an error. You might have to update Sire Unit tests.

**Comment by chryswoods** [comment]
I see the problem - you updated SireTest, but the repository for the unit tests is <https://github.com/michellab/SireUnitTests>. We separated out the unit tests from SireTests when you visited because downloading all of the data for the larger tests was too much when running on travis, or when people want to run the simple tests.

Could you fix the test in SireUnitTests? We should then clean up the split between SireTests and SireUnitTests before 2017.1.

**Comment by chryswoods** [comment]
This is now fixed.
