### ISSUE TITLE
Potential bug with openmm MCBarostat use in Sire

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#12]
Despite MCBarostat set to true, I end up with virtually no boxsize fluctuation, which turned out to be problematic for a not well equilibrated initial system. (I end up with holes in the water everywhere.)

**Comment by jmichel80** [comment]
can you give more details ? like number of cycles, length of cycle,
frequency of attempting volume moves ? You need to attempt many times a
volume move to reach correct average box size.
I suspect (but haven't checked) that MD thermostats in other codes (e.g.
Berendsen) relax more rapidly volume to reach a desired pressure, hence it
may be a good idea to equilibrate well the system with FESetup (that uses
sander by default, but can also be instructed to use other more efficient
MD code).



--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

On Thu, Jun 11, 2015 at 10:57 AM, ppxasjsm <notifications@github.com> wrote:

> Despite MCBarostat set to true, I end up with virtually no boxsize
> fluctuation, which turned out to be problematic for a not well equilibrated
> initial system. (I end up with holes in the water everywhere.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/12>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
So I have done an exact comparison at lambda 0 of a direct OpenMM simulation and a Sire openMM simulation (master using a config file). After about 50 ps the OpenMM simulation has relaxed to the 'correct' box size and there are no water holes observed. If I run the same length simulation in Sire (10 cycles à 5000 moves), and the same thermostat and barostat settings (frequency 25, 1 atmosphere, 300 K), the box size fluctuations are minimial and if anything more pronounced holes appear. I am now trying to find out why this is happening. I may have not set a variable correctly, I'll keep checking.

**Comment by ppxasjsm** [comment]
Ah there is one difference i use PME in the openMM simulation.
