### ISSUE TITLE
(somd) Potential incorrect estimation of simulation time if doing a restart

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#122]
If somd restarts an MD run from a restart file, the timestep used to produce the restart file is used. 
If the user has changed the timestep value in the config file this is ignored. 
However somd prints to the standard output:
    simtime=nmoves.val*ncycles.val*timestep.val
    print("###=======================somd run============================###")
    print ("Starting somd run...")
    print ("%s moves %s cycles, %s simulation time" %(nmoves.val, ncycles.val, simtime))

where timestep.val is the value set by the config file. 

Solution is to modify the block of code below

    else:
        system, moves = Sire.Stream.load(restart_file.val)
        move0 = moves.moves()[0]
        integrator = move0.integrator()
        integrator.setDeviceIndex(str(gpu.val))
        move0.setIntegrator(integrator)
        moves = WeightedMoves()
        moves.add(move0)
        print("Index GPU = %s " % moves.moves()[0].integrator().getDeviceIndex())
        print("Loaded a restart file on which we have performed %d moves." % moves.nMoves())
        #Maybe include a runtime error here!
        if minimise.val:
            print ('WARNING: You are trying to minimise from a restart! Revise your config file!')
        if equilibrate.val:
            print ('WARNING: You are trying to equilibrate from a restart! Revise your config file!')

Such that if restarting the timestep of the integrator is updated with the config file timestep (if different), much in the same way the integrator in the code above is passed a new GPU device index. 

Bugfixes are needed for both somd and somd-freenrg.

**Comment by chryswoods** [comment]
Closing as no progress
