### ISSUE TITLE
stale branches

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#123]
we have a branch that does not seem to be used anymore

feat-free-eng-merge

was freenrg_mbar_dirty_fix merged into 2016.3.1 ? If so we do not need this branch anymore.

**Comment by ppxasjsm** [comment]
I'll deal with them next week.

**Comment by chryswoods** [comment]
Thanks - yes please delete stale branches (remembering not to delete master ;-))

**Comment by jmichel80** [comment]
I have merged feature_standardstategen, as this also included code changes in feature_ljtail, I have also deleted that branch.

**Comment by ppxasjsm** [comment]
Does this include changes from freenrg_analysis or did you not commit those changes?

**Comment by jmichel80** [comment]
No I did not include anything from your code changes to freenrg_analysis. Please proceed with the merge when all tests have completed.

**Comment by jmichel80** [comment]
I created a new branch off devel 'feature_pbcorrection' that has the PB correction code Stefano is working on.

**Comment by ppxasjsm** [comment]
Ok great!
