### ISSUE TITLE
Add formal charge to PDB

### ISSUE THREAD

**Issue by chryswoods** [michellab/Sire#124]
Need to add formal charge output to PDBs

**Comment by chryswoods** [comment]
This is now morphing into a bigger problem. Essentially, I need to add code that can work out the formal charges on atoms based on element and connectivity. This is a challenging problem. Current code in PDB() in new_parser branch is a hack. Ideal solution is to add this properly with a heuristic to Evaluator, so we can have "auto formal_charges = molecule.evaluate().formalCharges()". This is a TODO feature that is relatively high on Cresset's list

**Comment by jmichel80** [comment]
Hi Chris,

Hannes parses the charge column info in PDBs when loading input in FEsetup. 

We sometimes have to manually add a net charge if the info was not there.
Why are your PDBs lacking this info in the 1st place? Where do they cone from?

Julien

**Comment by chryswoods** [comment]
The charge is the unit charge on each atom (formal charge), which Sire currently doesn't calculate. This is because it is ambiguous (which oxygen should get the -1 charge in a carboxylate group), and Sire doesn't have a concept of double bonds (so working out if a carbon in a ring should be charged or is not if the ring is aromatic is difficult). Cresset only want this because their software uses the formal charge to decide whether or not to automatically protonate residues. The lack of -1 charge on one of the carboxylate oxygens in ASP/GLU residues means that their software keeps protonating PDBs that are written by Sire.

I am hacking together a quick solution now for Cresset, and have worked out a better solution that I will code up later. I will add this to the roadmap aimed at the 2017.2 release.

**Comment by chryswoods** [comment]
Closing as this is now in the roadmap in the wiki
