### ISSUE TITLE
No constraints simulations and water

### ISSUE THREAD

**Issue by Steboss** [michellab/Sire#13]
Hi there!

It appears that performing simulations with no constraints  also water molecules do not have constraints and it can cause instabilities.

**Comment by ppxasjsm** [comment]
And this was also the reason why I was having such a hard time figuring out what was wrong with my code changes. The OpenMMMD.py file has by default no constraints set. So things kept exploding. Today I realised that this was the problem an not the code changes I had made...
Maybe we should have a default constraints=hbonds

**Comment by jmichel80** [comment]
Yes we should have default settings for a condensed phase NPT simulation as
this is what users would normally want to do for a binding energy
calculation.

--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

On Tue, Jul 21, 2015 at 8:12 PM, ppxasjsm <notifications@github.com> wrote:

> And this was also the reason why I was having such a hard time figuring
> out what was wrong with my code changes. The OpenMMMD.py file has by
> default no constraints set. So things kept exploding. Today I realised that
> this was the problem an not the code changes I had made...
> Maybe we should have a default constraints=hbonds
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/13#issuecomment-123448358>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by jmichel80** [comment]
Fixed with new constraint option 'none-notwater'
