### ISSUE TITLE
sire: ./compire-sire.sh --install XXX does not seem to work

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#131]
Doing a fresh build
Nothing happens if I type

./compile-sire.sh --install /home/julien/sire.app

I had to comment out the statement 'exit (0)' at line 24 of compile-sire.sh for the --install option to work as intended.

**Comment by chryswoods** [comment]
Thanks - the exit(0) is obviously wrong and should be deleted. I have removed it from the new_parser branch (which is the one I am actively developing), with this fix merged when I bring in new_parser (should be very soon). Speaking of which, the new parsers are fast, parallel, and automatic, i.e.

```python
#load the whole proteinbox system in less than 1 second
system = MoleculeParser.read("file.top", "file.crd")

# just parse the topology file
prm = AmberParm("file.top")

# get the 3rd molecule from this file (without coord info)
mol = prm.getMolecule(2)

# just parse the restart file
rst = AmberRst("file.crd")

# now get the 3rd molecule from this file with coord info
mol = prm.getMolecule(2, rst)
```

I'll close this issue once I have merged in new_parser.

**Comment by jmichel80** [comment]
That sounds really great ! It will enable new use cases and make some mdtraj hacks to update coordinates without loading a topology less relevant.

I wonder how you did it. When I wrote the parser there was a bottleneck around the setup of non bonded pairs that seemed hard to work around.

Now before this is pushed in devel let's make sure that this won't break somd or nautilus!

**Comment by chryswoods** [comment]
This is being written as a new set of parsers, so will not replace Amber (i.e. like how InterFF is new, and does not replace InterCLJFF etc.). You can choose when you want to use it after I have merged in the new_parser branch.
