### ISSUE TITLE
change in config file parser?

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#132]
HI, 

Very confused. Did the code for parsing config files change in 2016.3 ? 

I have this very strange behaviour where I can no longer run simulations with config files where paths to files are written between '' ''

example a config file that contains
(...)
morphfile = ../../input/MORPH.pert
(...)

runs ok

but if i change the syntax to
(...)
morphfile = ''../../input/MORPH.pert''
(...)
I get the error message

(...)
somd-freenrg is built using Sire and OpenMM and is distributed under the GPL.
For more information please visit http://siremol.org

Please supply the name of an existing topology, coordinate and morph file.
(cannot find morph file "../../input/MORPH.pert")

Losing my sleep.

**Comment by ppxasjsm** [comment]
I don't think I have changed anything here.

**Comment by jmichel80** [comment]
Another app that is now broken due to the change of parsing behavior. The problem is that option -b is no longer parsed correctly.

~/sire.app/bin/lj-tailcorrection -C ../../input/sim.cfg -l 0.00 -b '1.00 * gram / (centimeter*centimeter*centimeter)' -r traj000000001.dcd -s 1 1> ../freenrg-LJCOR-lam-0.000.dat
Traceback (most recent call last):
  File "/home/julien/sire.app/pkgs/sire-2016.3.1/share/Sire/scripts/lj-tailcorrection.py", line 156, in <module>
    LJcutoff.runLambda(params)
  File "/home/julien/sire.app/lib/python3.5/site-packages/Sire/Tools/__init__.py", line 172, in inner
    retval = func()
  File "/home/julien/sire.app/lib/python3.5/site-packages/Sire/Tools/LJcutoff.py", line 376, in runLambda
    E_lrc_full = addAnalyticalLRC(system_longc, long_cutoff, bulk_rho.val)
  File "/home/julien/sire.app/lib/python3.5/site-packages/Sire/Tools/LJcutoff.py", line 231, in addAnalyticalLRC
    rho = (bulk_density/solv_mol_mass).value()
TypeError: unsupported operand type(s) for /: 'str' and 'GeneralUnit'

**Comment by chryswoods** [comment]
The parser did change to fix the problems that Julien mentioned previously. The parser now handles units and has cleverness to recognise different types. There are a set of unit tests about the parser in unittests/Tools/test_parser.py. You have found some new edge cases that I will add to these so that I can fix. The parser generally needs overhauling so that it can work with types. I have already added this as a work item in the wiki.
