### ISSUE TITLE
openmm support broken in 2016.3?

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#133]
Hi,

It can no longer run somd on a CUDA platform using after a fresh sire install. 

Setting up sim file. 
There are 5326 atoms in the group 
###===========================================================###

###=======================Minimisation========================###
Running minimisation.
Energy before the minimisation: -16782.6 kcal mol-1
Tolerance for minimisation: 1
Maximum number of minimisation iterations: 1000
Traceback (most recent call last):
  File "/home/julien/sire.app/pkgs/sire-2016.3.1/share/Sire/scripts/somd-freenrg.py", line 147, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/home/julien/sire.app/lib/python3.5/site-packages/Sire/Tools/__init__.py", line 172, in inner
    retval = func()
  File "/home/julien/sire.app/lib/python3.5/site-packages/Sire/Tools/OpenMMMD.py", line 1604, in runFreeNrg
    system = integrator.minimiseEnergy(system, minimise_tol.val, minimise_max_iter.val)
RuntimeError: There is no registered Platform called "CUDA"

module list
Currently Loaded Modulefiles:
  1) slurm/default   2) cuda/7.5

The problem seems to be that openMM now expects cuda 8

julien@node010:~/software/devel/sire/build/corelib$ ldd /home/$USER/sire.app/lib/plugins/libOpenMMCUDA.so
	linux-vdso.so.1 =>  (0x00007ffc562d1000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1fecea9000)
	libOpenMM.so => /home/julien/sire.app/lib/plugins/../libOpenMM.so (0x00007f1fec987000)
	libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007f1feb9d3000)
	libcufft.so.8.0 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1feb7b5000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1feb5b1000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1feb2ad000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1feafa7000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1fead91000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1fea9cc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1fed2d4000)

I now have  in my binary ~/sire.app/conda-meta/openmm-7.1.0rc1-py35_0.json

What's the best fix ? Do we have a way to pull an older openmm version? Or do we have to go an install cuda 8 on all machines we use ? Arggg

**Comment by ppxasjsm** [comment]
You should be able to install the specific openmm version.
Try something along the lines:
```
conda remove openmm
conda install openmm=7.0
```

It is a bit annoying that OpenMM can only be run in the conda package version if the same CUDA drivers as during the build are used, but I guess that is unavoidable.

**Comment by jmichel80** [comment]
I did that...and this is what happens when I run somd-freenrg on a cluster node now

julien@node010:~$ ~/sire.app/bin/conda remove openmm
Fetching package metadata ...........
Solving package specifications: .

Package plan for package removal in environment /home/julien/sire.app:

The following packages will be REMOVED:

    openmm: 7.1.0rc1-py35_0 http://conda.binstar.org/omnia

Proceed ([y]/n)? y

julien@node010:~$ ~/sire.app/bin/conda install openmm=7.0
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/julien/sire.app:

The following NEW packages will be INSTALLED:

    openmm: 7.0.1-py35_0 http://conda.binstar.org/omnia

The following packages will be UPDATED:

    conda:  4.3.9-py35_0                                --> 4.3.11-py35_0

Proceed ([y]/n)? y

openmm-7.0.1-p 100% |###########################################################################################################################################################| Time: 0:00:02   4.07 MB/s
conda-4.3.11-p 100% |###########################################################################################################################################################| Time: 0:00:00   1.07 MB/s


(...)
Generated random seed number 138973 
Saving restart
Setting up sim file. 
There are 5326 atoms in the group 
###===========================================================###

###=======================Minimisation========================###
Running minimisation.
Energy before the minimisation: -16782.6 kcal mol-1
Tolerance for minimisation: 1
Maximum number of minimisation iterations: 1000
*** Error in `/home/julien/sire.app/bin/somd-freenrg': free(): invalid pointer: 0x00007fca70f3ad98 ***
Aborted (core dumped)

Perhaps the conda remove operation wasn't clean? 

Two problems:

#1 Not sure what to try next. Hack ./compile-sire.sh to pull openmm=7.0 the first time?

#2 Generally speaking this isn't good for sustainability. We can call the code sire 2016.3.X as much as we want, but what is under the hood actually depends on the day the code was compiled. 
One solution is to tie sire releases to specific versions of the dependencies pulled via conda, but this likely requires an overhaul of the install scripts to make it manageable. 

Thoughts and #1 and #2 ?

**Comment by jmichel80** [comment]
For issue 1 found this work-around

edit build/buid_sire.py line 93
        os.system("%s install --yes openmm" % conda_exe)
-->
        os.system("%s install --yes openmm=7.0" % conda_exe)

rm -rf ~/sire.app 

then full rebuild

**Comment by ppxasjsm** [comment]
I am not sure what the best solution for problem #1 and #2 are in these cases. 
In the end even if we hardcode an OpenMM version into a sire release version, then we still need to make sure that the appropriate cuda version is installed. 

Alternatively running everything using the OpenCL platform shoudl work and shouldn't make much of a difference in performance. With OpenCL there is no CUDA driver dependence and CUDA toolkit 7.5 should also work with OpenMM version 7.1

I think there were quite some substantial bug fixes in OpenMM going to version 7.1 so it would make sense to move to that soon.

**Comment by ppxasjsm** [comment]
Just tried to download and install cuda 8 on the cluster. Looks like Nvidia is having problems with their installer:
https://devtalk.nvidia.com/default/topic/993274/cuda-setup-and-installation/bad-checksum-for-cuda-8-0-for-ubuntu-14-04/1

**Comment by chryswoods** [comment]
Thanks for the discussion and for finding a solution. Yes, the binary 2016.3.1 defines the specific versions on the day the binary was compiled (i.e. the day I put it together). A problem with conda is that it will automatically update things, so the first "conda install" may then upgrade python libraries so that they are newer than those pull in by 2016.3.1. This is a problem for reproducibility, and is an issue. The only solutions are either

* We hard code versions for every install and prevent "conda install" from automatically upgrading. This is challenging, and we will have to decide when we want to move from one version to the next. (this is kind of the solution used for the C++ dependencies, e.g. Qt5, TBB, GSL, boost, which have  fixed version, and I decide periodically near release whether it is worth upgrading from one version to the next).

* We don't do anything to interfere with conda, and just accept that the 201X.X release is compiled using the version that was up to date on that day, and that this may change the next time "conda install" is run. This is our current position. This has the downside that OpenMM will update to the latest version without you knowing, and that this impacts CUDA.

From my perspective, the current situation (C++ fixed version, Python/conda most-up2date) is satisfactory. I can see that this is a problem for OpenMM. Your solution, where you have set the version of OpenMM in build_sire.py is correct, and is the option you should use. It is not a hack.

**Comment by ppxasjsm** [comment]
The corruption/issues with the cuda-8.0 installer seem to have been resolved.
