### ISSUE TITLE
intended way to do MBAR free energy estimation in 2016.3 ? 

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#135]
After a fresh install of 2016.3 analyse_freenrg_mbar is broken (again)

julien@node010:~/projects/somd/MDM2ligands/runs-12w-26w-10ns-multipledistres/Nutlin3a-multipledistres/free/run001/discharge/output$ /home/$USER/sire.app/bin/analyse_freenrg_mbar -i lambda-0.000/simfile.dat lambda-0.050/simfile.dat lambda-0.100/simfile.dat lambda-0.200/simfile.dat lambda-0.300/simfile.dat lambda-0.400/simfile.dat lambda-0.500/simfile.dat lambda-0.600/simfile.dat lambda-0.700/simfile.dat lambda-0.800/simfile.dat lambda-0.900/simfile.dat lambda-1.000/simfile.dat --lam 0.000 0.050 0.100 0.200 0.300 0.400 0.500 0.600 0.700 0.800 0.900 1.000 --temperature 298.0 -o mbar.pmf --subsampling percentage --percentage 85 
Starting /home/julien/sire.app/bin/analyse_freenrg_mbar: number of threads equals 32

Traceback (most recent call last):
  File "/home/julien/sire.app/pkgs/sire-2016.3.1/share/Sire/scripts/analyse_freenrg_mbar.py", line 106, in <module>
    lam = np.array(args.lam)
NameError: name 'np' is not defined

How are we meant to use this app now?

**Comment by ppxasjsm** [comment]
mmhhh this is odd. It would automatically try and install numpy via conda, if it isn't installed. I'll have a look. I had fixed this I thought. I'll check. 

In any case ```~/sire.app/bin/conda install numpy``` should do the trick.

**Comment by jmichel80** [comment]
Numpy was already installed, i had to explicitly import the module for the code to work.

**Comment by chryswoods** [comment]
The problem looks like you have;

numpy = Sire.try_import("numpy")

at the top of the script, but then use

np.array(..)

throughout the script. You should choose either to call it np or numpy. I would change the import line to be

np = Sire.try_import("numpy")

(note that Sire.try_import() will automatically install the dependency if it doesn't exist)
