### ISSUE TITLE
somd: something new is broken in analyse_freenrg_mbar or somd-freenrg

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#138]
I am using a build from feature_standardstategen.
For  some weird reason I don't get the same number of entries written in the output files simfile.dat for all lambda windows.  
This causes analyse_freenrg_mbar to bail out. 
It seems that some runs did not write all output, yet the somd log files report that the simulation completed correctly. 
Anyone else (Toni?) is suffering from this issue?

**Comment by ppxasjsm** [comment]
mmhh this is odd. Can you provide me with input for potential reproduciblity. I have never had an issue of having things not written to output.

**Comment by jmichel80** [comment]
See for instance on section6

/home/julien/projects/somd/MDM2ligands/Nutlin3a-MDM2-ACE-6-120-NME/runs/complex/bound/run001/discharge/output

folders lam-0.050, 0.100, 0.200, 0.400, 0.600 had incomplete output. I trimmed all other lambda files so could run mbar.

**Comment by chryswoods** [comment]
Closing as no progress
