### ISSUE TITLE
example file for analyse_freenrg

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#144]
I want to double check that I didn't break functionality for analyse_freenrg. 
Is there an example file lying around?

**Comment by chryswoods** [comment]
I'll add the unit test SireIO/test_analyse_freenrg.py. This loads up the (now added) io/freenrgs.s3 file and tests that analyse_freenrg is able to correctly calculate the bennetts free energy as 0.7754 kcal mol-1. Is this helpful?

**Comment by chryswoods** [comment]
(sorry - should have said it is already added to michellab/SireUnitsTests)
