### ISSUE TITLE
Sire 2016.3 can't find input files

### ISSUE THREAD

**Issue by Steboss** [michellab/Sire#145]
Hi 

This may be an easy task
I have just installed  the latest version of Sire (downloaded yesterday from devel branch) both on my workstation and cluster
The installation goes fine ( I am using gcc-4.8 ) but when I am trying to run a simulation where I specified the input files to use in the sim.cfg file I have an error 
```
Please supply the name of an existing topology, coordinate and morph file.
(cannot find coordinate file "../../input/SYSTEM.crd")
(cannot find topology file "../../input/SYSTEM.top")
(cannot find morph file "../../input/MORPH.pert")
```
I have checked paths and sim.cfg but everything is correctly given
The only way to overcome this error is to explicitly pass to somd-freenrg  topology, crd file and MORPH
I attached a zip to reproduce the error

Thanks  :)
[finding_files.zip](https://github.com/michellab/Sire/files/857767/finding_files.zip)

**Comment by jmichel80** [comment]
Hi Stefano,

See #132

Chris is working on a bugfix. In the meantime, following the procedure in #132 should get you there.
