### ISSUE TITLE
Failing travis build

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#15]
I have resolved dependencies for 
-cmake
-g++
but not openmm. The build fails due to Openmm not being installed. There is a .deb package available, which needs to be whitelisted, for a container based infrastructrue build:
http://docs.travis-ci.com/user/workers/container-based-infrastructure/
This type of build is faster.
In the mean time I might try an non container based infrastructure travis build.

**Comment by ppxasjsm** [comment]
So now it seems I can't build the bundled Qt version:
```make[1]: Leaving directory `/home/travis/build/michellab/Sire/build/build_bundled/qtbase/src'
make: *** [sub-src-make_first] Error 2
make: Target `first' not remade because of errors.
CMake Error at src/bundled/install_qt5.cmake:122 (message):
  Cannot build Qt5.  Please go to the mailing list for help.```

Did an error like this occur before?

**Comment by jmichel80** [comment]
No. Can you post a more detailed error message?
What OS are you using for this build?

--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

On Wed, Jul 15, 2015 at 10:04 AM, ppxasjsm <notifications@github.com> wrote:

> So now it seems I can't build the bundled Qt version:
> make[1]: Leaving directory
> `/home/travis/build/michellab/Sire/build/build_bundled/qtbase/src'
> make: *** [sub-src-make_first] Error 2
> make: Target `first' not remade because of errors.
> CMake Error at src/bundled/install_qt5.cmake:122 (message):
> Cannot build Qt5. Please go to the mailing list for help.
>
> Did an error like this occur before?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/15#issuecomment-121536559>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
I get something like this:
```{standard input}: Assembler messages:

{standard input}:20090: Warning: end of file not at end of a line; newline inserted

/usr/bin/g++-4.6 -c -pipe -O2 -fvisibility=hidden -fvisibility-inlines-hidden -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_LIBUDEV -DQT_NO_XCB -DQT_NO_XKBCOMMON -DQT_NO_USING_NAMESPACE -DQT_BUILD_CORE_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DELF_INTERPRETER=\"/lib64/ld-linux-x86-64.so.2\" -DPCRE_HAVE_CONFIG_H -DQT_CORE_LIB -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -I../../mkspecs/linux-g++ -I. -I../../include -I../../include/QtCore -I../../include/QtCore/5.2.0 -I../../include/QtCore/5.2.0/QtCore -Iglobal -I../3rdparty/zlib -I../3rdparty/pcre -I../3rdparty/harfbuzz/src -I../3rdparty/md5 -I../3rdparty/md4 -I../3rdparty/sha3 -I.moc -o .obj/moc_qnoncontiguousbytedevice_p.o .moc/moc_qnoncontiguousbytedevice_p.cpp

g++-4.6: internal compiler error: Killed (program cc1plus)

Please submit a full bug report,

with preprocessed source if appropriate.

See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.

make[2]: *** [.obj/qmetatype.o] Error 4

/usr/bin/g++-4.6 -c -pipe -O2 -fvisibility=hidden -fvisibility-inlines-hidden -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_LIBUDEV -DQT_NO_XCB -DQT_NO_XKBCOMMON -DQT_NO_USING_NAMESPACE -DQT_BUILD_CORE_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DELF_INTERPRETER=\"/lib64/ld-linux-x86-64.so.2\" -DPCRE_HAVE_CONFIG_H -DQT_CORE_LIB -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -I../../mkspecs/linux-g++ -I. -I../../include -I../../include/QtCore -I../../include/QtCore/5.2.0 -I../../include/QtCore/5.2.0/QtCore -Iglobal -I../3rdparty/zlib -I../3rdparty/pcre -I../3rdparty/harfbuzz/src -I../3rdparty/md5 -I../3rdparty/md4 -I../3rdparty/sha3 -I.moc -o .obj/moc_qtextstream_p.o .moc/moc_qtextstream_p.cpp

{standard input}: Assembler messages:

{standard input}:14837: Warning: end of file not at end of a line; newline inserted

{standard input}:14909: Error: unknown pseudo-op: `.cfi_remember_st'

{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive

g++-4.6: internal compiler error: Killed (program cc1plus)

Please submit a full bug report,

with preprocessed source if appropriate.

See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.

make[2]: *** [.obj/qxmlstream.o] Error 4```

And much more of the same.

**Comment by jmichel80** [comment]
Do you know what OS the travis server runs?

--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

On Wed, Jul 15, 2015 at 1:42 PM, ppxasjsm <notifications@github.com> wrote:

> I get something like this:
> ```{standard input}: Assembler messages:
>
> {standard input}:20090: Warning: end of file not at end of a line; newline
> inserted
>
> /usr/bin/g++-4.6 -c -pipe -O2 -fvisibility=hidden
> -fvisibility-inlines-hidden -std=c++0x -Wall -W -D_REENTRANT -fPIC
> -DQT_NO_LIBUDEV -DQT_NO_XCB -DQT_NO_XKBCOMMON -DQT_NO_USING_NAMESPACE
> -DQT_BUILD_CORE_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII
> -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER
> -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000
> -DELF_INTERPRETER=\"/lib64/ld-linux-x86-64.so.2\" -DPCRE_HAVE_CONFIG_H
> -DQT_CORE_LIB -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG
> -I../../mkspecs/linux-g++ -I. -I../../include -I../../include/QtCore
> -I../../include/QtCore/5.2.0 -I../../include/QtCore/5.2.0/QtCore -Iglobal
> -I../3rdparty/zlib -I../3rdparty/pcre -I../3rdparty/harfbuzz/src
> -I../3rdparty/md5 -I../3rdparty/md4 -I../3rdparty/sha3 -I.moc -o
> .obj/moc_qnoncontiguousbytedevice_p.o
> .moc/moc_qnoncontiguousbytedevice_p.cpp
>
> g++-4.6: internal compiler error: Killed (program cc1plus)
>
> Please submit a full bug report,
>
> with preprocessed source if appropriate.
>
> See file:///usr/share/doc/gcc-4.6/README.Bugs for instructions.
>
> make[2]: *** [.obj/qmetatype.o] Error 4
>
> /usr/bin/g++-4.6 -c -pipe -O2 -fvisibility=hidden
> -fvisibility-inlines-hidden -std=c++0x -Wall -W -D_REENTRANT -fPIC
> -DQT_NO_LIBUDEV -DQT_NO_XCB -DQT_NO_XKBCOMMON -DQT_NO_USING_NAMESPACE
> -DQT_BUILD_CORE_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII
> -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER
> -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000
> -DELF_INTERPRETER=\"/lib64/ld-linux-x86-64.so.2\" -DPCRE_HAVE_CONFIG_H
> -DQT_CORE_LIB -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG
> -I../../mkspecs/linux-g++ -I. -I../../include -I../../include/QtCore
> -I../../include/QtCore/5.2.0 -I../../include/QtCore/5.2.0/QtCore -Iglobal
> -I../3rdparty/zlib -I../3rdparty/pcre -I../3rdparty/harfbuzz/src
> -I../3rdparty/md5 -I../3rdparty/md4 -I../3rdparty/sha3 -I.moc -o
> .obj/moc_qtextstream_p.o .moc/moc_qtextstream_p.cpp
>
> {standard input}: Assembler messages:
>
> {standard input}:14837: Warning: end of file not at end of a line; newline
> inserted
>
> {standard input}:14909: Error: unknown pseudo-op: `.cfi_remember_st'
>
> {standard input}: Error: open CFI at the end of file; missing .cfi_endproc
> directive
>
> g++-4.6: internal compiler error: Killed (program cc1plus)
>
> Please submit a full bug report,
>
> with preprocessed source if appropriate.
>
> See file:///usr/share/doc/gcc-4.6/README.Bugs for instructions.
>
> make[2]: *** [.obj/qxmlstream.o] Error 4```
>
> And much more of the same.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/15#issuecomment-121604097>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
Vanilla Ubuntu 12.04, that's why I am so surprised. Are there any particular packages I need to have installed for running on empty system? Using clang as a compiler resulted in problems with compiling TBB. That error I managed to resolve, by using gcc instead, but with Qt5 I have no idea. I can install anything I want via apt. So I can preconfigure the system. 
I install the following packages:
```
  - sudo add-apt-repository --yes ppa:kubuntu-ppa/backports  # allows me to install cmake v 2.8.12 and higher
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake
  - sudo apt-get install build-essential
  - sudo apt-get install libgtk2.0-dev 
  - sudo apt-get install libgl1-mesa-dev
  - sudo apt-get install g++-4.6 # should be default anyway
```

**Comment by chryswoods** [comment]
Hi Antonia,

How much free memory is there on the build machine? I've seen this error before when g++ is killed because the machine has run out of memory. The cmake scripts try to build Qt in parallel using the same number of threads as there are cores. The number of threads is printed near the top of the cmake output. You could try editing the cmake file to only use one thread (this is in install_qt5.cmake, replace ${NCORES} with 1, or set ${NCORES} to 1 at the top of the file).

If this doesn't work, try to install again from a completely clean installation. Qt uses pre-compiled headers and there may be some confusion caused by your previous attempts to compile Qt.

The other thing to try is to cd into the Qt build directory and to run the g++ command by hand. The command is given to you in the output, e.g.

/usr/bin/g++-4.6 -c -pipe -O2 -fvisibility=hidden
 -fvisibility-inlines-hidden -std=c++0x -Wall -W -D_REENTRANT -fPIC
 -DQT_NO_LIBUDEV -DQT_NO_XCB -DQT_NO_XKBCOMMON -DQT_NO_USING_NAMESPACE
 -DQT_BUILD_CORE_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII
 -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER
 -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000
 -DELF_INTERPRETER=\"/lib64/ld-linux-x86-64.so.2\" -DPCRE_HAVE_CONFIG_H
 -DQT_CORE_LIB -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG
 -I../../mkspecs/linux-g++ -I. -I../../include -I../../include/QtCore
 -I../../include/QtCore/5.2.0 -I../../include/QtCore/5.2.0/QtCore -Iglobal
 -I../3rdparty/zlib -I../3rdparty/pcre -I../3rdparty/harfbuzz/src
 -I../3rdparty/md5 -I../3rdparty/md4 -I../3rdparty/sha3 -I.moc -o
 .obj/moc_qtextstream_p.o .moc/moc_qtextstream_p.cpp

You can then see if g++ still crashes, and can also use things like "top" to watch the memory consumption during the compile. You can also turn on all of g++'s verbosity options to see if there is more information about the crash.

  Cheers,

  Christopher

**Comment by ppxasjsm** [comment]
Hi Christopher,
the install is clean each time on a virtual machine, to exactly avoid 'cross-contamination' of old compilation attempts. 
I should have 2 cores available for the compilation and 3GB of RAM. That should be sufficient shouldn't it?
I'll try what you suggest. It isn't that simple to just try and compile it by hand since everything is automated, but hopefully, i'll get it to work.

**Comment by chryswoods** [comment]
Hi Antonia,

2 cores and 3 GB should be ok, although some C++ compiles can use several GB per process (mainly heavily templated code, e.g. the boost::python wrappers). I would suggest that if this doesn't work, that you try to compile Qt5 alone. The install-qt5.cmake file has all of the commands used to unpack, configure and compile Qt. Just copy these into a bash script and run these one after another. Then, after they have run, if g++ still crashes, add an extra line to the bash script that cd's into the build directory and runs the failing g++ command again (just type it into the bash script in the same way as you would type it onto the command line).

  Let me know how you get on,

  Cheers,

  Christopher

**Comment by ppxasjsm** [comment]
Hi Christopher, 
limiting the number of cores to 1 meant that Qt compiled fine. Thank you for the tip. I really had no idea where to look for an error there. Sire itself seems to now build (32%), since it is only building on one core it seems to be quite slow, but no more errors, so far. 

Thanks!
Antonia

**Comment by chryswoods** [comment]
No problem. I would leave it on one core as the python wrappers use a lot of RAM. clang uses less memory. I am surprised there was an error with Intel TBB, especially as I use clang on my mac. It is something I should look into when I have a free minute... ;-)
