### ISSUE TITLE
units of energy output by analyse_freenrg mbar

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#153]
In the new implementation, analyse_freenrg mbar outputs energies in reduced units

(...)
#MBAR free energy difference in reduced units: 
-0.005111, 0.003429  #WARNING SUBSAMLING ENERGIES RESULTED IN LESS THAN 50 SAMPLES, CONSIDER RERUN WITHOUT SUBSAMPLE OPTION
#TI free energy difference in reduced units: 
12.088484  #WARNING SUBSAMLING GRADIENTS RESULTED IN LESS THAN 50 SAMPLES, CONSIDER RERUN WITHOUT SUBSAMPLE OPTION

This will confuse most non physicists using the code as they won't know how to convert to kJ/mol or kcal/mol. The output doesn't say what is the definition of the reduced unit of energy. Presumably U*=U/kbT. 
Many users won't know where to find the value of the temperature used in the simulations. 

@ppxasjsm , can you change the code to output energies in kcal/mol, using the temperature defined in simfile.dat

**Comment by jmichel80** [comment]
A few other formatting issues with the output
 ''WARNING SUBSAMLING ...''
--> Fix typo


(...)
#PMF from MBAR in reduced units
0.0000 0.0250 -18.8783 0.0116
(...)

Above is not PMF, it's DeltaG(U(lam1) -> U(lam2) )

0.9900 1.0000 0.8858 0.0002
#PMF from MBAR in reduced units
0.0000 0.0000 0.0000
0.0250 -18.8783 0.0116
0.0500 -29.0655 0.0172
0.0750 -33.7746 0.0213

Output all energies in kcal/mol for consistency with the final value.

**Comment by ppxasjsm** [comment]
If you use the --temperature flag it outputs it in kcal/mol.

**Comment by ppxasjsm** [comment]
I can make sure it uses the simfile.dat temperature information instead.

**Comment by jmichel80** [comment]
Ah I didn't realise this.  Should the temperature be given in Celsius or Kelvin ? The help is unclear. 
We should use the temperature listed in simfile.dat by default, unless the user has explicitly passed a temperature keyword (and if there is a mismatch with the contents of simfile.dat write a warning in the output).

**Comment by ppxasjsm** [comment]
mmhh I feel like I had implemented something like that already. Temperature should be in Kelvin. I'll update the  help.

**Comment by jmichel80** [comment]
Also I suggest to catch user typos. 

~/sire.app/bin/analyse_freenrg mbar -i lambda-*/simfile.dat -p 95 -temperature 298

does run but report the results in reduced units. Ideally the code should complain that the keyword argument was not recognised.

**Comment by jmichel80** [comment]
Another quick fix that would be useful now is to also allow discarding data by number of measurements rather than percentage of dataset. 
This would allow discarding a consistent trajectory time for lambda values that were run with a different duration. 

something like --discard 10000  to cause the first 10,000 measurements to be discarded.

**Comment by ppxasjsm** [comment]
Ok I'll try and add these things now and push the fixes to devel.

**Comment by chryswoods** [comment]
Closing as no progress
