### ISSUE TITLE
parser_binary for wrapper creation

### ISSUE THREAD

**Issue by Steboss** [michellab/Sire#154]
I was trying to create a wrapper in Sire following the instructions into wrapper folder.
At the last step, when I am running in module Tools: ``` ~/sire.app/bin/python  ../Autogenerate/create_wrappers.py ``` I got this error:
```
/home/steboss/sire_RF/sire.app/lib/python3.5/site-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
/home/steboss/sire_RF/sire.app/lib/python3.5/site-packages/pyplusplus/decl_wrappers/algorithm.py:51: DeprecationWarning: LOCALE flag with a str pattern is deprecated. Will be an error in 3.6
  __RE_VALID_IDENTIFIER = re.compile( r"[_a-z]\w*", re.I | re.L | re.U )
Traceback (most recent call last):
  File "../AutoGenerate/create_wrappers.py", line 22, in <module>
    from pyplusplus.module_builder import module_builder_t
  File "/home/steboss/sire_RF/sire.app/lib/python3.5/site-packages/pyplusplus/__init__.py", line 25, in <module>
    from . import creators_factory
  File "/home/steboss/sire_RF/sire.app/lib/python3.5/site-packages/pyplusplus/creators_factory/__init__.py", line 7, in <module>
    from .ctypes_creator import ctypes_creator_t
  File "/home/steboss/sire_RF/sire.app/lib/python3.5/site-packages/pyplusplus/creators_factory/ctypes_creator.py", line 8, in <module>
    from pygccxml import binary_parsers
ImportError: cannot import name 'binary_parsers'
```
In ~/sire.app/lib/python-3.5/site-packages/pygccxml  I cannot find anything about binary_parsers
Where am I wrong?

Thank you 

Stefano

**Comment by chryswoods** [comment]
Have you installed pygccxml as instructed? When you type "import pygccxml" in sire.app/bin/ipython, what do you see?

**Comment by Steboss** [comment]
Hi Chris,

Yes, I have installed it 
In ipython I can import pygccxml but when I am doing:
```from pygccxml import binary_parsers```
I got the error ```cannot import name 'binary_parsers'```

**Comment by chryswoods** [comment]
I've looked into it and it is because pygccxml changed their API in version 1.9.0 and removed the binary_parsers module. Py++ is being updated to fix this, but the fix is not yet out (see https://bitbucket.org/ompl/pyplusplus/commits/all and https://bitbucket.org/ompl/ompl/issues/320/missing-py_pyplusplus).

This means that you need to install version 1.8.5. To do this, first remove the 1.9.0 version of pygccxml using

~/sire.app/bin/pip uninstall pygccxml

Then install the 1.8.5 version using

~/sire.app/bin/pip install -Iv pygccxml==1.8.5

This works for me (just tested). I will updated the wrapper generation instructions with this information. Thanks for finding the reporting this issue :-)

**Comment by Steboss** [comment]
Great! 
It works now, thanks very much

Actually, I had another "noob" question for generating  new wrappers. 
In order to see if I had done everything correctly, in the wrapper module folder, where I want to add the new wrapper, should I have a file called "module_info"?
Thanks very much

**Comment by chryswoods** [comment]
module_info is a file that is created automatically by the wrapper generation process. Are you generating wrappers for a new class in an existing module (i.e. Mol), or for a new module (a new directory that you've created yourself)?

If you are adding a new class into an existing module, then using AutoGenerate/scanheaders.py followed by "cd Module; $SIRE/bin/python ../AutoGenerate/create_wrappers.y" should do everything for you automatically. There may need to be some special extra code that you need to add depending on whether your class is doing anything clever (only needed for a small number of classes). In these cases, you would need to add the special code to Module/special_code.py. Take a look at Mol/special_code.py for pretty much all of the different types of special things that are needed.

If you are creating a new module, then you need to let AutoGenerate/scanheaders.py know that this module needs to be scanned. This is handled at the end of the script, in the "__main__" section, i.e. 

```python
if __name__ == "__main__":
    
    modules = { "Analysis" : "SireAnalysis",
                "Base" : "SireBase",
                "CAS" : "SireCAS",
                "Cluster" : "SireCluster",
                "FF" : "SireFF",
                "ID" : "SireID",
                "IO" : "SireIO",
                "Maths" : "SireMaths",
                "MM" : "SireMM",
                "Mol" : "SireMol",
                "Move" : "SireMove",
                "Squire" : "Squire",
                "Stream" : "SireStream",
                "System" : "SireSystem",
                "Units" : "SireUnits",
                "Vol" : "SireVol" }
```

As you can see, this `modules` dictionary associates a directory containing C++ code (e.g. SireAnalysis) with a Python module that needs to be generated (e.g. Analysis). The script will then scan through all of the C++ source directories to find all exposed classes, creating all of the data files that are needed (e.g. module_info, classdb.data etc. etc.).

If you want to add a new module, called Foo, with C++ source code in Sire/corelib/src/libs/SireFoo, then add this to the `modules` dictionary, i.e.

```python
if __name__ == "__main__":
    
    modules = { "Analysis" : "SireAnalysis",
                "Base" : "SireBase",
                "CAS" : "SireCAS",
                "Cluster" : "SireCluster",
                "FF" : "SireFF",
                "Foo" : "SireFoo",
                "ID" : "SireID",
                "IO" : "SireIO",
                "Maths" : "SireMaths",
                "MM" : "SireMM",
                "Mol" : "SireMol",
                "Move" : "SireMove",
                "Squire" : "Squire",
                "Stream" : "SireStream",
                "System" : "SireSystem",
                "Units" : "SireUnits",
                "Vol" : "SireVol" }
```

I hope this helps. If you need anything more, feel free to ask :-)

**Comment by chryswoods** [comment]
Closing as likely fixed and due to inactivity
