### ISSUE TITLE
travis builds

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#162]
Hi all, 

It seems that all travis builds on recent versions of the code now take several hours and are killed after a while. I don't know why the build time has gone up significantly. @chryswoods any idea?

**Comment by chryswoods** [comment]
Some of the newer code caused the compiler to use more memory than travis makes available, causing slowdown. We have been flirting with the limits of travis for a while now, and, despite travis increasing them for us, have broken through yet again. I am setting up a dedicated CI service at Bristol now which will remove our reliance on travis. In the interim, we need to run the tests manually

**Comment by chryswoods** [comment]
Closing as I am setting up a replacement for travis for Sire. We have outgrown the free infrastructure.
