### ISSUE TITLE
OpenMMMMD return the wrong lambda value

### ISSUE THREAD

**Issue by Steboss** [michellab/Sire#164]
Hi everybody,

there's a problem in the latest commit (https://github.com/michellab/Sire/commit/03dcba910fcbbc0bbc0a2097267695dce7be8567)  for  Sire 2017.2.0 
It may be due to some changes I made in OpenMMMD.py, but when an alchemical free energy calculation is run, the value of lambda is always wrong and fixed to 0.00
I attached a zip file with a test for a ethane to methanol simulation in vacuum.
[sire_lambda.zip](https://github.com/michellab/Sire/files/1359322/sire_lambda.zip)

**Comment by jmichel80** [comment]
@ppxasjsm can you take a look ?

**Comment by ppxasjsm** [comment]
sure

**Comment by Steboss** [comment]
I am sorry, 
Thankfully OpenMMMD works fine with  the lambda values. I didn't realize I had a bug in my script.
