### ISSUE TITLE
Generation of wrappers fails to extract documentation on some machines

### ISSUE THREAD

**Issue by chryswoods** [michellab/Sire#167]
The AutoGenerate/create_wrappers.py script that generates wrappers should automatically extract C++ documentation and add that to the Python wrappers. This works on some machines, but doesn't work on others. We need to debug this to find out what is going wrong. Please could you check if the docs are correctly extracted on your machine, and if not, let me know here what operating system you are using.

For information, the C++ documentation is extracted from source code documentation in the cpp file. This is generated by AutoGenerate/scanheaders.py, which uses some custom python code I had to write to extract comments (functions add_doc and extract_docs). These are complemented by AutoGenerate/doxygen.py, which is modified from an existing C++ doxygen extractor and py++ code that gets any documentation from the header files. There are two routes, as doxygen.py doesn't like getting documentation from the cpp files, which is where most of the documentation is located. I thus found writing code in scanheaders.py that pulled this documentation out and made it available to create_wrappers.py to be easier than moving all of the documentation into the header files.

**Comment by jmichel80** [comment]
@Steboss can you check and give an update to @chryswoods  ?
