### ISSUE TITLE
Free energy calculations with no constraints

### ISSUE THREAD

**Issue by Steboss** [michellab/Sire#17]
I am trying to perform  neopentane to methane free energy simulation according to this transformation:

![neopentane](https://cloud.githubusercontent.com/assets/11866490/8651805/0dfbb4f0-2973-11e5-84ad-a67832f03dd5.png)

But always in water simulation, after minimization and equilibration, I got this error:

Traceback (most recent call last):
  File "/home/steboss/sire.app/share/Sire/scripts/somd-freenrg.py", line 140, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/home/steboss/sire.app/bundled/lib/python3.3/site-packages/Sire/Tools/**init**.py", line 135, in inner
    retval = func()
  File "/home/steboss/sire.app/bundled/lib/python3.3/site-packages/Sire/Tools/OpenMMMD.py", line 1233, in runFreeNrg
    system = moves.move(system, nmoves.val, True)
RuntimeError: The periodic box size has decreased to less than twice the nonbonded cutoff.

I have played around a little bit and written down this results:
- configuration_1:   no constraint
                             0.5 fs timestep
                             10 A cutoff
                             Barostat ON 
                             Thermostat ON
                             Minimin ON
                             Equil ON
                             CUDA
                             CutoffPeriodic  
                                                                           Error: Box decreased :-1: 
- configuration_2: same as configuration_1 but:  
                              No barostat
                                                                             Error: Nan or Inf generation :-1: 
- configuration_3: same as configuration_1 but:
                              No barostat
                              No equil
                                                                              Simulation run! :dancers: 
- configuration_4: same as configuration_1 but:
                              No barostat
                              No minimization but Equilibration ON
                                                                              Simulation run! :+1: 
- configuration_5: same as configuration_1 but:
                             No barostat
                             No thermostat
                                                                                Error: Nan or Inf generation :-1: 
- configuration_6: same as configuration_1 but:
                             Cutoff NON periodic
                                                                             Simulation run but E_total ~ 10^14 kcal/mol :-1:  

On the other hand, it is possible to run such a simulation if perturbation is done on the external carbon atom while the central one remain a carbon.

**Comment by ppxasjsm** [comment]
Hey,
this looks quite similar to the problems I had also observed. I also seem to see similar things happening in the code changes I am not working enough on. The error, of the boxsize reducing to less than twize the cutoff length is an openMM error I think. 
In configuration_5 did you try and run an NVE simulation? I don't think you can just do it like that. 
Configuration_6 is nonsensical. 

A few questions:
- Does this happen for all values of lambda? (i.e. the simulation breaking?)
- Have you tried running a simulation only with openMM for the starting point? I think there might be some script for that if you want. 
- I have noticed, that Sire+openMM equilibrates the box volume much more slowly than just using openmm. I haven't found a reason for this yet.
-Have you tracked the box volume over time?
-Did you look at the starting configuration in VMD? Do they look ok? Or does VMD think that some atoms are too close to each other?
-In your FESetup protocol, how much time do you give for equilibration?
I think I'll be looking into this in more detail today.

**Comment by Steboss** [comment]
Hi Toni!

Sorry I did not specify the lambda windows. Actually this problem appear only for this lambda windows: 
0.5625, 0.625, 0.6875, 0.75, 0.8125, 0.875 over 3 indipendent runs.
So when lambda is approaching to 1. At lambda = 1 it works. 
I have tried to reparameterize the molecule with FESetup 0.5.1 and the error appear around 0.625 0.6875 only. So there is a randomness in lambda windows.

Configuration 5 and 6 are just to try what happens modifying parameters.

I have tried to run a MD with OpenMM for starting point and it works perfectly.
I would like to run a MD with OpenMM with the molecule parameters at lambda 0.75 but I have to figure out how to translate all the values of the molecule.

I track the volume over time for the other lambda windows and it seems ok, I have fluctuations in volume but no clashes or similar things. For this simulation it's hard to detect box volume, but I have measured it at the equilibration point using Sire and it seems ok: before and after the minimization I have the same value of the box.

FESetup  equilibration is 1000 steps for heating up the system and 15000 steps for equilibration pressure, so as I used usual for all other simulations

**Comment by jmichel80** [comment]
I have asked Stefano to report the issues with running without constraints,
but addressing these is not high priority at the moment as we do not
normally run MD simulations without constraints.

Julien

On Tuesday, July 14, 2015, ppxasjsm <notifications@github.com> wrote:

> Hey,
> this looks quite similar to the problems I had also observed. I also seem
> to see similar things happening in the code changes I am not working enough
> on. The error, of the boxsize reducing to less than twize the cutoff length
> is an openMM error I think.
> In configuration_5 did you try and run an NVE simulation? I don't think
> you can just do it like that.
> Configuration_6 is nonsensical.
>
> A few questions:
>
>    - Does this happen for all values of lambda? (i.e. the simulation
>    breaking?)
>    - Have you tried running a simulation only with openMM for the
>    starting point? I think there might be some script for that if you want.
>    - I have noticed, that Sire+openMM equilibrates the box volume much
>    more slowly than just using openmm. I haven't found a reason for this yet.
>    -Have you tracked the box volume over time? -Did you look at the starting
>    configuration in VMD? Do they look ok? Or does VMD think that some atoms
>    are too close to each other? -In your FESetup protocol, how much time do
>    you give for equilibration? I think I'll be looking into this in more
>    detail today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/17#issuecomment-121153824>.
>


-- 
--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263
School of Chemistry
University of Edinburgh
West Mains Road
Edinburgh, EH9 3JJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

**Comment by jmichel80** [comment]
this is now supported by the constraint flag 'none-notwater' 
The default recommend constraint option is now 'hbonds-notperturbed'
