### ISSUE TITLE
sommmd debbug statements

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#20]
sommmd (openmmIntegrator.cpp) debug statements seem to have inherited a couple of copy paste methods from the free energy calculation method, providing information about lambdas that don't exist.

**Comment by ppxasjsm** [comment]
Misleading naming
```
somd -h
"/home/ppxasjsm/Software/sire.app/share/Sire/scripts/somd.py" 
Starting somd: number of threads equals 8

usage: sommmd [-h] [-C [CONFIG]] [-H] [--author] [--version]
              [-t [TOPOLOGY_FILE]] [-c [COORDINATE_FILE]] [-d [DEVICE]]
              [-n [NMOVES]] [-p [PLATFORM]]
```
Is it sommmd, or somd?

**Comment by Steboss** [comment]
I think it should be somd, but I remember that Gaetano's Sire was: sommmd (
sire openMM Molecular Dynamics?)

2015-07-20 11:45 GMT+01:00 ppxasjsm <notifications@github.com>:

**Comment by jmichel80** [comment]
somd.
I once moaned that there were too many 'm's in sommmd and I could never
remember how many m to type to call the binary !

--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

On Mon, Jul 20, 2015 at 11:47 AM, Steboss <notifications@github.com> wrote:

> I think it should be somd, but I remember that Gaetano's Sire was: sommmd (
> sire openMM Molecular Dynamics?)
>
> 2015-07-20 11:45 GMT+01:00 ppxasjsm <notifications@github.com>:
>
> > Misleading naming
> >
> > somd -h
> > "/home/ppxasjsm/Software/sire.app/share/Sire/scripts/somd.py"
> > Starting somd: number of threads equals 8
> >
> > usage: sommmd [-h] [-C [CONFIG]] [-H] [--author] [--version]
> > [-t [TOPOLOGY_FILE]] [-c [COORDINATE_FILE]] [-d [DEVICE]]
> > [-n [NMOVES]] [-p [PLATFORM]]
> >
> > Is it sommmd, or somd?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/michellab/Sire/issues/20#issuecomment-122846677>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/20#issuecomment-122847016>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
ok I'll adjust the help message

**Comment by ppxasjsm** [comment]
Done.
