### ISSUE TITLE
Compile error with 2018.1.0

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#202]
Hi, 

I upgraded my system to ubuntu 16.04 to have the correct cmake dependency to compile 2018.1.0 

I ran in trouble compiling corelib. 

Any clue ? 

[ 77%] Built target SireCluster
Scanning dependencies of target SireMove
[ 77%] Building CXX object src/libs/SireMove/CMakeFiles/SireMove.dir/register_siremove.cpp.o
In file included from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/QDateTime:1:0,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:34,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdatetime.h:88:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5,0)
                        ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdatetime.h:279:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 2)
                        ^
In file included from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qbytearray.h:45:0,
                 from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/QByteArray:1,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:32,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:56:21: error: expected ‘;’ at end of member declaration
     inline bool ref() Q_DECL_NOTHROW {
                     ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:56:23: error: ‘Q_DECL_NOTHROW’ does not name a type
     inline bool ref() Q_DECL_NOTHROW {
                       ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:65:23: error: expected ‘;’ at end of member declaration
     inline bool deref() Q_DECL_NOTHROW {
                       ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:65:25: error: ‘Q_DECL_NOTHROW’ does not name a type
     inline bool deref() Q_DECL_NOTHROW {
                         ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:74:35: error: expected ‘;’ at end of member declaration
     bool setSharable(bool sharable) Q_DECL_NOTHROW
                                   ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:74:37: error: ‘Q_DECL_NOTHROW’ does not name a type
     bool setSharable(bool sharable) Q_DECL_NOTHROW
                                     ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:83:21: error: expected ‘;’ at end of member declaration
     bool isStatic() const Q_DECL_NOTHROW
                     ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:83:27: error: ‘Q_DECL_NOTHROW’ does not name a type
     bool isStatic() const Q_DECL_NOTHROW
                           ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:89:23: error: expected ‘;’ at end of member declaration
     bool isSharable() const Q_DECL_NOTHROW
                       ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:89:29: error: ‘Q_DECL_NOTHROW’ does not name a type
     bool isSharable() const Q_DECL_NOTHROW
                             ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:95:21: error: expected ‘;’ at end of member declaration
     bool isShared() const Q_DECL_NOTHROW
                     ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:95:27: error: ‘Q_DECL_NOTHROW’ does not name a type
     bool isShared() const Q_DECL_NOTHROW
                           ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:101:26: error: expected ‘;’ at end of member declaration
     void initializeOwned() Q_DECL_NOTHROW { atomic.store(1); }
                          ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:101:28: error: ‘Q_DECL_NOTHROW’ does not name a type
     void initializeOwned() Q_DECL_NOTHROW { atomic.store(1); }
                            ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:102:31: error: expected ‘;’ at end of member declaration
     void initializeUnsharable() Q_DECL_NOTHROW { atomic.store(0); }
                               ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:102:33: error: ‘Q_DECL_NOTHROW’ does not name a type
     void initializeUnsharable() Q_DECL_NOTHROW { atomic.store(0); }
                                 ^
In file included from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qbytearray.h:47:0,
                 from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/QByteArray:1,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:32,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qarraydata.h: In static member function ‘static QTypedArrayData<T>* QTypedArrayData<T>::allocate(size_t, QArrayData::AllocationOptions)’:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qarraydata.h:222:70: error: there are no arguments to ‘Q_STATIC_ASSERT’ that depend on a template parameter, so a declaration of ‘Q_STATIC_ASSERT’ must be available [-fpermissive]
         Q_STATIC_ASSERT(sizeof(QTypedArrayData) == sizeof(QArrayData));
                                                                      ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qarraydata.h:222:70: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qarraydata.h: In static member function ‘static void QTypedArrayData<T>::deallocate(QArrayData*)’:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qarraydata.h:229:70: error: there are no arguments to ‘Q_STATIC_ASSERT’ that depend on a template parameter, so a declaration of ‘Q_STATIC_ASSERT’ must be available [-fpermissive]
         Q_STATIC_ASSERT(sizeof(QTypedArrayData) == sizeof(QArrayData));
                                                                      ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qarraydata.h: In static member function ‘static QTypedArrayData<T>* QTypedArrayData<T>::fromRawData(const T*, size_t, QArrayData::AllocationOptions)’:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qarraydata.h:236:70: error: there are no arguments to ‘Q_STATIC_ASSERT’ that depend on a template parameter, so a declaration of ‘Q_STATIC_ASSERT’ must be available [-fpermissive]
         Q_STATIC_ASSERT(sizeof(QTypedArrayData) == sizeof(QArrayData));
                                                                      ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qarraydata.h: In static member function ‘static QTypedArrayData<T>* QTypedArrayData<T>::sharedNull()’:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qarraydata.h:250:70: error: there are no arguments to ‘Q_STATIC_ASSERT’ that depend on a template parameter, so a declaration of ‘Q_STATIC_ASSERT’ must be available [-fpermissive]
         Q_STATIC_ASSERT(sizeof(QTypedArrayData) == sizeof(QArrayData));
                                                                      ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qarraydata.h: In static member function ‘static QTypedArrayData<T>* QTypedArrayData<T>::sharedEmpty()’:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qarraydata.h:256:70: error: there are no arguments to ‘Q_STATIC_ASSERT’ that depend on a template parameter, so a declaration of ‘Q_STATIC_ASSERT’ must be available [-fpermissive]
         Q_STATIC_ASSERT(sizeof(QTypedArrayData) == sizeof(QArrayData));
                                                                      ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qarraydata.h: In static member function ‘static QTypedArrayData<T>* QTypedArrayData<T>::unsharableEmpty()’:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qarraydata.h:262:70: error: there are no arguments to ‘Q_STATIC_ASSERT’ that depend on a template parameter, so a declaration of ‘Q_STATIC_ASSERT’ must be available [-fpermissive]
         Q_STATIC_ASSERT(sizeof(QTypedArrayData) == sizeof(QArrayData));
                                                                      ^
In file included from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/QDateTime:1:0,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:34,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdatetime.h: At global scope:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdatetime.h:304:42: error: expected ‘;’ at end of member declaration
     static qint64 currentMSecsSinceEpoch() Q_DECL_NOTHROW;
                                          ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdatetime.h:304:44: error: ‘Q_DECL_NOTHROW’ does not name a type
     static qint64 currentMSecsSinceEpoch() Q_DECL_NOTHROW;
                                            ^
In file included from /home/julien/anaconda3/include/QtCore/qatomic.h:45:0,
                 from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:45,
                 from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qbytearray.h:45,
                 from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/QByteArray:1,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:32,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdatetime.h: In function ‘bool qIsDetached(T&) [with T = QDateTime]’:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdatetime.h:324:1: error: ‘class QDateTime’ has no member named ‘isDetached’
 Q_DECLARE_SHARED(QDateTime)
 ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdatetime.h: In function ‘void qSwap(T&, T&) [with T = QDateTime]’:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdatetime.h:324:1: error: ‘class QDateTime’ has no member named ‘data_ptr’
 Q_DECLARE_SHARED(QDateTime)
 ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdatetime.h:324:1: error: ‘class QDateTime’ has no member named ‘data_ptr’
 Q_DECLARE_SHARED(QDateTime)
 ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdatetime.h: In function ‘void std::swap(_Tp&, _Tp&) [with _Tp = QDateTime]’:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdatetime.h:324:1: error: ‘class QDateTime’ has no member named ‘data_ptr’
 Q_DECLARE_SHARED(QDateTime)
 ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdatetime.h:324:1: error: ‘class QDateTime’ has no member named ‘data_ptr’
 Q_DECLARE_SHARED(QDateTime)
 ^
In file included from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/QDateTime:1:0,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:34,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdatetime.h: At global scope:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdatetime.h:344:59: error: expected initializer before ‘Q_DECL_NOTHROW’
 Q_CORE_EXPORT uint qHash(const QDate &key, uint seed = 0) Q_DECL_NOTHROW;
                                                           ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdatetime.h:345:59: error: expected initializer before ‘Q_DECL_NOTHROW’
 Q_CORE_EXPORT uint qHash(const QTime &key, uint seed = 0) Q_DECL_NOTHROW;
                                                           ^
In file included from /home/julien/anaconda3/include/boost/smart_ptr/shared_ptr.hpp:28:0,
                 from /home/julien/anaconda3/include/boost/shared_ptr.hpp:17,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:39,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/home/julien/anaconda3/include/boost/smart_ptr/detail/shared_count.hpp:396:33: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     explicit shared_count( std::auto_ptr<Y> & r ): pi_( new sp_counted_impl_p<Y>( r.get() ) )
                                 ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /home/julien/anaconda3/include/boost/config/no_tr1/memory.hpp:21,
                 from /home/julien/anaconda3/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /home/julien/anaconda3/include/boost/shared_ptr.hpp:17,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:39,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from /home/julien/anaconda3/include/boost/shared_ptr.hpp:17:0,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:39,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/home/julien/anaconda3/include/boost/smart_ptr/shared_ptr.hpp:249:65: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
 template< class T, class R > struct sp_enable_if_auto_ptr< std::auto_ptr< T >, R >
                                                                 ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /home/julien/anaconda3/include/boost/config/no_tr1/memory.hpp:21,
                 from /home/julien/anaconda3/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /home/julien/anaconda3/include/boost/shared_ptr.hpp:17,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:39,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from /home/julien/anaconda3/include/boost/shared_ptr.hpp:17:0,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:39,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/home/julien/anaconda3/include/boost/smart_ptr/shared_ptr.hpp:448:31: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     explicit shared_ptr( std::auto_ptr<Y> & r ): px(r.get()), pn()
                               ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /home/julien/anaconda3/include/boost/config/no_tr1/memory.hpp:21,
                 from /home/julien/anaconda3/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /home/julien/anaconda3/include/boost/shared_ptr.hpp:17,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:39,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from /home/julien/anaconda3/include/boost/shared_ptr.hpp:17:0,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:39,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/home/julien/anaconda3/include/boost/smart_ptr/shared_ptr.hpp:461:22: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     shared_ptr( std::auto_ptr<Y> && r ): px(r.get()), pn()
                      ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /home/julien/anaconda3/include/boost/config/no_tr1/memory.hpp:21,
                 from /home/julien/anaconda3/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /home/julien/anaconda3/include/boost/shared_ptr.hpp:17,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:39,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from /home/julien/anaconda3/include/boost/shared_ptr.hpp:17:0,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:39,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/home/julien/anaconda3/include/boost/smart_ptr/shared_ptr.hpp:538:34: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     shared_ptr & operator=( std::auto_ptr<Y> & r )
                                  ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /home/julien/anaconda3/include/boost/config/no_tr1/memory.hpp:21,
                 from /home/julien/anaconda3/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /home/julien/anaconda3/include/boost/shared_ptr.hpp:17,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:39,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from /home/julien/anaconda3/include/boost/shared_ptr.hpp:17:0,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:39,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/home/julien/anaconda3/include/boost/smart_ptr/shared_ptr.hpp:547:34: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     shared_ptr & operator=( std::auto_ptr<Y> && r )
                                  ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /home/julien/anaconda3/include/boost/config/no_tr1/memory.hpp:21,
                 from /home/julien/anaconda3/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /home/julien/anaconda3/include/boost/shared_ptr.hpp:17,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:39,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from /home/julien/anaconda3/include/boost/shared_ptr.hpp:17:0,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:39,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/home/julien/anaconda3/include/boost/smart_ptr/shared_ptr.hpp: In member function ‘boost::shared_ptr<T>& boost::shared_ptr<T>::operator=(std::auto_ptr<_Up>&&)’:
/home/julien/anaconda3/include/boost/smart_ptr/shared_ptr.hpp:549:38: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
         this_type( static_cast< std::auto_ptr<Y> && >( r ) ).swap( *this );
                                      ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /home/julien/anaconda3/include/boost/config/no_tr1/memory.hpp:21,
                 from /home/julien/anaconda3/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /home/julien/anaconda3/include/boost/shared_ptr.hpp:17,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:39,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/QDebug:1:0,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:45,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdebug.h: At global scope:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdebug.h:73:9: error: ‘QMessageLogContext’ does not name a type
         QMessageLogContext context;
         ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdebug.h: In destructor ‘QDebug::~QDebug()’:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdebug.h:86:47: error: ‘struct QDebug::Stream’ has no member named ‘context’
                                       stream->context,
                                               ^
In file included from /home/julien/anaconda3/include/QtCore/qatomic.h:45:0,
                 from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:45,
                 from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qbytearray.h:45,
                 from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/QByteArray:1,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:32,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdebug.h: In function ‘bool qIsDetached(T&) [with T = QDebug]’:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdebug.h:132:1: error: ‘class QDebug’ has no member named ‘isDetached’
 Q_DECLARE_SHARED(QDebug)
 ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdebug.h: In function ‘void qSwap(T&, T&) [with T = QDebug]’:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdebug.h:132:1: error: ‘class QDebug’ has no member named ‘data_ptr’
 Q_DECLARE_SHARED(QDebug)
 ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdebug.h:132:1: error: ‘class QDebug’ has no member named ‘data_ptr’
 Q_DECLARE_SHARED(QDebug)
 ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdebug.h: In function ‘void std::swap(_Tp&, _Tp&) [with _Tp = QDebug]’:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdebug.h:132:1: error: ‘class QDebug’ has no member named ‘data_ptr’
 Q_DECLARE_SHARED(QDebug)
 ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qdebug.h:132:1: error: ‘class QDebug’ has no member named ‘data_ptr’
 Q_DECLARE_SHARED(QDebug)
 ^
In file included from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qbytearray.h:47:0,
                 from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/QByteArray:1,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:32,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qarraydata.h: In instantiation of ‘static QTypedArrayData<T>* QTypedArrayData<T>::sharedNull() [with T = char]’:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qbytearray.h:195:75:   required from here
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qarraydata.h:250:24: error: ‘Q_STATIC_ASSERT’ was not declared in this scope
         Q_STATIC_ASSERT(sizeof(QTypedArrayData) == sizeof(QArrayData));
                        ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qarraydata.h: In instantiation of ‘static void QTypedArrayData<T>::deallocate(QArrayData*) [with T = char]’:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qbytearray.h:409:63:   required from here
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qarraydata.h:229:24: error: ‘Q_STATIC_ASSERT’ was not declared in this scope
         Q_STATIC_ASSERT(sizeof(QTypedArrayData) == sizeof(QArrayData));
                        ^
In file included from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qbytearray.h:45:0,
                 from /home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/QByteArray:1,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireStream/streamdata.hpp:32,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:29:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h: At global scope:
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:65:17: warning: inline function ‘bool QtPrivate::RefCount::deref()’ used but never defined
     inline bool deref() Q_DECL_NOTHROW {
                 ^
/home/julien/anaconda3/pkgs/sire-2018.1.0/bundled/include/QtCore/qrefcount.h:56:17: warning: inline function ‘bool QtPrivate::RefCount::ref()’ used but never defined
     inline bool ref() Q_DECL_NOTHROW {
                 ^
/home/julien/software/devel/sire/corelib/src/libs/SireMove/register_siremove.cpp:32:31: warning: ‘registry’ defined but not used [-Wunused-variable]
 static const RegisterLibrary *registry = new RegisterLibrary( QString("SireMove"), 1, 1 );
                               ^
src/libs/SireMove/CMakeFiles/SireMove.dir/build.make:62: recipe for target 'src/libs/SireMove/CMakeFiles/SireMove.dir/register_siremove.cpp.o' failed
make[2]: *** [src/libs/SireMove/CMakeFiles/SireMove.dir/register_siremove.cpp.o] Error 1
CMakeFiles/Makefile2:1285: recipe for target 'src/libs/SireMove/CMakeFiles/SireMove.dir/all' failed
make[1]: *** [src/libs/SireMove/CMakeFiles/SireMove.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
SOMETHING WENT WRONG WHEN COMPILING CORELIB!

**Comment by chryswoods** [comment]
Could be one of several issues:

Some weirdness from your compiler - which C++ compiler are you using?

Most likely there is some name clash with the compiler finding the wrong Qt or system header files (e.g. limits.h). This breaks the Qt install. We have had to fix these kind of bugs periodically. 

Just to check, do you other Qt libraries installed on your machine. These should not be found by the qmake in Sire, but this may be breaking - https://github.com/econsysqtcam/qtcam/issues/4

Is it just a standard vanilla Ubuntu 16.04. If so, then I will create a docker container and will try to reproduce and then fix the bug.

**Comment by jmichel80** [comment]
hi Chris, 

julien@ubuntu:~/software/devel/sire/build$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.9' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 

I did a dist-upgrade from 14.04 to 16.04 earlier this week. I can't rule out that the upgrade process does not bring the system to a vanilla 16.04 state. 
@ppxasjsm did you upgrade to 16.04 to compile 2018.1 ?

**Comment by lohedges** [comment]
I've had [similar issues](#182) where CMake initially picks up the bundled Qt library but then somehow changes to using the system version during the install process. If I re-run `compile_sire.sh` it magically falls back to using the correct version and the install proceeds correctly. Does re-running the script fix your issue?

I tried to debug the problem, but I could never isolate exactly where the paths were being changed.

**Comment by chryswoods** [comment]
Closing as I believe this is resolved
