### ISSUE TITLE
Custom forcefield terms

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#21]
The softcore custom forcefield terms are really cryptic to me. (No I don't really want to touch them and change them right now.) I was wondering is there a paper/report something that gives detailed information what the terms are that are being passed to OpenMM::CustomNonbondedForce method? I tried Gaetano's thesis but there was nothing more than the usual, this is what a molecular forcefield looks like.

**Comment by jmichel80** [comment]
Not to my knowledge, but this is something we can discuss face to face.

On Sunday, July 19, 2015, ppxasjsm <notifications@github.com> wrote:

> The softcore custom forcefield terms are really cryptic to me. (No I don't
> really want to touch them and change them right now.) I was wondering is
> there a paper/report something that gives detailed information what the
> terms are that are being passed to OpenMM::CustomNonbondedForce method? I
> tried Gaetano's thesis but there was nothing more than the usual, this is
> what a molecular forcefield looks like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/21>.
>


-- 
--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.
