### ISSUE TITLE
Cannot add properties to an unnamed Molecule.

### ISSUE THREAD

**Issue by lohedges** [michellab/Sire#216]
This works:

```python
from Sire.Maths import *
from Sire.Mol import *

na = Molecule("Sodium")
na = na.edit().add( CGName("1") ).add( AtomName("Na") ).molecule().commit()

na = na.edit().atom(AtomIdx(0)) \
              .setProperty("coordinates", Vector(0,0,0)) \
              .molecule() \
              .commit()
```

This doesn't:

```python
from Sire.Maths import *
from Sire.Mol import *

na = Molecule()
na = na.edit().add( CGName("1") ).add( AtomName("Na") ).molecule().commit()

na = na.edit().atom(AtomIdx(0)) \
              .setProperty("coordinates", Vector(0,0,0)) \
              .molecule() \
              .commit()
```

It fails with error:

```bash
python: /home/lester/sire.app/pkgs/sire-2018.2.0/bundled/include/boost/smart_ptr/shared_ptr.hpp:734: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = SireMol::MoleculeData::PropVersions; typename boost::detail::sp_member_access<T>::type = SireMol::MoleculeData::PropVersions*]: Assertion `px != 0' failed.
[1]    28311 abort (core dumped) $HOME/sire.app/bin/python test.py
```

The only difference is that the first molecule was passed a name to its constructor, whereas the second wasn't.

Bizarrely, creating a Molecule with a empty string for a name, i.e. `mol = Molecule("")` works, even though the resulting `MolName` is the same in both cases!

```python
# No argument to constructor.
# Cannot add properties!
mol0 = Molecule()

# Empty string to constructor.
# Can add properties.
mol1 = Molecule("")

mol0.name() == mol1.name()
True
```

This doesn't seem like expected behaviour and off the top of my head I can't think why this would affect the ability to add properties. The same error occurs regardless of whether the properties are set at the atom or molecule level.

Christopher: For reference, I ran across this problem when trying to create merged molecules in BioSimSpace. It took me flipping ages to figure out that this was the issue, rather than some error in my own code! :-)  It appears that this is the same error that you got when attempting to add a "charge0" property in your example IPython session.

**Comment by chryswoods** [comment]
Closing as this is now fixed in the latest devel release (tested in https://github.com/michellab/SireUnitTests/commit/d5f666856042ef8021affeac88b3686d4b9c187c)
