### ISSUE TITLE
openmmacceleratedmdintegrator  v openmmmdintegrator

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#22]
I don't seem to quite understand what the difference between openmmacceleratedmdintegrator.cpp and openmmmdintegrator.cpp are? openmmacceleratedmdintegrator.cpp is not used with the wrapper, or did I not look properly?

**Comment by jmichel80** [comment]
It was an attempt at something new and but the project was canned. You can
remove completely openmmacceleratedmdintegrator.*



On Sunday, July 19, 2015, ppxasjsm <notifications@github.com> wrote:

> I don't seem to quite understand what the difference between
> openmmacceleratedmdintegrator.cpp and openmmmdintegrator.cpp are?
> openmmacceleratedmdintegrator.cpp is not used with the wrapper, or did I
> not look properly?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/22>.
>


-- 
--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.
