### ISSUE TITLE
Devel installation of sire with updated openmm to 7.4 does not run

### ISSUE THREAD

**Issue by JenkeScheen** [michellab/Sire#228]
I installed Sire devel and updated the openmm version to match my cuda compiler version to have the cuda platfrom available with openmm using:
`conda install -c omnia/label/devcuda91 openmm`

When trying to run somd now with no input I get the following error:
```
Starting /home/jscheen/sire.app/bin/somd: number of threads equals 20
Traceback (most recent call last):
  File "/home/jscheen/sire.app/pkgs/sire-2018.2.0/share/Sire/scripts/somd.py", line 12, in <module>
    from Sire.Tools import OpenMMMD
  File "/home/jscheen/sire.app/lib/python3.5/site-packages/Sire/Tools/OpenMMMD.py", line 22, in <module>
    from Sire.IO import *
  File "/home/jscheen/sire.app/lib/python3.5/site-packages/Sire/IO/__init__.py", line 13, in <module>
    from Sire.IO._IO import *
ImportError: /home/jscheen/sire.app/lib/python3.5/site-packages/Sire/IO/../../../../../lib/libSireMove.so.2018: undefined symbol: _ZN6OpenMM7Context12reinitializeEv

```

**Comment by chryswoods** [comment]
Did you update openmm after compiling Sire? If so, you will need to recompile Sire as updating openmm breaks binary compatibility.

**Comment by JenkeScheen** [comment]
upon recompilation of devel Sire:
```
CMakeFiles/SireMove.dir/openmmfrenergyst.cpp.o: In function `SireMove::OpenMMFrEnergyST::createContext(SireMove::IntegratorWorkspace&, SireUnits::Dimension::PhysUnit<0, 0, 1, 0, 0, 0, 0>)':
openmmfrenergyst.cpp:(.text+0x3e56): undefined reference to `OpenMM::Context::reinitialize()'
collect2: error: ld returned 1 exit status
src/libs/SireMove/CMakeFiles/SireMove.dir/build.make:1544: recipe for target 'src/libs/SireMove/libSireMove.so.2018.2.0' failed
make[2]: *** [src/libs/SireMove/libSireMove.so.2018.2.0] Error 1
CMakeFiles/Makefile2:1285: recipe for target 'src/libs/SireMove/CMakeFiles/SireMove.dir/all' failed
make[1]: *** [src/libs/SireMove/CMakeFiles/SireMove.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
SOMETHING WENT WRONG WHEN COMPILING CORELIB!
```

**Comment by chryswoods** [comment]
That is a weird output. Did you recompile from scratch or just run make install again? I am asking as the error shows that CMakeFiles/SireMove.dir/openmmfrenergyst.cpp.o has compiled and found OpenMM::Context::reinitialize() from the header file, but this symbol is not defined in the OpenMM library.

If OpenMM has changed its API then I would expect the compilation of CMakeFiles/SireMove.dir/openmmfrenergyst.cpp.o to fail if CMake is finding the correct header files for OpenMM...

You should rerun "cmake ." in sire/build/corelib and see where it thinks the OpenMM header files and libraries are.

**Comment by chryswoods** [comment]
We have updated the way we detect and optimise CUDA for OpenMM, so closing this now. Please reopen if it is still a problem
