### ISSUE TITLE
for deletion?

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#23]
I would delete the following classes, since they are not used anywhere:
openmmintegrator.h/cpp
openmmacceleratedmdintegrator.h/cpp

What does:
integratorworspacejm.cpp/h do? Should this also be remove/incorporated?

**Comment by jmichel80** [comment]
On 23 Jul 2015 12:01, "ppxasjsm" <notifications@github.com> wrote:
>
> I would delete the following classes, since they are not used anywhere:
> openmmintegrator.h/cpp
> openmmacceleratedmdintegrator.h/cpp
>

Yes ok.

> What does:
> integratorworspacejm.cpp/h do? Should this also be remove/incorporated?
>
It is a modification used to do cell theory. I will merge the code changes
with the standard integrator and update Nautilus.py next month.

> —
> Reply to this email directly or view it on GitHub.

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.
