### ISSUE TITLE
Unable to rename or renumber residues using ResEditor

### ISSUE THREAD

**Issue by lohedges** [michellab/Sire#232]
I need to be able to rename residues to be able to run SOMD simulations with BioSimSpace. This is because SOMD expects all water molecules to have a `Sire.Mol.ResName` of `WAT`.

If I do this...

```python
from Sire.Mol import *

# Here I assume that water is a Sire.Mol.Molecule object.
water = water.edit() \
             .residue(ResIdx(0)) \
             .rename(ResName("WAT")) \
             .molecule() \
             .commit()
```

...then I get the following error...

```bash
Exception 'SireError::incomplete_code' thrown by the thread 'master'.
FILE: /home/lester/Code/Sire/corelib/src/libs/SireMol/reseditor.cpp, LINE: 138
```

i.e. the `rename` method hasn't been implemented for the `Sire.Mol.ResEditor` class. However, if I create a new molecule and add a residue and rename it, things work, e.g.

```
from Sire.Mol import *

# Create a test molecule.
molecule = Molecule("A test molecule")

# Add a single residue and rename it.
res = molecule.edit().add(ResNum(1))
res.rename(ResName("WAT"))
```
At the point of being renamed, the residue above is of type `Sire.Mol.ResStructureEditor`, for which the rename function has been implemented correctly. With this in mind, it is possible to fix the initial code by creating a `ResStructureEditor` object from the `ResEditor`, i.e.

```python
water = ResStructureEditor(water.edit() \
                                .residue(ResIdx(0))\ 
                          ).rename(ResName("WAT")) \
                           .molecule() \
                           .commit()
```

While this is okay for now, it would be nice if it was possible to rename and renumber directly using the `ResEditor` object.

Apologies if I'm missing something, or if there is an easier way to do this.

**Comment by lohedges** [comment]
Actually, that doesn't work as expected since the molecule UID changes so you can't just update an existing system using the renamed molecule. I've managed to hack things for the purposes of BioSimSpace (by effectively creating a new system into which I put the renamed molecules) but it would be nice if this was easier.

**Comment by chryswoods** [comment]
Yup - an incomplete_code exception is a push for us to implement that code. I can show you what we need tomorrow once I am back.

**Comment by lohedges** [comment]
This is now fixed on the `feature-mapping` branch. Will be closed when merged into `devel`.

**Comment by lohedges** [comment]
Although I'm now able to rename residues in a molecule, I still get an error when I update the molecule in the system.

```bash
Exception 'SireError::incompatible_error' thrown by the thread 'master'.
The two passed molecule layouts are incompatible as they have different UIDs! 
```

For example:

```python
from Sire.Mol import *

# 'system' is a Sire.System.System object, from which I extract a molecule.
molecule = system.molecule(MolIdx(0))

# Now rename the first residue in the molecule.
# This now works.
molecule = molecule.edit().residue(ResIdx(0)).rename("WAT").molecule().commit()

**Comment by lohedges** [comment]
As suggested, this has currently been fixed by removing the molecule then re-adding it to the system, e.g.:

```python
from Sire.Mol import *

# 'system' is a Sire.System.System object, from which I extract a molecule.
molecule = system.molecule(MolIdx(0))

# Rename the first residue in the molecule.
molecule = molecule.edit().residue(ResIdx(0)).rename("WAT").molecule().commit()

# Remove the old molecule from the system.
system.remove(molecule.number())

# Add the molecule with the updated residue name back in.
system.add(molecule, MGName("all"))
```

I'll leave the issue open for now and close when there's a permanent fix.

**Comment by lohedges** [comment]
For a system with a large number of molecules that need renaming the above is _painfully_ slow and is unworkable for the purposes of renaming water molecules for SOMD simulations.

For now, I am going to just write the files as is, then use `sed` to convert all `SOL` residues to `WAT`. If anyone knows more about the inner workings of SOMD, then perhaps we could update it to also accept SOL for waters (and other common abbreviations).

**Comment by lohedges** [comment]
Yes, this is a known issue in Sire that I partially fixed last week. I'll have a chat with Christopher when he gets back as I'm sure that it should be possible to greatly speed up the renaming.

That said, I don't see why SOMD and the OpenMM drivers can't be updated to support something like:

```python

waters = ["WAT", "SOL", "HOH", ...]

if molecules.residues()[0].name().value() in waters:
    ...
```

(With similar for the C++)

The release of BioSimSpace that enables free energy perturbation simulations (when it's merged with `master`) is going to require the latest version of Sire/SOMD anyway so I don't see a problem with that. The above doesn't break backwards compatibility, it just allows greater flexibility in the naming of water molecules.

The C++ code also infers the atom types, e.g. hydrogen, by their name, rather than element, which might not always work.

**Comment by lohedges** [comment]
Actually, we're going to have to change a lot as it's not just the residue name that needs to be `WAT`. For example, from one of the C++ files:

```cpp
if ((at0name == AtomName("O") and at1name == AtomName("H1")) or ( at0name == AtomName("H1") and at1name == AtomName("O")))
```

The Gromacs water naming scheme is completely different, i.e. `HW1, HW2, OW`, so the above wouldn't work. This means that whenever I run a SOMD process I would need to do the following:

* Detect all of the water molecules in the system. (BioSimSpace can do this, but it's in pure python and is not the quickest.)
* Rename the water molecule residue to `WAT`.
* Rename the atom names to match the template used in the C++ files used to driver OpenMM, which looks like `H1, H2, and O`.
* Rename any virtual sites to `EPW`.

I actually think it would be easier for me to change `OpenMMMD.py` and the C++ code in `Sire.Move`. Making the residue name checking more flexible is trivial (I have done this already). For the atom names, I just need to check the element property, and if that doesn't exist try using `Element::biologicalElement(name)` passing the first two characters of the atom name. I assume that there are also standard naming conventions for virtual sites, or that they appear as dummy elements.

**Comment by lohedges** [comment]
Actually, this is way more complicated than I thought since there are multiple ways that hydrogen and oxygen atoms are tested for in the C++ files, e.g.:

```c++
if (molecule.atom(AtomIdx(idx)).name().toString()[6] == 'H')
    ...

if (molecule.atom(AtomIdx(idx)).name() == AtonName("H1"))
    ...
```

Ideally, these should all be something like:

```c++

Element elem;

// Try to extract the atom's element property.
try
{
    elem = mol.atom(AtomIdx(idx)).property<Element>("element");
}
// Infer from the atom name instead.
catch (...)
{
    auto name = mol.atom(AtomIdx(idx)).name().value();

    // We'll strip all numeric digits and use a maximum of two characters.
    name.remove(QRegExp("[0-9]")).mid(0, 2);
    elem = Element::biologicalElement(at0name);
}

if (elem == Element("H"))
   ...
```

I updated everything in [openmmmfrenergydt.cpp](https://github.com/michellab/Sire/blob/devel/corelib/src/libs/SireMove/openmmfrenergydt.cpp) but it got too painful in [openmmmfrenergyst.cpp](https://github.com/michellab/Sire/blob/devel/corelib/src/libs/SireMove/openmmfrenergyst.cpp). 

It seems like SOMD is currently broken for any solvated system that wasn't generated from AMBER input files. (I guess the input normally comes from FESetup though, which generates AMBER input.) I don't think it would tell you that anything is wrong, but wouldn't work as expected when restraints are set in the input files.
