### ISSUE TITLE
OpenMM RuntimeError for SOMD with CUDA 9.0

### ISSUE THREAD

**Issue by lohedges** [michellab/Sire#234]
I'm trying to run binding free energy simulations using SOMD on BlueCrystal 4. As I'm using Gromacs (for BioSimSpace solvation support) I require CUDA 9.0, since this is what the Gromacs module is built against:

```bash
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```

I have installed an updated version of OpenMM 7.3 into Sire, which is also built against CUDA 9.0:

```bash
~/sire.app/bin/conda install -c omnia/label/betacuda90 openmm
```

I don't seem to have problems running solvation free energy calculations, but the bound leg of the binding free energy calculation that I'm testing fails with the following error as soon as the free energy stage starts:

```bash
Traceback (most recent call last):
  File "/mnt/storage/home/lh17146/sire.app/pkgs/sire-2018.2.0/share/Sire/scripts/somd-freenrg.py", line 146, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/mnt/storage/home/lh17146/sire.app/lib/python3.5/site-packages/Sire/Tools/__init__.py", line 172, in inner
    retval = func()
  File "/mnt/storage/home/lh17146/sire.app/lib/python3.5/site-packages/Sire/Tools/OpenMMMD.py", line 1619, in runFreeNrg
    system = integrator.minimiseEnergy(system, minimise_tol.val, minimise_max_iter.val)
RuntimeError: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x12e16290_4147.cu(689): warning: variable "torsionParams1" was declared but never referenced
```

A Google search reveals no mention of this issue. Since it's just a warning, I'm not sure if it should trigger the `RuntimeError`. Has anyone come across this before?

**Comment by ppxasjsm** [comment]
I don’t think I have come across this sorry.

**Comment by lohedges** [comment]
Well, if I disable warnings for `nvcc` using `--disable-warnings` the `RuntimeError` isn't triggered. Now I'm running into another error:

```bash
Traceback (most recent call last):
  File "/mnt/storage/home/lh17146/sire.app/pkgs/sire-2018.2.0/share/Sire/scripts/somd-freenrg.py", line 146, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/mnt/storage/home/lh17146/sire.app/lib/python3.5/site-packages/Sire/Tools/__init__.py", line 172, in inner
    retval = func()
  File "/mnt/storage/home/lh17146/sire.app/lib/python3.5/site-packages/Sire/Tools/OpenMMMD.py", line 1619, in runFreeNrg
    system = integrator.minimiseEnergy(system, minimise_tol.val, minimise_max_iter.val)
RuntimeError: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x12e8d8d0_4806.cu(651): Error: Formal parameter space overflowed (4096 bytes max) in function computeBondedForces
```

I wonder if this is because my pert file writer explicitly lists everything, rather than only the terms that change. (I do this for clarity and debugging).

**Comment by lohedges** [comment]
Yes, that was the issue. I need to only write the parameters that change in my pert file. I thought SOMD / OpenMM was smart enough to work out which ones were redundant. Oh well.
