### ISSUE TITLE
AmberPrm parsing error for proteins containing disulphide bridges

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#236]
It seems that Sire cannot read parm7 files written by leap if bonds were added between atoms using the leap 'bond' syntax. This is usually done to setup disulphide bridges between pairs of CYX residues. 

I have attached an example where the protein thrombin has been setup and solvated using two different protocols. In the first protocol cysteines have been converted to CYX residues, but no bond was created between SG atoms of pairs of CYX residues.

solvated-cyx-NOssbond.parm7
solvated-cyx-NOssbond.rst7
 
In the second protocol the bonds have been added. 

solvated-cyx-ssbond.parm7
solvated-cyx-ssbond.rst7

Loading the parm7/rst7 files, hiding the solvent and aligning the proteins in vmd or pymol shows that the protein coordinates are identical. 

mdtraj loads without errors both topologies. 

~/sire.app/bin/python testmdtraj.py 

Sire loads without error only the first topology, and fails on the second topology with the error message:

~/sire.app/bin/python testSire.py

Traceback (most recent call last):
  File "testSire.py", line 12, in <module>
    mols2 = Sire.IO.Amber().readCrdTop(rst2, parm2)
UserWarning: Exception 'SireMol::missing_atom' thrown by the thread 'master'.
There is no atom with the number "4566" in the layout "{8da62164-5674-4777-99f3-246532b0d0ec}".
Thrown from FILE: /home/julien/software/devel/Sire/corelib/src/libs/SireMol/moleculeinfodata.cpp, LINE: 3320, FUNCTION: virtual QList<SireMol::AtomIdx> SireMol::MoleculeInfoData::map(SireMol::AtomNum) const
(..)

Tested using 
Sire version: 2018.2.0 (5a71974f5c83dd06d9dfa75530cf6705bc25db54/Lester Hedges/2018-10-26T10:29:48+01:00 | **UNCLEAN**)

The zip file contains input and scripts to reproduce this error. 
[ssbond.zip](https://github.com/michellab/Sire/files/2608574/ssbond.zip)

**Comment by jmichel80** [comment]
It appears this could be related to #217 and points to a general weakness in the Sire parser.

**Comment by jmichel80** [comment]
@lohedges since there are already a few other issues we have flagged with the amber parser as part of D3R it would be good if you can explore this issue along with the others during the second wave of the free energy library write up.

**Comment by lohedges** [comment]
Thanks, Julien, this will definitely need fixing. Since I didn't write the
Amber parser I'll consult with Christopher when I get back, since he will
probably have a better idea of where the parser logic needs to be tweaked.

**Comment by chryswoods** [comment]
Thanks Julien - just to say I have been working on this. I can now read your SS and nonSS structures, with the exception now coming because I haven't yet worked out how the excluded atoms list should be interpreted for split molecules.

**Comment by chryswoods** [comment]
So nearly there... ;-)

Can now read and write, with excluded atoms interpreted correctly. Energy comparison of original and written fie shows disagreement only in the intramolecular LJ term. Will continue to debug and then compare to sander energies for this molecule...

System( name=LIG, nForceFields=0, nMolecules=11347 nMonitors()=0 ) System( name=, nForceFields=0, nMolecules=11347 nMonitors()=0 )
Calculating energies...
E_{intraclj}^{CLJ}  3623053.68950275  3623069.988637646
E_{intraclj}^{LJ}  3630802.606372118  3630818.90702961
E_{intraclj}^{coulomb}  -7748.916869368094  -7748.918391963848
E_{intraff}^{1-4[LJ]}  0.0  0.0
E_{intraff}^{1-4[coulomb]}  0.0  0.0
E_{intraff}^{1-4}  0.0  0.0
E_{intraff}^{angle}  55583.05524047748  55583.05513252692
E_{intraff}^{bend-bend}  0.0  0.0
E_{intraff}^{bond}  1507109.6633855295  1507109.6293868737
E_{intraff}^{dihedral}  4723.574035544102  4723.573978237031
E_{intraff}^{improper}  0  0
E_{intraff}^{internal}  1567416.2926615512  1567416.2584976377
E_{intraff}^{stretch-bend-torsion}  0.0  0.0
E_{intraff}^{stretch-bend}  0.0  0.0
E_{intraff}^{stretch-stretch}  0.0  0.0
E_{intraff}^{urey_bradley}  0.0  0.0
E_{total}  5190469.982164301  5190486.247135283
E_{intraclj}^{CLJ}
Traceback (most recent call last):
  File "test_ssbonds.py", line 121, in <module>
    test_read_write(True)
  File "test_ssbonds.py", line 105, in test_read_write
    _compare_energies(nrgs, nrgs2)    
  File "test_ssbonds.py", line 62, in _compare_energies
    assert_equal(nrgs1[key], nrgs2[key])
  File "/Users/chris/sire.app/lib/python3.5/unittest/case.py", line 821, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/chris/sire.app/lib/python3.5/unittest/case.py", line 814, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 3623053.68950275 != 3623069.988637646

**Comment by chryswoods** [comment]
Actually, it turned out that the code worked. The differences in energy were because I was saving to AmberRst format, which saved the coordinates with a different level of precision. I don't believe the input file was well equilibrated, as the energies are really huge. Thus the small change in atom coordinates caused the detected changes in energy. This seems strange, but I validated by comparing to energies when saving / loading from AmberRst7, which gave complete agreement (and then I validated by adding more Rst/Rst7 conversions to the cathepsin test molecules just to be sure).

@jmichel80 - could you confirm that the ssbond structures are poorly equilibrated and have bad contacts? Could you also send some equilibrated structures that should give good energies, and ideally the intramolecular energy calculated via Amber?

**Comment by chryswoods** [comment]
Closing issue now as following up in sireparsertest repo
