### ISSUE TITLE
Links in "CONGRATULATIONS" message are not valid

### ISSUE THREAD

**Issue by tomgreen66** [michellab/Sire#237]
The "CONGRATULATIONS" message at the end of the install have links to examples and tutorials that are not valid.  Seems to be:
`http://siremol.org/tutorial` suggest should be `http://siremol.org/pages/tutorials.html`
`http://siremol.org/examples` I couldnt find an equivalent on the webpage.

Was going to submit a pull request but maybe the links should be working and just need the web server to redirect them.

**Comment by chryswoods** [comment]
Thanks for spotting this - it drifted out of date after a website refresh. I will update the routing on the website as the links in the 'Congratulations' message are snappier :-)

**Comment by chryswoods** [comment]
Thanks - I've updated the htaccess file on the website to fix these links. The examples and tutorials are the same, so I've made these both point to the same place. When (if?) anyone gives us some good examples of use, then we will create a real examples page.
