### ISSUE TITLE
SOMD crashes when used in BioSimSpace on OS X

### ISSUE THREAD

**Issue by chryswoods** [michellab/Sire#245]
The merged version of SOMD now crashes when run as part of BioSimSpace on OS X. You can see this in the BioSimSpace azure pipeline (https://dev.azure.com/michellab/BioSimSpace/_build/results?buildId=203). You can also see this if you install Sire by downloading the latest development binary from siremol.org and installing BioSimSpace into that. 

I believe that the issue is not with BioSimSpace, but rather that SOMD now crashes when run using the input files used in the BioSimSpace tests. These provide a more rigorous test of SOMD compared to the tests in Sire.

@ppxasjsm and @SofiaBariami - please could you check that SOMD still works for your inputs and could you verify that you also see errors now when running SOMD via BioSimSpace. If you do, then please could you fix them or else I will need to roll back the changes. Please also add some tests in SireUnitTests that enable you to reproduce the bug identified by BioSimSpace so that we can verify that SOMD is working using only the Sire CI/CD pipeline. Thanks :-)

**Comment by jmichel80** [comment]
Hi Chris,

let's roll back the changes. Having taken a closer look I would like
to see a refactoring of the edits done by @SofiaBariami before this is
merged in devel.

Best wishes,

Julien
--------------------------------------------------------------
Dr. Julien Michel,
Senior Lecturer
Room 263, School of Chemistry
University of Edinburgh
David Brewster road
Edinburgh, EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

On Mon, Feb 25, 2019 at 8:06 PM Christopher Woods
<notifications@github.com> wrote:
>
> The merged version of SOMD now crashes when run as part of BioSimSpace on OS X. You can see this in the BioSimSpace azure pipeline (https://dev.azure.com/michellab/BioSimSpace/_build/results?buildId=203). You can also see this if you install Sire by downloading the latest development binary from siremol.org and installing BioSimSpace into that.
>
> I believe that the issue is not with BioSimSpace, but rather that SOMD now crashes when run using the input files used in the BioSimSpace tests. These provide a more rigorous test of SOMD compared to the tests in Sire.
>
> @ppxasjsm and @SofiaBariami - please could you check that SOMD still works for your inputs and could you verify that you also see errors now when running SOMD via BioSimSpace. If you do, then please could you fix them or else I will need to roll back the changes. Please also add some tests in SireUnitTests that enable you to reproduce the bug identified by BioSimSpace so that we can verify that SOMD is working using only the Sire CI/CD pipeline. Thanks :-)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
The University of Edinburgh is a charitable body, registered in Scotland, with registration number SC005336.

**Comment by lohedges** [comment]
Copied from the BioSimSpace issue [thread](https://github.com/michellab/BioSimSpace/issues/55).

I've now fully merged the changes into my local Sire and recompiled. I'm now seeing the test failure locally too. Having run the failing BioSimSpace test manually in a temporary working directory I get the following back trace. It looks like it's definitely a bug introduced via the the SOMD updates.

```bash
Traceback (most recent call last):
  File "/home/lester/sire.app/pkgs/sire-2018.2.0/share/Sire/scripts/somd.py", line 125, in <module>
    OpenMMMD.run(params)
  File "/home/lester/sire.app/lib/python3.5/site-packages/Sire/Tools/__init__.py", line 176, in inner
    retval = func()
  File "/home/lester/sire.app/lib/python3.5/site-packages/Sire/Tools/OpenMMMD.py", line 1409, in run
    moves = setupMoves(system, ranseed, gpu.val)
  File "/home/lester/sire.app/lib/python3.5/site-packages/Sire/Tools/OpenMMMD.py", line 443, in setupMoves
    Integrator_OpenMM.setCombiningRules(combining_rules.val)
AttributeError: 'OpenMMMDIntegrator' object has no attribute 'setCombiningRules'
```

**Comment by lohedges** [comment]
Having looked into this more, it turns out that the wrappers for Sire.Move weren't regenerated following the updates to SOMD. This can be done by, e.g.

```bash
cd wrappers
$HOME/Sire.app/bin/python AutoGenerate/scanheaders.py $HOME/Code/Sire/corelib/src/libs .
cd Move
$HOME/Sire.app/bin/python ../AutoGenerate/create_wrappers.py
```

After the wrappers are built, re-running `./compile_sire.sh` throws the following error:

```bash
[  1%] Built target sire_python
[  2%] Built target SirePython
[  2%] Built target Error
[  3%] Built target Qt
[  4%] Built target Analysis
[  6%] Built target Cluster
[  7%] Built target ID
[ 13%] Built target Base
[ 17%] Built target FF
[ 24%] Built target CAS
[ 28%] Built target IO
[ 34%] Built target Maths
[ 35%] Built target Stream
Scanning dependencies of target Move
[ 38%] Built target Squire
[ 43%] Built target System
[ 45%] Built target Units
[ 64%] Built target MM
[ 66%] Built target Vol
[ 66%] Building CXX object Move/CMakeFiles/Move.dir/_Move.main.cpp.o
[ 66%] Building CXX object Move/CMakeFiles/Move.dir/OpenMMFrEnergyST.pypp.cpp.o
[ 66%] Building CXX object Move/CMakeFiles/Move.dir/SireMove_properties.cpp.o
[ 91%] Built target Mol
[ 91%] Building CXX object Move/CMakeFiles/Move.dir/SireMove_registrars.cpp.o
/home/lester/Code/Sire/wrapper/Move/SireMove_registrars.cpp:6:10: fatal error: version_error_impl.h: No such file or directory
 #include "version_error_impl.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Move/CMakeFiles/Move.dir/build.make:1116: Move/CMakeFiles/Move.dir/SireMove_registrars.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/lester/Code/Sire/wrapper/Move/OpenMMFrEnergyST.pypp.cpp: In function ‘void register_OpenMMFrEnergyST_class()’:
/home/lester/Code/Sire/wrapper/Move/OpenMMFrEnergyST.pypp.cpp:212:110: error: ‘getCombiningRules’ is not a member of ‘SireMove::OpenMMFrEnergyST’
             getCombiningRules_function_type getCombiningRules_function_value( &::SireMove::OpenMMFrEnergyST::getCombiningRules );
                                                                                                              ^~~~~~~~~~~~~~~~~
/home/lester/Code/Sire/wrapper/Move/OpenMMFrEnergyST.pypp.cpp:643:110: error: ‘setCombiningRules’ is not a member of ‘SireMove::OpenMMFrEnergyST’
             setCombiningRules_function_type setCombiningRules_function_value( &::SireMove::OpenMMFrEnergyST::setCombiningRules );
                                                                                                              ^~~~~~~~~~~~~~~~~
make[2]: *** [Move/CMakeFiles/Move.dir/build.make:726: Move/CMakeFiles/Move.dir/OpenMMFrEnergyST.pypp.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:838: Move/CMakeFiles/Move.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
SOMETHING WENT WRONG WHEN COMPILING WRAPPER!
```

(I'm not sure the reason for the missing header file, `version_error_impl.h`.)

**Comment by SofiaBariami** [comment]
I found a mistake at opennmmfrenergyst.cpp at the combining rules part and I am fixing it right now. I am so sorry for the inconvenience. It is my mistake.

**Comment by lohedges** [comment]
@chryswoods: Any idea why when I get the following change when I re-build the wrappers for `Sire.Move`?

```
@@ -3,128 +3,128 @@

 #include "SireMove_registrars.h"

-#include "Helpers/version_error_impl.h"
+#include "version_error_impl.h"
...
```

This is incorrect, since the file is located at `Helpers/version_error_impl.h` (and appears as this in all of the other `Sire*_registrars.cpp` files. I've always rebuilt the wrappers this way and have never come across this problem before.

(This issue is in addition to the SOMD problems shown above.)

**Comment by lohedges** [comment]
It looks like there is an error in the file `wrappers/AutoGenerate/create_wrappers.py`.

Line [719](https://github.com/michellab/Sire/blob/devel/wrapper/AutoGenerate/create_wrappers.py#L719) reads:

```cpp
print("#include \"version_error_impl.h\"\n", file=FILE)
```

This should be:

```cpp
print("#include \"Helpers/version_error_impl.h\"\n", file=FILE)
```
Not sure how this got through. Once we've rolled back (or fixed) I can add this change and update.

**Comment by lohedges** [comment]
For reference, the above line was introduce [here](https://github.com/michellab/Sire/commit/d71181dadb0c48bf256d84803d3ed25610ce920a#diff-5ab52f2702fe6a86abdd095c9516d1b3).

**Comment by chryswoods** [comment]
Thanks - yes, this looks like the error. I've committed this change.

**Comment by lohedges** [comment]
Closing since changes have been rolled back.
