### ISSUE TITLE
Issue with saving restart

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#248]
This may or may not be fixed already with what you have been working on recently, but I ran a standard MD simulation of a small compound in water for 20 ns and just as it was finishing, saving the restart file threw an error.

The error was:
```bash
Saving restart
Traceback (most recent call last):
  File "/home/ppxasjsm/sire.app/pkgs/sire-2019.1.0/share/Sire/scripts/somd.py", line 125, in <module>
    OpenMMMD.run(params)
  File "/home/ppxasjsm/sire.app/lib/python3.6/site-packages/Sire/Tools/__init__.py", line 176, in inner
    retval = func()
  File "/home/ppxasjsm/sire.app/lib/python3.6/site-packages/Sire/Tools/OpenMMMD.py", line 1485, in run
    Sire.Stream.save([system, moves], restart_file.val)
MemoryError
```

Mostly putting it here as a reminder for me to look into it.

**Comment by ppxasjsm** [comment]
Simulation trajectory file was saved ok.

**Comment by ppxasjsm** [comment]
[prod.txt](https://github.com/michellab/Sire/files/2909213/prod.txt)
[npt_top.txt](https://github.com/michellab/Sire/files/2909215/npt_top.txt)
[npt_crd.txt](https://github.com/michellab/Sire/files/2909216/npt_crd.txt)

And the relevant input files to reproduce. Simulations were run with: 
```bash
 ~/sire.app/bin/somd -C prod.cfg
```

**Comment by jmichel80** [comment]
I think the code changes Sofia has done have broken the restart read

```
/** Extract from a binary datastream */
QDataStream &operator>>(QDataStream &ds, OpenMMFrEnergyST &velver)
{
    VersionID v = readHeader(ds, r_openmmint);

    if (v == 1)
    {
        SharedDataStream sds(ds);
        sds >> velver.frequent_save_velocities >> velver.molgroup
            >> velver.solute >> velver.solutehard >> velver.solutetodummy
            >> velver.solutefromdummy >> velver.combiningRules >> velver.combining_rules 
            >> velver.CutoffType >> velver.cutoff_distance
```

Can you roll back openmmfrenergyst.* to the version prior to her PR. We will have to isolate code changes for the QUBE project until we have a more comprehensive test suite.

**Comment by ppxasjsm** [comment]
I can write a somd test based on this.

**Comment by jmichel80** [comment]
Closing as somd revert should have fixed this
