### ISSUE TITLE
Disabling testing while I debug infinite running tests...

### ISSUE THREAD

**Issue by chryswoods** [michellab/Sire#249]
The latest version of devel times out during running tests because they seem to get stuck in an infinite loop. I tried debugging this using pipelines but to no avail. I have disabled the tests temporarily so that I can build and deploy binaries that I can then download and run on client machines.

Also, I still can't build libcpuid on my MacBook. I get the same error. Disabling tests will let me compare the package built on pipelines against what I have on my MacBook...

**Comment by lohedges** [comment]
We still have the infinite loop issue with the unit tests. For now, I'm running all tests locally before accepting any pull requests.
