### ISSUE TITLE
Docker build failing: returned a non-zero code: 255

### ISSUE THREAD

**Issue by SofiaBariami** [michellab/Sire#252]
Hi everybody! I’m trying to build a new docker container with the new version of Sire and I’m getting this error:
**The command ‘/bin/sh -c ./compile_sire.sh’ returned a non-zero code: 255**
I think it’s a docker issue. I updated it but still getting the same error. Anyone else who had the same problem?

Here is a more detailed description of the error:

```
x86_64-conda_cos6-linux-gnu-g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
gmake[2]: *** [src/libs/SireMol/CMakeFiles/SireMol.dir/parser.cpp.o] Error 4
gmake[2]: *** Deleting file `src/libs/SireMol/CMakeFiles/SireMol.dir/parser.cpp.o’
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [src/libs/SireMol/CMakeFiles/SireMol.dir/all] Error 2
gmake: *** [all] Error 2 ```

**Comment by chryswoods** [comment]
This looks like an out-of-memory error. The `parser.cpp` file is the code that uses boost::spirit to create the parser for Sire's selection code. Compiling this consumes a *lot* of memory, particularly using g++. Check the amount of memory you have allocated to docker. Normally it may be half your system memory, or just 1 GB. Increase this to 4.0 GB and you should be ok (it is 4.0 GB on my MacBook).

**Comment by SofiaBariami** [comment]
It worked fine with 4GB. Thank you @chryswoods!

**Comment by lohedges** [comment]
Closing since issue was resolved.
