### ISSUE TITLE
Broken local Linux build

### ISSUE THREAD

**Issue by lohedges** [michellab/Sire#253]
Having not noticed that the version number had been updated to 2019.1.0 I realise that I hadn't been invoking a full recompile on my local Linux installation. When doing so `./compile_sire.sh` fails nearly immediately with the following error (running on Arch Linux, Kernel 5.0.0, gcc 8.2.1):

```
Where would you like to install Sire? [/home/lester/sire.app]:
Installing into directory '/home/lester/sire.app'
64 bit processor
64 bit operating system
** Unpacking miniconda into /home/lester/sire.app... **
** bash build/miniconda.sh -b -p /home/lester/sire.app **
PREFIX=/home/lester/sire.app
installing: python-3.5.2-0 ...
installing: conda-env-2.6.0-0 ...
installing: openssl-1.0.2j-0 ...
installing: pycosat-0.6.1-py35_1 ...
installing: readline-6.2-2 ...
installing: requests-2.11.1-py35_0 ...
installing: ruamel_yaml-0.11.14-py35_0 ...
installing: sqlite-3.13.0-0 ...
installing: tk-8.5.18-0 ...
installing: xz-5.2.2-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-3 ...
installing: conda-4.2.12-py35_0 ...
installing: pycrypto-2.6.1-py35_4 ...
installing: pip-8.1.2-py35_0 ...
installing: wheel-0.29.0-py35_0 ...
installing: setuptools-27.2.0-py35_0 ...
Python 3.5.2 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
** Running the conda activate script... **
** . "/home/lester/sire.app/bin/activate"
** Running the Python install script... **
** "/home/lester/sire.app/bin/python" build/build_sire.py **
Compiling on Linux
Number of cores used for compilation = 8
Continuing the Sire install using /home/lester/sire.app/bin/python build/build_sire.py
pip is already installed...
Installing packages using '"/home/lester/sire.app/bin/conda" install --yes ipython pytest nose netcdf4 boost gsl tbb tbb-devel pyqt gcc_linux-64 gxx_linux-64 make libtool autoconf automake cmake'
Fetching package metadata .........
Solving package specifications: .


PackageNotFoundError: Package not found: '' Packages missing in current linux-64 channels:
  - tbb
  - tbb-devel
  - gcc_linux-64
  - gxx_linux-64
  - make

Close matches found; did you mean one of these?

    make: cmake, mako
    tbb: tblib

You can search for packages on anaconda.org with

    anaconda search -t conda tbb-devel

(and similarly for the other packages)

You may need to install the anaconda-client command line client with

    conda install anaconda-client


Something went wrong installing dependencies!


CommandNotFoundError: Command Error: error with command 'deactivate'. Command not found: 'deactivate'. 'deactivate' is not a conda command.
 Did you mean "source deactivate" ?
 deactivate 'deactivate' is not a conda command.
 Did you mean "source deactivate" ?
```

**Comment by lohedges** [comment]
Okay, this can be fixed by the following:

```bash
diff --git a/compile_sire.sh b/compile_sire.sh
index dc1592bb..e686c756 100755
--- a/compile_sire.sh
+++ b/compile_sire.sh
@@ -26,7 +26,7 @@ if [ ! -z "$CONDA_PYTHON" ]; then
     echo "** \"$CONDA_PYTHON\" build/build_sire.py **"
     "$CONDA_PYTHON" build/build_sire.py
     err=$?
-    conda deactivate
+    source deactivate
     exit $err
 else
     echo "** FATAL **"
```

```bash
diff --git a/build/build_sire.py b/build/build_sire.py
index 90b00730..712ecbfa 100755
--- a/build/build_sire.py
+++ b/build/build_sire.py
@@ -107,7 +107,7 @@ if __name__ == "__main__":
                   "Are you running this script using the python executable "
                   "from a valid miniconda or anaconda installation?" % conda_base)
             sys.exit(-1)
-        py_module_install = "\"%s\" install --yes" % conda_exe
+        py_module_install = "\"%s\" install -c conda-forge --yes" % conda_exe

     print("Continuing the Sire install using %s %s" \
               % (python_exe, sys.argv[0]))
```

In summary: `deactivate` is not a conda commnad (not sure how to change this in the Windows bat file) and the missing packages are all available from the `conda-forge` channel on Anaconda cloud.

This raises an interesting question about the usefulness of our Azure pipelines CI build. I assume that it must be recompiling Sire starting from the last docker build, so the missing dependencies above were already installed in the existing Sire app. If we forced a full rebuild (starting from a fresh repo) it would break.

**Comment by lohedges** [comment]
Looks like I spoke too soon. Now aborts with the following error:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy
  - python 3.7*
Use "conda info <package>" to see the dependencies for each package.


Cannot find the conda g++ binaries!
```

**Comment by lohedges** [comment]
Right, after cloning a fresh version of the Sire repository and re-running everything it now works with zero changes required to `compile_sire.sh` or `build/build_sire.py`. Apparently trashing my `sire.app` and the build files (as I have always previously done after a version update) no longer works.

Apologies if anyone has wasted any time looking at this!

**Comment by chryswoods** [comment]
Sorry for not noticing this - every version number change requires a complete build from scratch (remove build dirs and sire.app). This is because conda and cmake gets really confused by our pkgs/sire-20XX directory moving and then clashing with paths that cmake store in the build/corelib and build/wrapper directories. There isn’t an easy fix other then adding a test in compile_sire.sh that detects a version change and telling the user to delete all and start from scratch.

**Comment by lohedges** [comment]
No problem. I'm used to the drill when changing version numbers, only completely removing my `~/sire.app` and the `build/corelib` and `build/wrapper` directories didn't work for me this time.

**Comment by lohedges** [comment]
I figured it out. The version of Miniconda had been updated so I also needed to trash the `build/miniconda.sh` script. If this file is present, then the install doesn't download another copy. I'll have to remember this for next time.

**Comment by lohedges** [comment]
While I managed to get a clean install to work on my laptop, it's currently failing on my workstation (which is effectively the same Linux install.) This is after cloning a fresh repository and installing into a new sire.app. After the source finishes compiling, I get the following error:

```
NOW RUNNING "/home/lester/sire.app/bin/cmake" --build . --target install -- -j 4
Scanning dependencies of target sire_python
Scanning dependencies of target SirePython
make[2]: *** No rule to make target '/home/lester/sire.app/bundled/lib/libboost_python.so', needed by 'python/sire_python'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[  0%] Building CXX object python/CMakeFiles/sire_python.dir/main.cpp.o
make[2]: *** No rule to make target '/home/lester/sire.app/bundled/lib/libboost_python.so', needed by 'Helpers/libSirePython.so.2019.1.0'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[  0%] Building CXX object Helpers/CMakeFiles/SirePython.dir/objectregistry.cpp.o
make[1]: *** [CMakeFiles/Makefile2:1168: python/CMakeFiles/sire_python.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:123: Helpers/CMakeFiles/SirePython.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
SOMETHING WENT WRONG WHEN COMPILING WRAPPER!
```

**Comment by lohedges** [comment]
The install works on my laptop, Cibod, and BC4. Only my workstation is failing, which is where I do all of my Sire development! I have made sure I have a completely clean Sire repository, no existing sire.app, and a clean shell environment in which to run ./compile_sire.sh. Totally baffling.

**Comment by lohedges** [comment]
Right, I've now figured out the problem. Depending on the conda install, you may not end up with a file called `libboost_python.so` in `$HOME/sire.app/lib`. On my local machine, the files are:

```bash
ll /home/lester/sire.app/lib/libboost_python*
-rw-rw-r-- 2 lester lester 583K Feb 10 21:27 sire.app/lib/libboost_python37.a
lrwxrwxrwx 1 lester lester   27 Mar  8 11:18 sire.app/lib/libboost_python37.so -> libboost_python37.so.1.69.0
-rwxrwxr-x 2 lester lester 317K Feb 10 21:28 sire.app/lib/libboost_python37.so.1.69.0
```

Wheras on Cibod I have:

```bash
 ll /home/lester/sire.app/lib/libboost_python*
-rw-rw-r--. 2 lester wheel 577386 Jul  5  2018 /home/lester/sire.app/lib/libboost_python37.a
lrwxrwxrwx. 1 lester wheel     27 Mar  8 09:46 /home/lester/sire.app/lib/libboost_python37.so -> libboost_python37.so.1.67.0
-rwxrwxr-x. 2 lester wheel 327560 Jul  5  2018 /home/lester/sire.app/lib/libboost_python37.so.1.67.0
lrwxrwxrwx. 1 lester wheel     19 Mar  8 09:46 /home/lester/sire.app/lib/libboost_python.a -> libboost_python37.a
lrwxrwxrwx. 1 lester wheel     27 Mar  8 09:46 /home/lester/sire.app/lib/libboost_python.so -> libboost_python37.so.1.67.0
```

Creating a symbolic link on my local machine, i.e...

```bash
ln -s ~/sire.app/lib/libboost_python37.so.1.69.0 ~/sire.app/lib/libboost_python.so 
```

...and re-running `./compile_sire.sh` now allows the wrappers to be built.

It's very annoying that the Conda environment isn't consistent between machines, although this is nothing more than we've come to expect. If this is a common problem we could probably create the symbolic link ourselves within the build script.

**Comment by lohedges** [comment]
I've posted an [issue](https://github.com/conda-forge/boost-feedstock/issues/68) on the conda-forge boost feedstock page. Hopefully they'll resolve the issue (or let me know why it differs to the default channel behaviour). This is the only thing currently preventing a clean conda install and packaging.

**Comment by lohedges** [comment]
I've fixed this by updating [install_boost_python.cmake](https://github.com/michellab/Sire/blob/devel/wrapper/bundled/install_boost_python.cmake) so that it finds the Python specific version of `libboost_python` that is installed by conda. See [here](https://github.com/michellab/Sire/commit/9a79b74c1dbf91deb8a3b999d4522d48b6690f7e) for details. This file always exists if the conda boost install was successful, regardless of whether the `libboost_python.{so,dylib}` symlink exists.
