### ISSUE TITLE
Parameterizing in Sire

### ISSUE THREAD

**Issue by MariaDoh** [michellab/Sire#262]
Dear users and developers,
I have recently started working with Sire in order to do MC calculation to generate an ensemble of conformers of two linked protein domains to cross validate with experimental data.
I was wondering whether it is possible to start from a .pdb file alone and parameterize the system within Sire or if a .top file from another Software (Amber for instance) containing all FF parameters is necessary.
Kind regards and thanks in advance for your time.
Maria Dohmen

**Comment by lohedges** [comment]
Hi Mariah,

You can do this with [BioSimSpace](https://github.com/michellab/BioSimSpace), which is built on top of Sire. BioSimSpace is an interoperable Python framework for biomolecular simulation that provides a simple interface to common packages, such as AMBER and GROMACS. With BioSimSpace you can load a PDB file (assuming correct atom names and all hydrogens) and parameterise it with any AMBER style force field that we supports. For example, see the documentation [here](https://biosimspace.org/api/index_Parameters.html).

We also have an interactive Jupyter notebook server [here](http://notebook.biosimspace.org/tmplogin), where you can play with BIoSimSpace online. Once the server launches, click on the `biosimspace_demo` directory and open `interactive_setup.ipynb` or `molecular_setup.ipynb` to get an example of what can be done.
