### ISSUE TITLE
Error when installing pymbar with conda

### ISSUE THREAD

**Issue by SofiaBariami** [michellab/Sire#263]
I am trying to run **analyse_freenrg** that requires **pymbar**. After I installed it using conda: 
` ~/sire_combRules.app/bin/conda  install -c omnia pymbar` 
I am having the following error: 
`  /home/sofia/sire.app/bin/analyse_freenrg: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory `
I can locate it at /home/sofia/sire.app/pkgs/python-3.7.1-h0371630_7/lib/
However, the problem remains even when I export LD_LIBRARY_PATH to /home/sofia/sire_combRules.app/pkgs/python-3.7.1-h0371630_7/lib/
Also I get the same error even when I am trying to run somd or any other command. 
Anyone had a similar problem?

**Comment by lohedges** [comment]
Hi Sofia,

It's possible that the installation of pymbar has messed up the Python version within the Sire miniconda, although I would be surprised since the only package that pymbar pulls in is itself. (As a test, I tried installing pymbar on my Linux workstation. Using both the default and omnia channels, the only package that is installed is pymbar itself, i.e. there are no changes to libpython.)

Could you post the output of the following bash command:

```bash
ls -l $HOME/sire_combRules.app/lib/libpython*
```

(The `lib` directory with within the `sire.app` is where all of the shared object files should live.)

**Comment by SofiaBariami** [comment]
Hi Lester, 

here's the output: 
```
-rwxrwxr-x 1 sofia sofia 23440382 Mar 27 16:08 /home/sofia/sire_combRules.app/lib/libpython3.6m.a
lrwxrwxrwx 1 sofia sofia       20 Mar 27 16:09 /home/sofia/sire_combRules.app/lib/libpython3.6m.so -> libpython3.6m.so.1.0
lrwxrwxrwx 1 sofia sofia       20 Mar 27 16:09 /home/sofia/sire_combRules.app/lib/libpython3.6m.so.1 -> libpython3.6m.so.1.0
-rwxrwxr-x 1 sofia sofia  3576256 Mar 27 16:08 /home/sofia/sire_combRules.app/lib/libpython3.6m.so.1.0
```

The python version (~/sire_combRules.app/bin/python)  that I am using is Python 3.6.8.

**Comment by lohedges** [comment]
Okay, so it looks like you've somehow ended up with Python3.6 installed in the miniconda, whereas Sire (and it's associated applications) have been compiled against Python3.7. Try running the following to see if it fixes the problem.

```bash
$HOME/sire_combRules.app/bin/conda install python=3.7.1
```

If conda throws any complaints it might tell you which package is requiring Python3.6.

**Comment by SofiaBariami** [comment]
Thanks for the help Lester. I installed python 3.7.1, and also exported LD_LIBRARY_PATH to point at  `/home/sofia/sire_combRules.app/lib/` an now it works :)

**Comment by lohedges** [comment]
Great, glad to hear that it was that simple. I'd be interested to know what messed up your Sire conda environment, so let me know if you come across the same issue again. I'll close for now as the original problem is solved.

**Comment by lohedges** [comment]
Also, you shouldn't need to export LD_LIBRARY_PATH in order for the Sire applications, e.g. SOMD, to find the correct libraries. These are checked at run-time by Sire itself (when sire_python is launched). For example, if you do the following...

```python
from Sire.Base import getLibDir
getLibDir()
```
...you should see the location of the libraries, which in my case is `/home/lester/sire.app/lib`
