### ISSUE TITLE
Attribute error in lj-tailcorrection 

### ISSUE THREAD

**Issue by SofiaBariami** [michellab/Sire#265]
I am running a lj-tailcorrection calculation after a FEP with the following command: 
`~/sire.app/bin/lj-tailcorrection -C ../../input/config.cfg  -l 0.00 -r traj000000001.dcd -s 100 -c ../../input/vacuum.rst7 -m ../../input/MORPH.pert -t ../../input/vacuum.parm7`  for lambda = 0.00 but I am getting an **"AttributeError: 'Cartesian' object has no attribute 'dimensions'"**.
 This is my output:
```
Starting /home/sofia/sire.app/bin/lj-tailcorrection: number of threads equals 20

Loading configuration information from file ../../input/config.cfg

Running a lj-tailcorrection calculation using files ../../input/vacuum.parm7, ../../input/vacuum.rst7, ../../input/MORPH.pert and traj000000001.dcd.
Namespace(author=False, bulk_rho=None, config='../../input/config.cfg', coordinate_file='../../input/vacuum.rst7', help_config=False, lambda_val='0.00', morph_file='../../input/MORPH.pert', step='100', topology_file='../../input/vacuum.parm7', traj_file='traj000000001.dcd', version=False)
Using parameters:
===============
andersen == True
barostat == False
buffered coordinates frequency == 500
center solute == True
constraint == hbonds
crdfile == ../../input/vacuum.rst7
cutoff type == nocutoff
energy frequency == 100
equilibrate == False
lambda array == (0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0)
lambda_val == 0.0
minimise == False
morphfile == ../../input/MORPH.pert
ncycles == 15
nmoves == 5000
precision == mixed
save coordinates == True
step_frame == 100
timestep == 0.002 ps
topfile == ../../input/vacuum.parm7
trajfile == traj000000001.dcd
===============
### Running LJ tail correction calculation on unknown ###
lambda is 0.0
Create the System...
Selecting dummy groups
Creating force fields... 
Traceback (most recent call last):
  File "/home/sofia/sire.app/share/Sire/scripts/lj-tailcorrection.py", line 156, in <module>
    LJcutoff.runLambda(params)
  File "/home/sofia/sire.app/lib/python3.7/site-packages/Sire/Tools/__init__.py", line 176, in inner
    retval = func()
  File "/home/sofia/sire.app/lib/python3.7/site-packages/Sire/Tools/LJcutoff.py", line 374, in runLambda
    dims = space.dimensions()
AttributeError: 'Cartesian' object has no attribute 'dimensions'

```
The error occurs when the script needs to determine the longest cutoff that can be used. It should take lowest space dimension  and decrease by 5%, where 
**space = PeriodicBox(Vector( traj_box_x, traj_box_y, traj_box_z ) )** and **traj_box_x,y,z**  are lists of the **cell_lengths** that are defined at a function called updateSystemfromTraj b (see [here](https://github.com/michellab/Sire/blob/devel/wrapper/Tools/LJcutoff.py)).
I am guessing the error has to do with the trajectory input but I'm not sure what to do, as the simulations run fine.

**Comment by jmichel80** [comment]
Hi Sofia, 

Your input files are in vacuum so there is no periodic box associated with the input which breaks lj-tailcorrection that only works for periodic simulations. 

Why are you running this out of curiosity ? This shouldn't be needed for the QUBE work.

**Comment by SofiaBariami** [comment]
Oh right I see. I was discussing with Michail how to find the LJ contribution at the free energy at the specific lambda window and he told me to use that command. I wanted to find the difference between the combining rules as you told me to do.

**Comment by jmichel80** [comment]
I think just finding if the single point energies of the input files differ by roughly the free energy difference between geometric and combining would give a clue about the validity of the implementation.  
Don't worry if you don't see how to do that easily for now, we can discuss next week. It looks like the combining rules are seemingly working, so you can progress by returning to readXml.

**Comment by SofiaBariami** [comment]
Alright! Thank you for the help!
