### ISSUE TITLE
Restrain specific residues of protein

### ISSUE THREAD

**Issue by SofiaBariami** [michellab/Sire#268]
Hi everyone. I am trying to restrain specific residues of a protein but I haven't find anything that could help. The possible choices for the restraint method are: **none, hbonds, allbonds, and hangles**. Is there a way to choose the ones that should be restrained? Thank you!

**Comment by jmichel80** [comment]
These are constraints, which has nothing to do with restraints. 
I've gone through the code and I'm afraid I was mistaken, the exact feature we want is not implemented. The closest we have is the config option 'use_restraints' which executes setupRestraints(system) that will restrain every heavy atom that is not in a water molecule. 

Given that the current implementation of setupRestraints has limited utility I suggest the following new implementation:

* Define the config parameter ''restrained_atoms'' which is None by default, but can give the path to an input file ''positional-restraints.in''

* The format of the file 'positional-restraints.in' is 

```
atomnumber0
atomnumber1
atomnumber2
(...)
```
 
* Modify def setupRestraints(system)

such that the file specified with ''restrained_atoms'' is loaded in memory at the beginning of this subroutine. 

> def setupRestraints(system):
>     restrained_atoms_list = []
>     if restrained_atoms.val is not None:
>         restrained_atoms_list = loadRestraints(restrained_atoms.val)
> 

Inside the inner loop 

>         for x in range(0, nats):

        
add

>             if (not atnumber in restrained_atoms_list):
>                 continue

Then write a separate python script that writes the input file positional-restraints.in for a given prm7 file according to the desired rules. In our case we want to positionally restrain the backbone atoms (N, CA, C, O) of the protein residues that are in residues that are next to a residue that was removed. So you need to find all the atom numbers that correspond to these atoms in the input files crdfile and topfile. A code along the lines of what is written below should do the trick.  

 ```python
 restrained_atoms_list = []
 (molecules, space) = amber.readCrdTop(crdfile.val, topfile.val)
  moleculeNumbers = molecules.molNums()
  for moleculeNumber in moleculeNumbers:
        molecule = molecules.molecule(moleculeNumber)[0].molecule()
        atoms = mol.atoms()
        for x in range(0,len(atoms)):
            at = atoms[x]
            if at.name.value() in ['CA', 'N', 'C', 'O']:
                restrained_atoms_list.append(at.number().value())
 # Now write restrained_atoms_list to a text file...
```
