### ISSUE TITLE
Refactor initialise() -> initialize()

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#27]
Normally I wouldn't create an issue for a retractor, but this requires significant changes, but would make spelling of other variables/function names more consistent.

**Comment by jmichel80** [comment]
Yes spelling should be consistent. 
What is the definition of a retractor?

**Comment by ppxasjsm** [comment]
Yes, spelling...good point! This was an autocorrect error I think and should read refactor (i.e. renaming)...I should check spelling really.

**Comment by ppxasjsm** [comment]
Ok actually the renaming should occur the otherway round all ize -> ise.
