### ISSUE TITLE
QM/MM tutorial not working: related to boost library?

### ISSUE THREAD

**Issue by shuchingou** [michellab/Sire#278]
I used sire installed via conda, followed the QM/MM tutorial and got this error for calculating electrostatic interaction energy between the side-chain and the water molecules:

Traceback (most recent call last):
  File "energy.py", line 71, in <module>
    qmmm_energy = qmmmff.energy()
Boost.Python.ArgumentError: Python argument types in
    QMMMFF.energy(QMMMFF)
did not match C++ signature:
    energy(Squire::QMMMFF {lvalue}, SireFF::EnergyTable {lvalue} energytable, SireCAS::Symbol symbol, double scale_energy=1)
    energy(Squire::QMMMFF {lvalue}, SireFF::EnergyTable {lvalue} energytable, double scale_energy=1)

**Comment by lohedges** [comment]
Hi there.

I think the tutorial must be out of date. Looking at the file [qmmff.h](https://github.com/michellab/Sire/blob/devel/corelib/src/libs/Squire/qmmmff.h) there are only two `energy` method prototypes, none of which take zero arguments.  (The same is true for all classes from which QMMMFF inherits.)

```c++
void energy(EnergyTable &energytable, double scale_energy=1);

void energy(EnergyTable &energytable, const Symbol &symbol,
double scale_energy=1);
```

(The error is indicating that the method call doesn't match either of the C++ signatures.)

I'm not familiar with Squire, or any of Sire's QMMM functionality, so I'll ask @chryswoods about this next week.

**Comment by chryswoods** [comment]
This is an issue with python function overloading. The .energy(energytable) functions have incorrectly hidden the underlying .energy() functions of the G1FF/G2FF base classes.

The tutorial is very old and is just demonstrating how quantomm works. Sorry that bitrot means that it doesn’t work now. One solution to get the energy is to put the forcefield into a System and call energy from there, eg 

‘’’
from Sire.System import System
s = System()
s.add(qmff)
print(s.energy())
‘’’

To run actual qmmm simulations please run quantomm directly.

**Comment by shuchingou** [comment]
Thank you for the assistance!
