### ISSUE TITLE
Numpy in Sire

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#28]
Should we also require numpy or avoid another dependency?

**Comment by jmichel80** [comment]
It is important to distinguish the 'Sire core' library and 'Sire apps'.

My take on this is:

Sire core has no other python module dependencies (besides what's needed to
compile wrappers).

Some Sire apps (compiled together with the default sire build) may have
other dependencies (e.g. mdtraj in Nautilus).
We should aim to depend on those via conda. Sire apps should check for
missing dependencies when invoked from the command line, and if missing,
provide a helpful message for users to instruct how to install the missing
dependency.

Julien




--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

On Wed, Aug 5, 2015 at 11:12 AM, ppxasjsm <notifications@github.com> wrote:

> Should we also require numpy or avoid another dependency?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/28>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
So a dependency on numpy of somd and somd-frenrg would be ok. I will try and fix the pip install bit and maybe also make sure that numpy gets installed.

**Comment by ppxasjsm** [comment]
Dependency added since a lot of things become easier that way.
