### ISSUE TITLE
GroTop parser is very slow to write systems with a large number of molecules

### ISSUE THREAD

**Issue by lohedges** [michellab/Sire#285]
In relation to [this](https://github.com/michellab/BioSimSpace/issues/105) BIoSimSpace issue, the GROMACS topology writer is extremely slow for systems with a large number of molecules. This is due to the cost of looping through the entire system to generate a set of `GroMolType` objects, then looping through these in order to find the unique types.

Due to the flexibility of Sire, molecules in a `System` object are unique and are editable. Ideally, we would like to also be able to implement some kind of molecule registry so that we can avoid duplication of memory when molecules in a system contain the same topology, e.g. waters. In this situation the only property that differs between the molecules is the `coordinates`. For a solvated protein, this would reduce the number of molecule type searches down to two (assuming no ions).

**Comment by lohedges** [comment]
I've updated the `GroTop` writer so that it doesn't create a bunch of unnecessary `GroMolType` objects. This is achieved by extracting the water molecules from the system, then only computing the `GroMolType` of the first water molecule.

In testing, the `GroTop` writer is still slow for large molecules. This is a result of creating the non-bonded terms, which requires an N^2 loop over the atoms in the molecule. When I have time, I'll figure out how to speed this up too.

**Comment by lohedges** [comment]
I am also experiencing the N^2 problem when trying to convert a large GROMACS system to AMBER format. The prm7 file is super quick to write if I delete the `intrascale` property from each of the molecules in the system prior to writing, whereas it has been going for hours otherwise. (This is a system containing 7 molecules, with 17071 atoms total.)

If I delete the `intrascale` property, does the non-bonded matrix get reconstructed from other parameters on write? (Is it needed for write?) If so, it is far quicker to reconstruct the matrix than to convert, so we might want to think about how to optimise things when the molecules in the system are large.

**Comment by lohedges** [comment]
Ah, I've figured this out and the answer is _no_. If I read the converted files back in, while I do have an `intrascale` property it is inconsistent with that of the original system, so we do need to preserve the information via conversion.

**Comment by lohedges** [comment]
We've solved the problem for Amber. However, the `GroTop` parser still uses an (N^2)/2 loop with a `get` on the `intrascale` matrix for each atom pair molecule:

[GroTop.cpp](https://github.com/michellab/Sire/blob/devel/corelib/src/libs/SireIO/grotop.cpp#L3744)
```cpp
// must record every pair that has a non-default scaling factor
for (int i=0; i<scl.nAtoms()-1; ++i)
{
    for (int j=i+1; j<scl.nAtoms(); ++j)
    {
        const auto s = scl.get( AtomIdx(i), AtomIdx(j) );

        if ( not ( (s.coulomb() == 0 and s.lj() == 0) or
                     (s.coulomb() == 1 and s.lj() == 1) ) )
        {
            //this is a non-default pair
            scllines.append( QString("%1 %2     1")
                             .arg(i+1,6).arg(j+1,6) );
         }
    }
}
```

**Comment by chryswoods** [comment]
For this you can change to loop over CutGroup pairs (most of which will be default 0) and then only atom pairs between CutGroups that have non-default values. This should make it roughly order N

**Comment by lohedges** [comment]
Ah, good idea.

Since I can't play around with `scl.get` using `CGIdx` as arguments in Python (it isn't exposed) do you know how I would check that what is returned is default, then how to loop over the atoms in each cut-group retaining their `AtomIdx` in the original molecule (rather than the cut-group). Is there an example of something like this anywhere in the code / unit tests?

**Comment by chryswoods** [comment]
CLJNBPairs is based on SireBase::SparseMatrix

https://github.com/michellab/Sire/blob/bb6382f6cc2ea122b0638e35309e70aafac84132/corelib/src/libs/SireBase/sparsematrix.hpp#L129

The key functions are “get”, “defaultValue” and “isEmpty”.

The SparseMatrix does not have a fixed size and all unset values equal “defaultValue”. If all values are equal to “defaultValue” then “isEmpty” is true.

The SparseMatrix is a template class that is used for the template AtomPairs class. CLJNBPairs is an AtomPairs<CLJScaleFactor>. The AtomPairs class holds a SparseMatrix of CGAtomPairs<CLJScaleFactor>.

https://github.com/michellab/Sire/blob/bb6382f6cc2ea122b0638e35309e70aafac84132/corelib/src/libs/SireMM/atompairs.hpp#L87

You can loop over each CGAtomPairs for each CutGroup pair, and use isEmpty to see if it has any values. If it is not isEmpty, then loop over each atom pair within the CGAtomPairs object to find the values.

**Comment by chryswoods** [comment]
(you can covert the CGIdx plus Index of the atom in the CutGroup into an AtomIdx in the molecule using the MoleculeInfo class, e.g. molinfo.atomIdx( CGAtomIdx(cgidx, idx) )

https://github.com/michellab/Sire/blob/bb6382f6cc2ea122b0638e35309e70aafac84132/corelib/src/libs/SireMol/moleculeinfo.h#L142
