### ISSUE TITLE
how is pip shipped with sire?

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#3]
When I do an install of the github version of sire, I don't seem to have ~/sire.app/bundles/bin/pip available after the install. Since debugging with ipython is a lot easier, I am wondering where the packaging for this happens?

**Comment by jmichel80** [comment]
there is an error in the install scripts for the bundled dependencies of wrappers and pip isn't installed by default.  To fix this

cd /build_bundled/setuptools
~/sire.app/bundled/bin/python3 setup.py install --prefix=/home/$USER/sire.app/bundled/
export PYTHONPATH='/home/$USER/sire.app/bundled/lib/python3.3/site-packages/'
cd ../pip
~/sire.app/bundled/bin/python3 setup.py install --prefix=/home/$USER/sire.app/bundled/

A few useful add ons

~/sire.app/bundled/bin/pip install readline
~/sire.app/bundled/bin/pip install ipython
~/sire.app/bundled/bin/pip install nose

If you want to support mdtraj see the notes here (section ''Dependencies for Nautilus'')

http://www.julienmichel.net/wiki/tiki-index.php?page=Project+Nautilus

**Comment by ppxasjsm** [comment]
Ok, I encountered another problem, to do with zlibimporter.

The error i get looks like this:
```
zipimport.ZipImportError: bad local file header in /home/ppxasjsm/sire.app/bundled/lib/python3.3/site-packages/setuptools-0.9.8-py3.3.egg
```
Initially I thought this might have something to do with the zlib version. So I went from 1.2.8 down to 1.2.3.4 which is installed on ubuntu 12.04. 

After that I still get the same error message. After a bit of googling I found this bug report in setuptools:
https://bitbucket.org/pypa/setuptools/issue/168

This problem is fixed in setuptools version 3.5.2, but the egg included is version 0.9.8, as far as I understand this should be the problem.

**Comment by ppxasjsm** [comment]
Abover zipimporter error fixed by upgrading the setuptool.tar.gz to version 15.0 in bundled.

**Comment by ppxasjsm** [comment]
And because it is fun there is another error. Somehow the python3 setup does not find the ssl library on the system:
```
Python build finished, but the necessary bits to build these modules were not found:
_bz2               _curses            _curses_panel
_dbm               _gdbm              _lzma
_sqlite3           _ssl               _tkinter
```
which means, that pip install will not work. I'll see if I can find a fix around that.

**Comment by jmichel80** [comment]
Seems related to the problems reported in the thread below here. To confirm, you are building on ubuntu 14.04.2 ? 

https://groups.google.com/forum/#!topic/sire-developers/cHeU7ptycCY

and

https://groups.google.com/forum/#!topic/sire-developers/jTSaFIZXp70

**Comment by jmichel80** [comment]
PS: On CentOS 6.5 we fixed it in the past by

yum install zlib-devel
yum install openssl-devel

before compiling wrappers 

So the problem in general is that the way python compiles is quite OS specific. Through previous discussions with Chris  we concluded that we should make sure zlib and ssl are built-in rather than having python link to OS libraries by tweaking the setup scripts.

**Comment by ppxasjsm** [comment]
Zlib not being there was not the problem. If you make sure zlib is installed then the rest of the installation should be fine. In ubuntu it is as as easy as ```sudo apt-get install zlib``` on ubuntu, gets rid of that error. (I actually never had the zlib is not installed error) The main problem was the bug in setuptools, which is now fixed by using a bit more update version of setuptools (15.x) instead of (0.9.x)

So here the problem was an outdated setuptools version, rather than zlib not being there.

**Comment by ppxasjsm** [comment]
With the ssl library it is not clear what the problem is to me. I can manually tweak the setup.py of python3, but that is suboptimal I would say. 
The problem is that python3 setup.py looks in the wrong directories for ssl support at least for my ubuntu 14.04 system:

```        
# Detect SSL support for the socket module (via _ssl)
        search_for_ssl_incs_in = [
                              '/usr/local/ssl/include',
                              '/usr/contrib/ssl/include/'
                             ]
        ssl_incs = find_file('openssl/ssl.h', inc_dirs,
                             search_for_ssl_incs_in
                             )
        if ssl_incs is not None:
            krb5_h = find_file('krb5.h', inc_dirs,
                               ['/usr/kerberos/include'])
            if krb5_h:
                ssl_incs += krb5_h
        ssl_libs = find_library_file(self.compiler, 'ssl',lib_dirs,
                                     ['/usr/local/ssl/lib',
                                      '/usr/contrib/ssl/lib/'
                                     ] )

        if (ssl_incs is not None and
            ssl_libs is not None):
            exts.append( Extension('_ssl', ['_ssl.c'],
                                   include_dirs = ssl_incs,
                                   library_dirs = ssl_libs,
                                   libraries = ['ssl', 'crypto'],
                                   depends = ['socketmodule.h']), )
```

whereas it can be found in ```/usr/lib/ssl```.

**Comment by jmichel80** [comment]
Could that be because the python source are obsolete? Might be worth
checking if a recent version has a correctly working setup.py script. I
agree we should avoid hacking setup.py !

- - -
Julien
Sent from my phone.
On 6 Apr 2015 17:56, "ppxasjsm" <notifications@github.com> wrote:

> With the ssl library it is not clear what the problem is to me. I can
> manually tweak the setup.py of python3, but that is suboptimal I would say.
> The problem is that python3 setup.py looks in the wrong directories for
> ssl support at least for my ubuntu 14.04 system:
>
> # Detect SSL support for the socket module (via _ssl)
>         search_for_ssl_incs_in = [
>                               '/usr/local/ssl/include',
>                               '/usr/contrib/ssl/include/'
>                              ]
>         ssl_incs = find_file('openssl/ssl.h', inc_dirs,
>                              search_for_ssl_incs_in
>                              )
>         if ssl_incs is not None:
>             krb5_h = find_file('krb5.h', inc_dirs,
>                                ['/usr/kerberos/include'])
>             if krb5_h:
>                 ssl_incs += krb5_h
>         ssl_libs = find_library_file(self.compiler, 'ssl',lib_dirs,
>                                      ['/usr/local/ssl/lib',
>                                       '/usr/contrib/ssl/lib/'
>                                      ] )
>
>         if (ssl_incs is not None and
>             ssl_libs is not None):
>             exts.append( Extension('_ssl', ['_ssl.c'],
>                                    include_dirs = ssl_incs,
>                                    library_dirs = ssl_libs,
>                                    libraries = ['ssl', 'crypto'],
>                                    depends = ['socketmodule.h']), )
>
> whereas it can be found in /usr/lib/ssl.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/3#issuecomment-90155162>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
Yep I was thinking about that. I have updated to the last version of pip and setuptools but not python. Then it would be the question of using the latest python 3.3 version of moving to python 3.4. I'll have a look at this today.

**Comment by ppxasjsm** [comment]
BTW, python as is runs fine in principle it just cumbersome to install new things within it. Pip install is causing the actual problem, because ssl isn't installed properly in the python install.

**Comment by jmichel80** [comment]
We should draw the line at providing source files that will compile python across modern flavours of Linux OSs with what is needed to install pip. 
The goal is that the binary install in $HOME/sire.app/ should be portable (so it can be given to users without requiring them to compile).  This should be doable provided 
1) what is needed to install pip is built-in python 
2) the binary is compiled with a libc version that isn't too recent (to avoid version `GLIBC_XX' not found error messages)

For more complex apps that have other dependencies (e.g. Nautilus needs mdtraj/numpy which also pulls in blas/lapack and other things) developers will bundle everything needed to have a portable binary which could be installed separately from sire.app, e.g. $/HOME/nautilus.app/ 

This gives us the flexibility to use other python toolkits with Sire, without avoiding the complexity of trying to maintain one version of sire that supports all dependencies from all possible python packages that could be installed (sounds like a nightmare !!). 

For somd we will have to figure out at some stage how to bundle in openmm.

At the moment this solution puts the burden on the developer and there may be performance hits for the sake of portability, but this seems necessary to me to make the software widely usable. Power-users and would be developers will still have the option to tweak settings and compile everything from source.  

Now maybe we can forget the above if you tell me there is a dead easy simple alternative way to make python portable across OS  !

**Comment by ppxasjsm** [comment]
Well, there is anaconda:
https://store.continuum.io/cshop/anaconda/
many people have switched to using this (I do too). And then there is omina, which is trying to bundle commonly used tools for MD work together including mdtraj, openmm etc. http://www.omnia.md.

**Comment by jmichel80** [comment]
I've heard about anaconda but haven't had a chance to look at it. It sounds like a good way to support numpy etc....! Omnia is interesting too, but we have to make sure we have control on the version of OpenMM that is used in somd as OpenMM code updates may potentially break our code. We also want to keep the option to link to custom versions of OpenMM if that is the most efficient route to support a desired feature. Ideally the binary won't end up being too huge.

**Comment by ppxasjsm** [comment]
Using a certain version can always be forced in setup.py scripts for example. If we only use the API of OpenMM, then in theory minor updates shouldn't break our code, only major version releases, assuming that OpenMM developers adhere to not changing API in minor releases.

**Comment by ppxasjsm** [comment]
Ok I have solved all these problems and the installation works fine on Ubuntu 14.04, once all the needed development libraries for python were installed.
