### ISSUE TITLE
Support longer timesteps

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#30]
By implementing hydrogen mass repartitioning.

**Comment by jmichel80** [comment]
I have completed triplicate runs of a protein-ligand complex. All runs completed without errors. 
HMR + 4fs setup is ca. x1.5 times faster than no HMR + 2 fs setup. 

I plan to test similarity of gradients when multi lambda feature is implemented so I can also compare calculated free energies with BAR

**Comment by ppxasjsm** [comment]
This seems to work fine (eth-methanol). I'll close the issue.
