### ISSUE TITLE
Unable to generate Sire wrappers

### ISSUE THREAD

**Issue by lohedges** [michellab/Sire#300]
It looks like [this](https://github.com/michellab/Sire/commit/c9dd4232c178cc298eb1ca64d2b8cba250b9d611) commit by @ptosco has broken our ability to generate Sire wrappers using the process described [here](https://github.com/michellab/Sire/tree/devel/wrapper). Since this commit touched 156 files, I think I'm going to need some help getting to the bottom of it.

Because the merge didn't change the API it had no effect on the existing wrappers, so everything has continued to build fine afterwards. There also hadn't been any API changes since the commit, meaning that I hadn't spotted the issue until making some optimisations with @chryswoods this morning.

This points to a clear weakness in our current development pipeline: It is no longer good enough to check that the code builds and that the tests pass; we also need to make sure that we can rebuild the wrappers from scratch. Ideally this would be automated in our Azure Pipleline, perhaps by checking that we can regenerate wrappers for one of the smaller sub-packages (perhaps `Sire::IO`) during the build process. If not, it should at least be tested locally before accepting a pull request.

Below is a representative error message after the commit, here trying to build the `Sire::IO` Python wrappers. (Similar errors are thrown building wrappers for any other module.) I'm hoping that this is an easy fix. (We currently can't push any API changing commits until it is resolved.)

```sh
In file included from active_headers.h:6:
In file included from /home/sireuser/Sire/corelib/src/libs/SireIO/amber.h:32:
In file included from /home/sireuser/Sire/corelib/src/libs/SireBase/propertymap.h:36:
In file included from /home/sireuser/Sire/corelib/src/libs/SireBase/property.h:32:
In file included from /home/sireuser/Sire/corelib/src/libs/SireBase/sharedpolypointer.hpp:32:
In file included from /home/sireuser/Sire/corelib/src/libs/SireStream/datastream.h:38:
In file included from /home/sireuser/Sire/corelib/src/libs/SireStream/version_error.h:32:
In file included from /home/sireuser/Sire/corelib/src/libs/SireError/version_error.h:32:
In file included from /home/sireuser/Sire/corelib/src/libs/SireError/exception.h:39:
/home/sireuser/Sire/corelib/src/libs/sireglobal.h:168:5: error: unknown type name 'SIRE_ALWAYS_INLINE'
    SIRE_ALWAYS_INLINE qint64 toInt(const void *ptr)
    ^
/home/sireuser/Sire/corelib/src/libs/sireglobal.h:168:30: error: expected ';' after top level declarator
    SIRE_ALWAYS_INLINE qint64 toInt(const void *ptr)
                             ^
                             ;
/home/sireuser/Sire/corelib/src/libs/sireglobal.h:563:7: error: use of undeclared identifier 'Sire'
using Sire::RegisterMetaType;
      ^
/home/sireuser/Sire/corelib/src/libs/sireglobal.h:564:7: error: use of undeclared identifier 'Sire'
using Sire::MAGIC_ONLY;
      ^
/home/sireuser/Sire/corelib/src/libs/sireglobal.h:565:7: error: use of undeclared identifier 'Sire'
using Sire::NO_STREAM;
      ^
/home/sireuser/Sire/corelib/src/libs/sireglobal.h:566:7: error: use of undeclared identifier 'Sire'
using Sire::NO_ROOT;
      ^
/home/sireuser/Sire/corelib/src/libs/sireglobal.h:567:7: error: use of undeclared identifier 'Sire'
using Sire::MagicID;
      ^
/home/sireuser/Sire/corelib/src/libs/sireglobal.h:568:7: error: use of undeclared identifier 'Sire'
using Sire::getMagic;
      ^
/home/sireuser/Sire/corelib/src/libs/sireglobal.h:569:7: error: use of undeclared identifier 'SireStream'
using SireStream::XMLStream;
      ^
In file included from active_headers.h:6:
In file included from /home/sireuser/Sire/corelib/src/libs/SireIO/amber.h:32:
In file included from /home/sireuser/Sire/corelib/src/libs/SireBase/propertymap.h:36:
In file included from /home/sireuser/Sire/corelib/src/libs/SireBase/property.h:32:
In file included from /home/sireuser/Sire/corelib/src/libs/SireBase/sharedpolypointer.hpp:32:
In file included from /home/sireuser/Sire/corelib/src/libs/SireStream/datastream.h:38:
/home/sireuser/Sire/corelib/src/libs/SireStream/version_error.h:59:25: error: unknown type name 'RegisterMetaTypeBase'
                  const RegisterMetaTypeBase &info,
                        ^
In file included from active_headers.h:6:
In file included from /home/sireuser/Sire/corelib/src/libs/SireIO/amber.h:32:
In file included from /home/sireuser/Sire/corelib/src/libs/SireBase/propertymap.h:36:
In file included from /home/sireuser/Sire/corelib/src/libs/SireBase/property.h:32:
In file included from /home/sireuser/Sire/corelib/src/libs/SireBase/sharedpolypointer.hpp:32:
/home/sireuser/Sire/corelib/src/libs/SireStream/datastream.h:47:67: error: unknown type name 'RegisterMetaTypeBase'
SIRESTREAM_EXPORT QDataStream& writeHeader(QDataStream &ds, const RegisterMetaTypeBase &r_type,
                                                                  ^
/home/sireuser/Sire/corelib/src/libs/SireStream/datastream.h:50:61: error: unknown type name 'MagicID'
SIRESTREAM_EXPORT QDataStream& writeHeader(QDataStream &ds, MagicID magicid, VersionID version);
                                                            ^
/home/sireuser/Sire/corelib/src/libs/SireStream/datastream.h:52:63: error: unknown type name 'RegisterMetaTypeBase'
SIRESTREAM_EXPORT VersionID readHeader(QDataStream &ds, const RegisterMetaTypeBase &r_type);
                                                              ^
/home/sireuser/Sire/corelib/src/libs/SireStream/datastream.h:54:57: error: unknown type name 'MagicID'
SIRESTREAM_EXPORT VersionID readHeader(QDataStream &ds, MagicID magicid, const char *type_name);
                                                        ^
In file included from active_headers.h:6:
In file included from /home/sireuser/Sire/corelib/src/libs/SireIO/amber.h:35:
In file included from /home/sireuser/Sire/corelib/src/libs/SireMol/atomidx.h:34:
In file included from /home/sireuser/Sire/corelib/src/libs/SireMol/atomid.h:225:
/home/sireuser/Sire/corelib/src/libs/SireMol/atomidentifier.h:106:1: error: unknown type name 'SIRE_ALWAYS_INLINE'
SIRE_ALWAYS_INLINE uint qHash(const AtomIdentifier &atomid)
^
/home/sireuser/Sire/corelib/src/libs/SireMol/atomidentifier.h:106:24: error: expected ';' after top level declarator
SIRE_ALWAYS_INLINE uint qHash(const AtomIdentifier &atomid)
                       ^
                       ;
In file included from active_headers.h:6:
In file included from /home/sireuser/Sire/corelib/src/libs/SireIO/amber.h:35:
/home/sireuser/Sire/corelib/src/libs/SireMol/atomidx.h:83:5: error: unknown type name 'uint'
    uint hash() const;
    ^
/home/sireuser/Sire/corelib/src/libs/SireMol/atomidx.h:79:20: error: return type 'SireMol::AtomIdx' is an abstract
      class
    static AtomIdx null();
           ~~~~~~~ ^
/home/sireuser/Sire/corelib/src/libs/SireID/id.h:78:18: note: unimplemented pure virtual method 'hash' in 'AtomIdx'
    virtual uint hash() const=0;
                 ^
In file included from active_headers.h:6:
In file included from /home/sireuser/Sire/corelib/src/libs/SireIO/amber.h:36:
In file included from /home/sireuser/Sire/corelib/src/libs/SireMol/molviewproperty.h:36:
In file included from /home/sireuser/Sire/corelib/src/libs/SireMol/moleculeinfo.h:32:
In file included from /home/sireuser/Sire/corelib/src/libs/SireMol/moleculeinfodata.h:39:
In file included from /home/sireuser/Sire/corelib/src/libs/SireMol/cgatomidx.h:32:
In file included from /home/sireuser/Sire/corelib/src/libs/SireMol/cgidx.h:34:
In file included from /home/sireuser/Sire/corelib/src/libs/SireMol/cgid.h:34:
/home/sireuser/Sire/corelib/src/libs/SireMol/atomsin.hpp:96:5: error: unknown type name 'uint'
    uint hash() const;
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

**Comment by ptosco** [comment]
@lohedges This should be a pretty simple fix. Please let me know how I can test it, i.e., how can I generate wrappers from scratch.

**Comment by lohedges** [comment]
Thanks, @ptosco. I assume that I just need to make `castxml` aware of the `SIRE_ALWAYS_INLINE` so that it can replace it with `inline`, as is done in the [corelib/CMakeLists.txt](https://github.com/michellab/Sire/blob/devel/corelib/CMakeLists.txt) file.

You can generate wrappers by following the procedure described [here](https://github.com/michellab/Sire/tree/devel/wrapper), either by installing the required dependencies yourself, or using our Docker container.

**Comment by ptosco** [comment]
@lohedges could you please try applying this change to `sireglobal.h`:

```
#ifdef QT_NO_TEXTSTREAM
#error Sire requires that Qt was built with QTextStream enabled \
       Please recompile Qt with QTextStream enabled.
#endif

/* add the following lines */
#ifndef SIRE_ALWAYS_INLINE
#ifdef _MSC_VER
#define SIRE_ALWAYS_INLINE __forceinline
#else
#define SIRE_ALWAYS_INLINE inline
#endif
#endif
```

and tell me if that fixes the problem? Thanks.

**Comment by lohedges** [comment]
Thanks @ptosco, I've fixed it an other way. I just needed to update the define symbols in [create_wrappers.py](https://github.com/michellab/Sire/blob/devel/wrapper/AutoGenerate/create_wrappers.py):

```python
define_symbols = ["GCCXML_PARSE", "__PIC__",
                  "SIRE_USE_OPENMM",
                  "SIRE_ALWAYS_INLINE=inline",
                  "SIRE_SKIP_INLINE_FUNCTIONS",
                  "SIREN_SKIP_INLINE_FUNCTIONS",
                  "SIRE_INSTANTIATE_TEMPLATES",
                  "SIREN_INSTANTIATE_TEMPLATES"]
```

**Comment by lohedges** [comment]
Would you ever need to build the wrappers on Windows? If so, your solution is probably more general.

**Comment by ptosco** [comment]
Alternatively in `scanheaders.py` you could change

```
    print("#ifndef ACTIVE_HEADERS_H\n" + \
                 "#define ACTIVE_HEADERS_H\n\n" + \
                 "#ifdef GCCXML_PARSE\n", file=FILE)
```

into

```
    print("""\
#ifndef ACTIVE_HEADERS_H
#define ACTIVE_HEADERS_H
#ifndef SIRE_ALWAYS_INLINE
#ifdef _MSC_VER
#define SIRE_ALWAYS_INLINE __forceinline
#else
#define SIRE_ALWAYS_INLINE inline
#endif
#endif
#ifdef GCCXML_PARSE
""", file=FILE)
```

**Comment by ptosco** [comment]
The above is more general and would also work on Windows.

**Comment by lohedges** [comment]
Great. Just testing now. Thanks for your help.

**Comment by lohedges** [comment]
Hmm, while things seem okay so for most modules, for `Sire::Mol` I see that many existing wrapper files are deleted and some new ones with very bizarre names are created, e.g.:

(Taken from my Git status)

```sh
 M wrapper/Mol/Atom.pypp.cpp
 D wrapper/Mol/AtomBeads.pypp.cpp
 D wrapper/Mol/AtomBeads.pypp.hpp
 D wrapper/Mol/AtomCharges.pypp.cpp
 D wrapper/Mol/AtomCharges.pypp.hpp
 D wrapper/Mol/AtomCoords.pypp.cpp
 D wrapper/Mol/AtomCoords.pypp.hpp
 M wrapper/Mol/AtomEditorBase.pypp.cpp
 D wrapper/Mol/AtomElements.pypp.cpp
 D wrapper/Mol/AtomElements.pypp.hpp
 D wrapper/Mol/AtomEnergies.pypp.cpp
 D wrapper/Mol/AtomEnergies.pypp.hpp
 D wrapper/Mol/AtomFloatProperty.pypp.cpp
 D wrapper/Mol/AtomFloatProperty.pypp.hpp
 D wrapper/Mol/AtomForces.pypp.cpp
 D wrapper/Mol/AtomForces.pypp.hpp
 D wrapper/Mol/AtomIntProperty.pypp.cpp
 D wrapper/Mol/AtomIntProperty.pypp.hpp
 D wrapper/Mol/AtomMasses.pypp.cpp
 D wrapper/Mol/AtomMasses.pypp.hpp
 D wrapper/Mol/AtomPolarisabilities.pypp.cpp
 D wrapper/Mol/AtomPolarisabilities.pypp.hpp
 D wrapper/Mol/AtomRadii.pypp.cpp
 D wrapper/Mol/AtomRadii.pypp.hpp
 D wrapper/Mol/AtomStringProperty.pypp.cpp
 D wrapper/Mol/AtomStringProperty.pypp.hpp
 D wrapper/Mol/AtomVariantProperty.pypp.cpp
 D wrapper/Mol/AtomVariantProperty.pypp.hpp
 D wrapper/Mol/AtomVelocities.pypp.cpp
 D wrapper/Mol/AtomVelocities.pypp.hpp
 D wrapper/Mol/BeadFloatProperty.pypp.cpp
 D wrapper/Mol/BeadFloatProperty.pypp.hpp
 D wrapper/Mol/BeadIntProperty.pypp.cpp
 D wrapper/Mol/BeadIntProperty.pypp.hpp
 D wrapper/Mol/BeadStringProperty.pypp.cpp
 D wrapper/Mol/BeadStringProperty.pypp.hpp
 D wrapper/Mol/BeadVariantProperty.pypp.cpp
 D wrapper/Mol/BeadVariantProperty.pypp.hpp
 D wrapper/Mol/CGFloatProperty.pypp.cpp
 D wrapper/Mol/CGFloatProperty.pypp.hpp
 D wrapper/Mol/CGIntProperty.pypp.cpp
 D wrapper/Mol/CGIntProperty.pypp.hpp
 D wrapper/Mol/CGStringProperty.pypp.cpp
 D wrapper/Mol/CGStringProperty.pypp.hpp
 D wrapper/Mol/CGVariantProperty.pypp.cpp
 D wrapper/Mol/CGVariantProperty.pypp.hpp
 M wrapper/Mol/CMakeAutogenFile.txt
 D wrapper/Mol/ChainFloatProperty.pypp.cpp
 D wrapper/Mol/ChainFloatProperty.pypp.hpp
 D wrapper/Mol/ChainIntProperty.pypp.cpp
 D wrapper/Mol/ChainIntProperty.pypp.hpp
 D wrapper/Mol/ChainStringProperty.pypp.cpp
 D wrapper/Mol/ChainStringProperty.pypp.hpp
 D wrapper/Mol/ChainVariantProperty.pypp.cpp
 D wrapper/Mol/ChainVariantProperty.pypp.hpp
 M wrapper/Mol/ConnectivityBase.pypp.cpp
 D wrapper/Mol/ResFloatProperty.pypp.cpp
 D wrapper/Mol/ResFloatProperty.pypp.hpp
 D wrapper/Mol/ResIntProperty.pypp.cpp
 D wrapper/Mol/ResIntProperty.pypp.hpp
 D wrapper/Mol/ResStringProperty.pypp.cpp
 D wrapper/Mol/ResStringProperty.pypp.hpp
 D wrapper/Mol/ResVariantProperty.pypp.cpp
 D wrapper/Mol/ResVariantProperty.pypp.hpp
 D wrapper/Mol/SegFloatProperty.pypp.cpp
 D wrapper/Mol/SegFloatProperty.pypp.hpp
 D wrapper/Mol/SegIntProperty.pypp.cpp
 D wrapper/Mol/SegIntProperty.pypp.hpp
 D wrapper/Mol/SegStringProperty.pypp.cpp
 D wrapper/Mol/SegStringProperty.pypp.hpp
 D wrapper/Mol/SegVariantProperty.pypp.cpp
 D wrapper/Mol/SegVariantProperty.pypp.hpp
 M wrapper/Mol/SireMol_properties.cpp
 M wrapper/Mol/SireMol_registrars.cpp
 M wrapper/Mol/_Mol.main.cpp
 M wrapper/Mol/active_headers.h
?? wrapper/Mol/AtomProperty_less__QString__greater_.pypp.cpp
?? wrapper/Mol/AtomProperty_less__QString__greater_.pypp.hpp
?? wrapper/Mol/AtomProperty_less__QVariant__greater_.pypp.cpp
?? wrapper/Mol/AtomProperty_less__QVariant__greater_.pypp.hpp
?? wrapper/Mol/AtomProperty_less__SireMaths_scope_Vector3D_less__SireUnits_scope_Dimension_scope_Force__greater___greater_.pypp.cpp
?? wrapper/Mol/AtomProperty_less__SireMaths_scope_Vector3D_less__SireUnits_scope_Dimension_scope_Force__greater___greater_.pypp.hpp
?? wrapper/Mol/AtomProperty_less__SireMaths_scope_Vector3D_less__SireUnits_scope_Dimension_scope_Velocity__greater___greater_.pypp.cpp
?? wrapper/Mol/AtomProperty_less__SireMaths_scope_Vector3D_less__SireUnits_scope_Dimension_scope_Velocity__greater___greater_.pypp.hpp
?? wrapper/Mol/AtomProperty_less__SireMaths_scope_Vector__greater_.pypp.cpp
?? wrapper/Mol/AtomProperty_less__SireMaths_scope_Vector__greater_.pypp.hpp
?? wrapper/Mol/AtomProperty_less__SireMol_scope_BeadNum__greater_.pypp.cpp
?? wrapper/Mol/AtomProperty_less__SireMol_scope_BeadNum__greater_.pypp.hpp
?? wrapper/Mol/AtomProperty_less__SireMol_scope_Element__greater_.pypp.cpp
?? wrapper/Mol/AtomProperty_less__SireMol_scope_Element__greater_.pypp.hpp
?? wrapper/Mol/AtomProperty_less__SireUnits_scope_Dimension_scope_PhysUnit_less__0_comma__0_comma__0_comma__1_comma__0_comma__0_comma__0__greater___greater_.pypp.cpp
?? wrapper/Mol/AtomProperty_less__SireUnits_scope_Dimension_scope_PhysUnit_less__0_comma__0_comma__0_comma__1_comma__0_comma__0_comma__0__greater___greater_.pypp.hpp
?? wrapper/Mol/AtomProperty_less__SireUnits_scope_Dimension_scope_PhysUnit_less__0_comma__1_comma__0_comma__0_comma__0_comma__0_comma__0__greater___greater_.pypp.cpp
?? wrapper/Mol/AtomProperty_less__SireUnits_scope_Dimension_scope_PhysUnit_less__0_comma__1_comma__0_comma__0_comma__0_comma__0_comma__0__greater___greater_.pypp.hpp
?? wrapper/Mol/AtomProperty_less__SireUnits_scope_Dimension_scope_PhysUnit_less__0_comma__3_comma__0_comma__0_comma__0_comma__0_comma__0__greater___greater_.pypp.cpp
?? wrapper/Mol/AtomProperty_less__SireUnits_scope_Dimension_scope_PhysUnit_less__0_comma__3_comma__0_comma__0_comma__0_comma__0_comma__0__greater___greater_.pypp.hpp
?? wrapper/Mol/AtomProperty_less__SireUnits_scope_Dimension_scope_PhysUnit_less__1_comma__0_comma__0_comma__0_comma__0_comma__-1_comma__0__greater___greater_.pypp.cpp
?? wrapper/Mol/AtomProperty_less__SireUnits_scope_Dimension_scope_PhysUnit_less__1_comma__0_comma__0_comma__0_comma__0_comma__-1_comma__0__greater___greater_.pypp.hpp
?? wrapper/Mol/AtomProperty_less__SireUnits_scope_Dimension_scope_PhysUnit_less__1_comma__2_comma__-2_comma__0_comma__0_comma__-1_comma__0__greater___greater_.pypp.cpp
?? wrapper/Mol/AtomProperty_less__SireUnits_scope_Dimension_scope_PhysUnit_less__1_comma__2_comma__-2_comma__0_comma__0_comma__-1_comma__0__greater___greater_.pypp.hpp
?? wrapper/Mol/AtomProperty_less__double__greater_.pypp.cpp
?? wrapper/Mol/AtomProperty_less__double__greater_.pypp.hpp
?? wrapper/Mol/AtomProperty_less__long_long__greater_.pypp.cpp
?? wrapper/Mol/AtomProperty_less__long_long__greater_.pypp.hpp
?? wrapper/Mol/BeadProperty_less__QString__greater_.pypp.cpp
?? wrapper/Mol/BeadProperty_less__QString__greater_.pypp.hpp
?? wrapper/Mol/BeadProperty_less__QVariant__greater_.pypp.cpp
?? wrapper/Mol/BeadProperty_less__QVariant__greater_.pypp.hpp
?? wrapper/Mol/BeadProperty_less__double__greater_.pypp.cpp
?? wrapper/Mol/BeadProperty_less__double__greater_.pypp.hpp
?? wrapper/Mol/BeadProperty_less__long_long__greater_.pypp.cpp
?? wrapper/Mol/BeadProperty_less__long_long__greater_.pypp.hpp
?? wrapper/Mol/CGProperty_less__QString__greater_.pypp.cpp
?? wrapper/Mol/CGProperty_less__QString__greater_.pypp.hpp
?? wrapper/Mol/CGProperty_less__QVariant__greater_.pypp.cpp
?? wrapper/Mol/CGProperty_less__QVariant__greater_.pypp.hpp
?? wrapper/Mol/CGProperty_less__double__greater_.pypp.cpp
?? wrapper/Mol/CGProperty_less__double__greater_.pypp.hpp
?? wrapper/Mol/CGProperty_less__long_long__greater_.pypp.cpp
?? wrapper/Mol/CGProperty_less__long_long__greater_.pypp.hpp
?? wrapper/Mol/ChainProperty_less__QString__greater_.pypp.cpp
?? wrapper/Mol/ChainProperty_less__QString__greater_.pypp.hpp
?? wrapper/Mol/ChainProperty_less__QVariant__greater_.pypp.cpp
?? wrapper/Mol/ChainProperty_less__QVariant__greater_.pypp.hpp
?? wrapper/Mol/ChainProperty_less__double__greater_.pypp.cpp
?? wrapper/Mol/ChainProperty_less__double__greater_.pypp.hpp
?? wrapper/Mol/ChainProperty_less__long_long__greater_.pypp.cpp
?? wrapper/Mol/ChainProperty_less__long_long__greater_.pypp.hpp
?? wrapper/Mol/ResProperty_less__QString__greater_.pypp.cpp
?? wrapper/Mol/ResProperty_less__QString__greater_.pypp.hpp
?? wrapper/Mol/ResProperty_less__QVariant__greater_.pypp.cpp
?? wrapper/Mol/ResProperty_less__QVariant__greater_.pypp.hpp
?? wrapper/Mol/ResProperty_less__double__greater_.pypp.cpp
?? wrapper/Mol/ResProperty_less__double__greater_.pypp.hpp
?? wrapper/Mol/ResProperty_less__long_long__greater_.pypp.cpp
?? wrapper/Mol/ResProperty_less__long_long__greater_.pypp.hpp
?? wrapper/Mol/SegProperty_less__QString__greater_.pypp.cpp
?? wrapper/Mol/SegProperty_less__QString__greater_.pypp.hpp
?? wrapper/Mol/SegProperty_less__QVariant__greater_.pypp.cpp
?? wrapper/Mol/SegProperty_less__QVariant__greater_.pypp.hpp
?? wrapper/Mol/SegProperty_less__double__greater_.pypp.cpp
?? wrapper/Mol/SegProperty_less__double__greater_.pypp.hpp
?? wrapper/Mol/SegProperty_less__long_long__greater_.pypp.cpp
?? wrapper/Mol/SegProperty_less__long_long__greater_.pypp.hpp
```

When trying to compile the wrappers I get errors such as:

```sh
In file included from /home/lester/Code/Sire/wrapper/Mol/_Mol.main.cpp:72:0:
/home/lester/Code/Sire/wrapper/Mol/AtomProperty_less__SireUnits_scope_Dimension_scope_PhysUnit_less__1_comma__0_comma__0_comma__0_comma__0_comma__-1_comma__0__greater___greater_.pypp.hpp:8:126: error: expected initializer before '-' token
 roperty_less__SireUnits_scope_Dimension_scope_PhysUnit_less__1_comma__0_comma__0_comma__0_comma__0_comma__-1_comma__0__greater___greater__class();
```

I'm currently trying to work out whether this is a CastXML issue, or because of changes to the Sire source. (I've not rebuilt the wrappers for `Sire::Mol` for a while, so haven't seen this before!)

Argh!

**Comment by ptosco** [comment]
I'll install dependencies and try to build the wrappers myself so I can try to figure out what the problem is.

**Comment by lohedges** [comment]
I can confirm that it appears to be an issue with CastXML, not the changes introduced in the merge. I've generated wrappers pre- and post-commit and the same problem occurs for `Sire::Mol`. (Bizarrely, this appears to be the only module affected!)

I'm kind of at a loss as to how to proceed. The last time I touched any of the `Sire::Mol` wrappers was on April 29 (see [here](https://github.com/michellab/Sire/tree/devel/wrapper/Mol)) and, at that time, the wrapping process hadn't been containerised. There is no way of me reproducing my exact workstation setup at that point, so I've no idea which specific versions of CastXML, Clang, and LLVM happened to be installed at that time. I guess I'm going to have to try a few (based on dates) and see if I can get anything to work.

**Comment by lohedges** [comment]
Nope, no joy. I've tried all combinations of the above packages through Conda and my Linux distro and still experience the wrapper issue with `Sire::Mol`. Other than building older versions manually I don't know what to suggest.

**Comment by jmichel80** [comment]
Any advice from @chryswoods ? It's pretty crippling if we can't rebuild wrappers.

**Comment by chryswoods** [comment]
First, yes, it would be good to add a wrapper-generation stage to Azure pipelines. We could even find a way to commit these so that the wrappers are generated and updated automatically on every commit (thus solving lots of other problems).

Second, thanks @ptosco and @lohedges for solving the SIRE_ALWAYS_INLINE problem - yes, the correct solution is to add it to the 'define_symbols' list, as @lohedges did. You can see the other symbols I had to add from previous breakages there. We have to remember that the CastXML parser is more brittle than the C++ compiler, so a little massaging of source code is sometimes needed (or, indeed, I completely get the code chopped out by hiding non-declaration code between SIRE_SKIP_INLINE_FUNCTIONS define guards if the code is too complex for CastXML, e.g. as here - https://github.com/michellab/Sire/blob/8df7dd5297e8b746b45ff23c732e3652b49795a8/corelib/src/libs/SireMol/mover.hpp#L170).

The last problem is the "bad template naming" problem. Essentially Py++ struggles to name the wrappers of template classes. It calls the wrapper for ChainProperty<double> `ChainProperty_less__double__greater_.pypp.hpp` (i.e. replaces the less-than and greater-than with `_less_` and `_greater_`). This is ok for most classes, but problems occur for complex template classes (i.e. multiple template arguments), and particularly for the template classes that involve the template metaclass PhysUnit type, e.g. `AtomProperty<Charge>` is `AtomProperty< SireUnits::Dimension::PhysUnit<0,0,0,1,0,0,0> >`. This is turned into the name `AtomProperty_less__SireUnits_scope_Dimension_scope_PhysUnit_less__0_comma__1_comma__0_comma__0_comma__0_comma__0_comma__0__greater___greater_.pypp.cpp`!!!

The compile error occurs because physical units involving negative indices, e.g. `typedef PhysUnit<1,0,0,0,0,-1,0> MolarMass;`, are given file names that have `-` signs in them, e.g. `AtomProperty<MolarMass>` is `AtomProperty< SireUnits::Dimension::PhysUnit<1,0,0,0,0,-1,0> >`, which is named `AtomProperty_less__SireUnits_scope_Dimension_scope_PhysUnit_less__1_comma__0_comma__0_comma__0_comma__0_comma__-1_comma__0__greater___greater_.pypp.hpp`.

The solution I had to come up with was to create an aliasing scheme, whereby template classes could be assigned to an aliased name, and then this was used for naming the file and the class in Python. The aliases are set in the source code using SIRE_EXPOSE_ALIAS, e.g. https://github.com/michellab/Sire/blob/8df7dd5297e8b746b45ff23c732e3652b49795a8/corelib/src/libs/SireMol/moleditor.h#L238

(this says that the class `SireMol::Editor<SireMol::MolEditor, SireMol::Molecule>` should be called `SireMol::MolEditorBase` in the wrappers)

Things are even more complex for the XProperty classes, and so lines like `SIRE_EXPOSE_ATOM_PROPERTY` were created that enabled `scanheaders.py` to add the alias as well as sorting out the other magic needed to make it appear that Python duck-typing was compatible with C++ templates (e.g. `mol.setProperty("property", duck_type_class)` called the right templated function class of `mol`). So, the alias for `AtomProperty<MolarMass>` is set here https://github.com/michellab/Sire/blob/8df7dd5297e8b746b45ff23c732e3652b49795a8/corelib/src/libs/SireMol/atommasses.h#L47

These lines are parsed by `scanheaders.py` to create a set of aliases that are read in by `create_wrappers.py`. This will check if the exposed class has an alias, and if it does, then it sets the alias and ensures that this is used for writing out the file, e.g. as here https://github.com/michellab/Sire/blob/8df7dd5297e8b746b45ff23c732e3652b49795a8/wrapper/AutoGenerate/create_wrappers.py#L438

The problem comes because the format of the classnames reported by CastXML changes with different versions of CastXML. The scheme CastXML (and GCCXML before that) uses to name classes evolves over time, and when it changes, it means that the test `if (classname in aliases)` fails, and so the template class is not aliased, and the horrible (broken) CastXML name is used for that class instead. Horrible and broken names are almost entirely the AtomProperty (and XProperty) names, which are all in SireMol, hence why you see this problem mostly in SireMol (as a general rule, if the wrappers in SireMol generate and compile then you can be happy that everything else will work).

The fix is to work out what CastXML is now calling the classes, and then update the python code in `create_wrappers.py` to find the right class and set the alias. From a quick look, my guess is that CastXML is now fully-resolving the template names, e.g. `AtomProperty<MolarMass>` is being resolved to `AtomProperty< SireUnits::Dimension::PhysUnit<0,0,0,1,0,0,0> >` and so there is no class in the `mb` CastXML interface object callled `AtomProperty<MolarMass>` that can be found, and so no alias is added.

The two possible fixes are to revert to an older version of CastXML, or to add code to `scan headers.py` or `create_wrappers.py` that can resolve the typedef and look for the fully resolved class in `mb`. The second option is more robust, but I suspect quite tricky as you may have to dig into C++ to work out how to fully resolve templates... My suggestion is thus setting up a docker image for wrapper building that pins a sufficiently old version of CastXML that this is not a problem, but that is still new enough that CastXML can cope with the complexity of Sire code...

@lohedges - we can look at this on Friday if you want?

**Comment by ptosco** [comment]
Thanks @chryswoods for the comprehensive explanation.
@lohedges I have managed to build the wrappers with a completely braindead approach, i.e. by just replacing all `-` signs in function and file names with `m`:

```
for i in Analysis Base CAS Cluster Error FF ID IO \
    MM Maths Mol Move Py++ Qt Squire Stream System Units Vol; do
    pushd wrapper/$i
    PATH=$HOME/sire.app/bin:$PATH $HOME/sire.app/bin/python \
        ../AutoGenerate/create_wrappers.py
    for f in `grep -l 'comma__\-' -r .`; do
        sed -i 's|comma__-|comma__m|g' $f
        new_f=`echo $f | sed 's|comma__-|comma__m|g'`
        [ $f != $new_f ] && mv $f $new_f
    done
    popd
done
```

Is it correct that, apart from the bizarre names of the functions, this should make no difference to the end user of the Python wrappers? If that's the case, we may just submit a PR to the CastXML repo to replace `-` with `m` as they already do with `<`, `>` and the like.

**Comment by lohedges** [comment]
@chryswoods, thanks for the clear explanation, it was very helpful. Yes, let's try to go through this on Friday. I'll see if I can find a CastXML version that works, since I have definitely built the SireMol wrappers in the past year without problem.

I'm currently struggling to install older versions within the wrapper Docker container because of incompatible recipes for the older Linux builds of LLVM and Clang on conda-forge. (The macOS build install fine.) I've also tried building a completely different wrapper container based on Ubuntu Bionic (then installing the Sire conda package using Conda) but I keep getting weird fPIC errors when I try to generate the wrappers:

```sh
In file included from active_headers.h:6:
In file included from /home/sireuser/Sire/corelib/src/libs/SireMol/amberparameters.h:32:
In file included from /home/sireuser/Sire/corelib/src/libs/SireBase/propertymap.h:32:
In file included from /home/sireuser/sire.app/bin/../include/qt/QtCore/QHash:1:
In file included from /home/sireuser/sire.app/bin/../include/qt/QtCore/qhash.h:44:
In file included from /home/sireuser/sire.app/bin/../include/qt/QtCore/qchar.h:43:
/home/sireuser/sire.app/bin/../include/qt/QtCore/qglobal.h:1135:4: error: "You must build your code with position independent code if Qt was built with -reduce-relocations. "
      "Compile your code with -fPIC (-fPIE is not enough)."
#  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
```

(I was seeing this when rolling back the CastXML version in the original wrapper Docker container too.)

This problem has occurred but was supposedly fied [here](https://github.com/michellab/Sire/issues/259). Perhaps older compilers (or older versions of CastXML) don't handle the fPIC flag correctly.

@ptosco While your approach would allow the wrappers to compile, I think we need to keep the aliases that Christopher described since those are what what people are currently using within their Python scripts. (@chryswoods, correct me if I'm wrong.) Do the unit tests still pass following your build?

Cheers.

**Comment by chryswoods** [comment]
Yes, @lohedges is right that the aliases are also needed so that the classes have the right name in python. One solution would be to use the same trick and rename them in ‘__init__.py’ at import time (e.g. process the alias info there and say ‘AtomCharges = XXX’).

The only issue is that the length of the ugly file names is so long that this can cause trouble on some file systems or can overflow command buffer when compiling on some OSs.

@lohedges is also right that old CastXMLs don’t have working fPIC. There is a real balance finding a version that is new enough to work but not too new to break things...

**Comment by lohedges** [comment]
Fixed by @chryswoods [here](https://github.com/michellab/Sire/commit/30bfbdbe06aa3f8f125fedd49559db5fdfb647e2). Hurrah!
