### ISSUE TITLE
SOMD not running with top and crd correct

### ISSUE THREAD

**Issue by velocirraptor23** [michellab/Sire#302]
Hi all,
I would like to run a MD production using sire but it seems there is an error to load those files. Not sure what happened but both inputs look OK. Thee were generated with tleap (amber16) in ambertools, minimization ran ok with sander but then it doesnt run with sire for MD production, it seems it cant recognize the files. I tried with other inputs and they run pretty well in other systems. have you ever face an issue like this? It never happened before to me. I have tried everything but nothing works. Im sure that even if something is wrong in the inputs at least It has to run to produce a wrong simulation.

Cesar

**Comment by velocirraptor23** [comment]
Hi All,
I realized my inputs files are having issues with some torsions but I didn't expect sander was going to work even that. WhenI make corrections in the inputs then my simulation ran immediately well. I guess the end of the story.
Cesar

**Comment by chryswoods** [comment]
Great to hear it’s now working :-)
