### ISSUE TITLE
analyse_freenrg mbar of SOMD Free Energy of Binding Tutorial

### ISSUE THREAD

**Issue by rongfengzou** [michellab/Sire#313]
Hi, I went through the tutorial of  SOMD Free Energy of Binding Tutorial.
In the analysis part, I ran the command:
analyse_freenrg mbar --lam -i lam*/simfile.dat --temperature 298 -o out.dat --subsampling --overlap

The output is:Simulation data is analysed using the python module pymbar
----------------------------------------------------------
# Writing all output to file out.dat
#Lambda array was not given, trying to infer lambda values from simulation files...
working on input file lambda_0.0000/simfile.dat
working on input file lambda_0.1250/simfile.dat
working on input file lambda_0.2500/simfile.dat
working on input file lambda_0.3750/simfile.dat
working on input file lambda_0.5000/simfile.dat
working on input file lambda_0.6250/simfile.dat
working on input file lambda_0.7500/simfile.dat
working on input file lambda_0.8750/simfile.dat
working on input file lambda_1.0000/simfile.dat

#Subsampling energies according to statistical inefficiency for pymbar
#Subsampling gradients according to statistical inefficiency
#running mbar ====================================================
K (total states) = 9, total samples = 4059
N_k = 
[451 451 451 451 451 451 451 451 451]
There are 9 states with samples.
Initializing free energies to zero.
Initial dimensionless free energies with method zeros
f_k = 
[0. 0. 0. 0. 0. 0. 0. 0. 0.]
Determining dimensionless free energies by Newton-Raphson / self-consistent iteration.
self consistent iteration gradient norm is      47573, Newton-Raphson gradient norm is     3400.7
Choosing self-consistent iteration on iteration 0
self consistent iteration gradient norm is      35442, Newton-Raphson gradient norm is     2483.5
Choosing self-consistent iteration for lower gradient on iteration 1
self consistent iteration gradient norm is      27977, Newton-Raphson gradient norm is     1809.1
Newton-Raphson used on iteration 2
self consistent iteration gradient norm is     1428.3, Newton-Raphson gradient norm is     55.667
Newton-Raphson used on iteration 3
self consistent iteration gradient norm is     45.229, Newton-Raphson gradient norm is   0.047663
Newton-Raphson used on iteration 4
self consistent iteration gradient norm is   0.038935, Newton-Raphson gradient norm is 2.6076e-08
Newton-Raphson used on iteration 5
self consistent iteration gradient norm is   2.13e-08, Newton-Raphson gradient norm is 7.7099e-21
Newton-Raphson used on iteration 6
self consistent iteration gradient norm is 6.2858e-21, Newton-Raphson gradient norm is  7.421e-25
Newton-Raphson used on iteration 7
self consistent iteration gradient norm is 4.8137e-25, Newton-Raphson gradient norm is 5.2649e-26
Newton-Raphson used on iteration 8
self consistent iteration gradient norm is          0, Newton-Raphson gradient norm is 1.0028e-26
Choosing self-consistent iteration for lower gradient on iteration 9
Converged to tolerance of 3.083359e-15 in 10 iterations.
Of 10 iterations, 7 were Newton-Raphson iterations and 3 were self-consistent iterations
Final dimensionless free energies
f_k = 
[ 0.         -6.1760604  -7.33251323 -6.41616475 -4.8315503  -3.08706393
 -1.65801677 -0.02362955  1.86168383]
MBAR initialization complete.
Traceback (most recent call last):
  File "/home/rongfeng/biosimspace.app/share/Sire/scripts/analyse_freenrg.py", line 621, in <module>
    free_energy_obj.run_mbar(test_overlap)
  File "/home/rongfeng/biosimspace.app/lib/python3.7/site-packages/Sire/Tools/FreeEnergyAnalysis.py", line 85, in run_mbar
    (deltaF_ij, dDeltaF_ij, theta_ij) = MBAR_obj.getFreeEnergyDifferences()
ValueError: not enough values to unpack (expected 3, got 2)

Is there anything wrong with the FreeEnergyAnalysis.py?

Best Regards,
Rongfeng

**Comment by lohedges** [comment]
Hi Rongfeng. This is due to an apparent change in the pymbar API, as reported and fixed in [this](https://github.com/michellab/Sire/issues/309) previous issue. Please use the latest development package for now. Installation details are in the GitHub README.
