### ISSUE TITLE
Bug at LJcutoff.py

### ISSUE THREAD

**Issue by SofiaBariami** [michellab/Sire#316]
Hi, there is a typo at line 235 of [LJcutoff.py](https://github.com/michellab/Sire/blob/devel/wrapper/Tools/LJcutoff.py)

```
if combining_rules.val == 'arithmetic':
    sig_ij = (0.5*(sigma+solv_sigma)).value()
else:
    sig_lj = math.sqrt(sigma.value()*solv_sigma.value())
```

it's sig_ij and not sig_lj. 
Can somebody fix this please? I can also do it. 
Thank you!

**Comment by lohedges** [comment]
I can get this fixed this afternoon.

L

**Comment by lohedges** [comment]
Thanks for reporting, @SofiaBariami. Should be fixed in the latest commit.
