### ISSUE TITLE
Alternating MC and MD moves in a somd simulation

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#321]
Hi @chryswoods , 

I am working on a custom somd code that runs a set of InternalMonteCarlo moves, followed by a set of MD steps with OpenMM. The relevant bits of the code look like this at the moment

```
    PDB().write(system.molecules(),"begin.pdb")
    print (system.energy())
    for i in range(cycle_start, cycle_end):
        print("\nCycle = ", i, flush=True )
        system = moves.move(system, nmoves.val, True)
        PDB().write(system.molecules(),"before.pdb")
        print (system.energy())
        system1 = MCmoves.move(system, nmcmoves.val, True)
        PDB().write(system1.molecules(),"after.pdb")
        print (system1.energy())
```

Where moves is a WeightedMoves object that only runs MD with OpenMM for nmoves, and MCmoves is another WeightedMoves object that only runs MC moves for nmcmoves.  
Execution of the code with a dummy Monte Carlo moves where a single internal degree of freedom is perturbed by 0 degrees generates a pdb file 'after.pdb' that contains the same coordinates as those found in 'begin.pdb', rather than 'before.pdb'. 
In essence, the Monte Carlo move is performed on the coordinates the system had before the MD simulation was performed. 

After trawling through the code I suspect this may be because the Sampler object of the InternalMove object needs to be updated with the system returned by moves.move(...) using Sampler::updateFrom(const System &system). 
However it is not immediately obvious whether there is a simple Python API to do that without digging inside WeightedMoves.
I wonder if this is also revealing an oversight in the OpenMMMDIntegrator code, that updates the system coordinates, but not a sampler correctly. 

I  suspect I could come up with an ugly kludge, but it would be great if you could suggest the best route to fix this bug.

For reference I have attached a script and input that reproduces the behaviour described above (tested on 2020.1)  
[git.zip](https://github.com/michellab/Sire/files/5065834/git.zip)

**Comment by chryswoods** [comment]
Thanks Julien - I'll take a look at this. The error doesn't make sense, which does point to a bug. WeightedMoves will automatically update the sampler, so you don't need to do that yourself. 

The system from moves.move (before.pdb) is given as input to MCmoves.move. So, at the very least, we should get before.pdb out. MCmoves.move has now knowledge of the system that produced begin.pdb, so I am not sure how this bug is operating, but it definitely is a bug.

**Comment by lohedges** [comment]
Hi @jmichel80, are you sure what you write above is correct? I've run your example and the coordinates in `after.pdb` are different to those in `begin.pdb`. Here is the diff:

```sh
diff begin.pdb after.pdb
```

```
1,41c1,41
< ATOM      1   C1 LIG     1      27.620  93.145  24.947  0.00  1.00           C
< ATOM      2   C2 LIG     1      26.281  92.950  25.444  0.00  1.00           C
< ATOM      3   C3 LIG     1      25.753  91.614  25.535  0.00  1.00           C
< ATOM      4   C4 LIG     1      26.560  90.510  25.123  0.00  1.00           C
< ATOM      5   C5 LIG     1      27.882  90.680  24.629  0.00  1.00           C
< ATOM      6   C6 LIG     1      28.428  92.031  24.538  0.00  1.00           C
< ATOM      7   C9 LIG     1      24.347  91.357  26.057  0.00  1.00           C
< ATOM      8  C10 LIG     1      24.348  91.249  27.584  0.00  1.00           C
< ATOM      9  N13 LIG     1      24.273  92.460  28.194  0.00  1.00           N
< ATOM     10  C14 LIG     1      24.243  92.815  29.519  0.00  1.00           C
< ATOM     11  O15 LIG     1      24.410  90.157  28.116  0.00  1.00           O
< ATOM     12  N16 LIG     1      24.692  94.087  29.731  0.00  1.00           N
< ATOM     13  C17 LIG     1      24.722  94.619  31.008  0.00  1.00           C
< ATOM     14  C18 LIG     1      24.291  93.860  32.133  0.00  1.00           C
< ATOM     15  C19 LIG     1      23.818  92.523  31.923  0.00  1.00           C
< ATOM     16  C20 LIG     1      23.797  91.997  30.605  0.00  1.00           C
< ATOM     17  N33 LIG     1      23.388  91.731  32.947  0.00  1.00           N
< ATOM     18  C34 LIG     1      24.332  94.451  33.458  0.00  1.00           C
< ATOM     19  O36 LIG     1      25.187  95.931  31.223  0.00  1.00           O
< ATOM     20  C37 LIG     1      24.503  96.964  30.523  0.00  1.00           C
< ATOM     21  C38 LIG     1      25.286  97.479  29.295  0.00  1.00           C
< ATOM     22   N1 LIG     1      24.359  94.951  34.503  0.00  1.00           N
< ATOM     23   H1 LIG     1      28.022  94.145  24.881  0.00  1.00           H
< ATOM     24   C7 LIG     1      25.475  94.086  25.848  0.00  1.00           C
< ATOM     25   H4 LIG     1      26.152  89.512  25.189  0.00  1.00           H
< ATOM     26   H5 LIG     1      28.471  89.827  24.327  0.00  1.00           H
< ATOM     27   H6 LIG     1      29.430  92.191  24.167  0.00  1.00           H
< ATOM     28  H92 LIG     1      23.698  92.180  25.757  0.00  1.00           H
< ATOM     29  H93 LIG     1      23.969  90.427  25.631  0.00  1.00           H
< ATOM     30  H13 LIG     1      24.232  93.242  27.556  0.00  1.00           H
< ATOM     31  H20 LIG     1      23.448  90.991  30.424  0.00  1.00           H
< ATOM     32 H372 LIG     1      24.340  97.798  31.206  0.00  1.00           H
< ATOM     33 H373 LIG     1      23.536  96.585  30.192  0.00  1.00           H
< ATOM     34 H331 LIG     1      23.394  92.082  33.894  0.00  1.00           H
< ATOM     35 H332 LIG     1      23.063  90.793  32.758  0.00  1.00           H
< ATOM     36 H381 LIG     1      24.714  98.265  28.802  0.00  1.00           H
< ATOM     37 H382 LIG     1      26.247  97.878  29.619  0.00  1.00           H
< ATOM     38 H383 LIG     1      25.450  96.657  28.598  0.00  1.00           H
< ATOM     39  H71 LIG     1      24.502  93.737  26.192  0.00  1.00           H
< ATOM     40  H72 LIG     1      25.977  94.618  26.657  0.00  1.00           H
< ATOM     41  H73 LIG     1      25.342  94.757  25.000  0.00  1.00           H
---
> ATOM      1   C1 LIG     1      27.722  93.088  25.194  0.00  1.00           C
> ATOM      2   C2 LIG     1      26.388  92.892  25.703  0.00  1.00           C
> ATOM      3   C3 LIG     1      25.743  91.620  25.510  0.00  1.00           C
> ATOM      4   C4 LIG     1      26.431  90.581  24.812  0.00  1.00           C
> ATOM      5   C5 LIG     1      27.747  90.754  24.301  0.00  1.00           C
> ATOM      6   C6 LIG     1      28.411  92.040  24.496  0.00  1.00           C
> ATOM      7   C9 LIG     1      24.337  91.363  26.032  0.00  1.00           C
> ATOM      8  C10 LIG     1      24.338  91.255  27.559  0.00  1.00           C
> ATOM      9  N13 LIG     1      24.263  92.466  28.169  0.00  1.00           N
> ATOM     10  C14 LIG     1      24.233  92.821  29.494  0.00  1.00           C
> ATOM     11  O15 LIG     1      24.400  90.163  28.091  0.00  1.00           O
> ATOM     12  N16 LIG     1      24.682  94.093  29.706  0.00  1.00           N
> ATOM     13  C17 LIG     1      24.712  94.625  30.983  0.00  1.00           C
> ATOM     14  C18 LIG     1      24.281  93.866  32.108  0.00  1.00           C
> ATOM     15  C19 LIG     1      23.808  92.529  31.898  0.00  1.00           C
> ATOM     16  C20 LIG     1      23.787  92.003  30.580  0.00  1.00           C
> ATOM     17  N33 LIG     1      23.378  91.737  32.922  0.00  1.00           N
> ATOM     18  C34 LIG     1      24.322  94.457  33.433  0.00  1.00           C
> ATOM     19  O36 LIG     1      25.177  95.937  31.198  0.00  1.00           O
> ATOM     20  C37 LIG     1      24.493  96.970  30.498  0.00  1.00           C
> ATOM     21  C38 LIG     1      25.276  97.485  29.270  0.00  1.00           C
> ATOM     22   N1 LIG     1      24.349  94.957  34.478  0.00  1.00           N
> ATOM     23   H1 LIG     1      28.212  94.040  25.340  0.00  1.00           H
> ATOM     24   C7 LIG     1      25.703  93.963  26.401  0.00  1.00           C
> ATOM     25   H4 LIG     1      25.936  89.633  24.666  0.00  1.00           H
> ATOM     26   H5 LIG     1      28.245  89.951  23.779  0.00  1.00           H
> ATOM     27   H6 LIG     1      29.411  92.200  24.120  0.00  1.00           H
> ATOM     28  H92 LIG     1      23.688  92.186  25.732  0.00  1.00           H
> ATOM     29  H93 LIG     1      23.959  90.433  25.606  0.00  1.00           H
> ATOM     30  H13 LIG     1      24.222  93.248  27.531  0.00  1.00           H
> ATOM     31  H20 LIG     1      23.438  90.997  30.399  0.00  1.00           H
> ATOM     32 H372 LIG     1      24.330  97.804  31.181  0.00  1.00           H
> ATOM     33 H373 LIG     1      23.526  96.591  30.167  0.00  1.00           H
> ATOM     34 H331 LIG     1      23.384  92.088  33.869  0.00  1.00           H
> ATOM     35 H332 LIG     1      23.053  90.799  32.733  0.00  1.00           H
> ATOM     36 H381 LIG     1      24.704  98.271  28.777  0.00  1.00           H
> ATOM     37 H382 LIG     1      26.237  97.884  29.594  0.00  1.00           H
> ATOM     38 H383 LIG     1      25.440  96.663  28.573  0.00  1.00           H
> ATOM     39  H71 LIG     1      24.714  93.623  26.706  0.00  1.00           H
> ATOM     40  H72 LIG     1      26.277  94.247  27.283  0.00  1.00           H
> ATOM     41  H73 LIG     1      25.605  94.823  25.740  0.00  1.00           H
```

(Coordinates also differ between `before.pdb` and `after.pdb`.)

**Comment by lohedges** [comment]
Hmm, since coordiantes differ between `before.pdb` and `after.pdb` perhaps I am not running it correctly.

**Comment by lohedges** [comment]
Okay, I've replaced...

```python
system1 = MCmoves.move(system, nmcmoves.val, True)
```

with

```python
system1 = MCmoves.move(system, 0, True)
```

Now the `before.pdb` and `after.pdb` files are _identical_, since no MC moves have taken place. The coordinates are changed between `begin.pdb` and `before.pdb` following the MD move, as expected.

**Comment by chryswoods** [comment]
I can reproduce the bug by editing input/lig2.flex and setting

```
dihedral C2   C3   C9   C10   flex 0.00
```

I see that begin.pdb and after.pdb are identical, and these are different to before.pdb. Debugging as this doesn't make sense...

**Comment by lohedges** [comment]
Bizarrely, if you make the change you suggest but still leave the number of MC moves set to zero then you still see the behaviour that I describe above, i.e. `before.pdb` and `after.pdb` are identical, whereas the coordinates are changed between `begin.pdb` and `before.pdb`. Setting it back to `ncmoves.val` gives the weird behaviour you see, i.e. `begin.pdb` is the same as `after.pdb`, which doesn't make sense.

Maybe I'm missing something here?

**Comment by chryswoods** [comment]
Ok, I've found the problem. The issue is that the sampler is using a MoleculeGroup that is not part of the System. 

In setupMCMoves the ligand is edited (renamed and flexibility added), and then it is added to a new MoleculeGroup (ligand_grp) which is added to the Sampler of ligand_intra_moves.

Because the ligand was renamed and a new property added, this updated the MoleculeInfo object of the ligand and changed the version number.

The updated ligand WAS NOT added to the System, meaning that the copy of the ligand in the System has a MoleculeInfo that is older than the one in the sampler.

When the MD moves are made, they update the ligand in the System which has the old MoleculeInfo, as they only update the coordinates.

Then, when the MC move is made, we call "update" to update the Sampler, to update the MoleculeGroup in the sampler. However, the copy of the ligand in the Sampler has a newer MoleculeInfo, and so it is not updated. It assumes that, because its MoleculeInfo is newer, then everything about it is newer (including the coordinates, which are, in fact, older). The Sampler returns the "old" ligand to InternalMove, which does nothing, and thus the "old" ligand is returned, overwriting the ligand that was output by the MD moves.

This is not a "bug" exactly, as the code to work out which molecule is newer or older is doing what it should do. The issue is that changes to MoleculeInfo have a higher weight in saying that the molecule is newer than changes in the molecule property.

The fix is to always make sure that the MoleculeGroup used by a Move is part of the System to be moved. We don't enforce that as, in some cases, you may want them to be different (knowing that this falling out of sync may be an issue). In this case, we really do want the ligand group to be part of System. so you need to change setupMCmoves to contain this add and update, e.g.

```
def setupMCmoves(system, random_seed):
    # Now create an Internal MC move that works on the solute only
    ligand = system[MolNum(LIGAND_NUM)][0]
    ligand = ligand.edit().rename(LIGAND_NAME).commit()
    # This will add the property "flexibility" to the solute
    flexibility_lib = FlexibilityLibrary(LIGAND_FLEX_FILE)
    flexibility = flexibility_lib.getFlexibility(ligand)
    ligand = ligand.edit().setProperty("flexibility", flexibility).commit()

    ligand_grp = MoleculeGroup("ligand",ligand)
    ligand_intra_moves = InternalMove( ligand_grp )

    # make sure that the ligand is updated in the System
    system.update(ligand)
    # also make sure that the MoleculeGroup used by the sampler
    # is also in the System
    system.add(ligand_grp)

    ... rest of the function
```

When you make this change the PDBs are as you expect, e.g. after.pdb == before.pdb != begin.pdb

**Comment by chryswoods** [comment]
Oh, and I forgot to say, @lohedges - the reason you see the behaviour you do is because, when the number of moves is 0, Sire will automatically not do anything. This means that when you run 0 moves, it will just return the System that you input. Hence you get back what you put in, and so after.pdb == before.pdb != begin.pdb

**Comment by jmichel80** [comment]
Thanks a lot @chryswoods for the detailed explanation ! I have implemented your changes and the code seems to behave as intended now.
