### ISSUE TITLE
libgfortran version not suitable for Sire when installed use conda

### ISSUE THREAD

**Issue by pengchunwang** [michellab/Sire#322]
Hi all,

I install sire use the following commands:
-> conda create -p /data/xpfep python=3.7
-> conda activate /data/xpfep
-> conda install -c conda-forge -c omnia -c michellab sire

But when import Sire, the following error is printed:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/xpfep/lib/python3.7/site-packages/Sire/__init__.py", line 184, in <module>
    from . import Qt
  File "/data/xpfep/lib/python3.7/site-packages/Sire/Qt/__init__.py", line 19, in <module>
    from Sire.Qt._Qt import *
ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory

when I list the libgfortran in /data/xpfep/lib/, it got the:
/data/xpfep/lib/libgfortran.so
/data/xpfep/lib/libgfortran.so.4
/data/xpfep/lib/libgfortran.so.4.0.0

It seems the default installed libgfortran version not suitable for Sire, Does any body know why?
Thanks~

**Comment by pengchunwang** [comment]
when I try to install libgfortran==3.0.0 using the following command:
-> conda install -c conda-forge libgfortran

when import Sire, another error is printed:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/xpfep/lib/python3.7/site-packages/Sire/__init__.py", line 184, in <module>
    from . import Qt
  File "/data/xpfep/lib/python3.7/site-packages/Sire/Qt/__init__.py", line 19, in <module>
    from Sire.Qt._Qt import *
ImportError: /data/xpfep/lib/python3.7/site-packages/Sire/Qt/../../../../../lib/libcblas.so.3: undefined symbol: cgemv_

**Comment by pengchunwang** [comment]
I have carefully read the install log, and found some Error info in "Verifying transaction" when "conda install -c conda-forge -c omnia -c michellab sire":

Verifying transaction: |
SafetyError: The package for libopenblas located at /data/miniconda3/pkgs/libopenblas-0.3.10-pthreads_hb3c22a3_4
appears to be corrupted. The path 'lib/libopenblasp-r0.3.10.so'
has an incorrect size.
  reported size: 30520712 bytes
  actual size: 10294080 bytes

I tried to clean all, and delete the libopenblas* in pkgs dir, then reinstall, it seems to work fine now.

**Comment by lohedges** [comment]
Thanks for reporting. I'm glad you managed to get things working in the end. Yes, conda doesn't always report errors in the most obvious way and sometimes an install that _appears_ to go fine can leave you with a messed up environment. Good job tracking down the issue in the logs.
