### ISSUE TITLE
sire_python broken on macOS following merge of feature_triclinic branch

### ISSUE THREAD

**Issue by lohedges** [michellab/Sire#326]
Following the merge of the `feature_triclinic` branch the macOS pipeline is failing due to a broken `sire_python` interpreter. After doing a clean build on a MacBook I see the following error when trying to launch `sire_python`:

```sh
libc++abi.dylib: terminating with uncaught exception of type SireMaths::math_error: SireMaths::math_error
[1]    78603 abort      $HOME/sire.app/bin/package_sire
```

No such error is triggered if I launch the regular Python interpreter from the Sire app and import Sire. (Top-level import, or any sub-package.)

After comparing the macOS conda environment to the last successful development build I thought that the issue could be caused by updates to `clang` and `cctools`. Having checked which shared libraries are used by `sire_python` it is apparent that `libc++` is no longer in`@rpath` and instead the system `libc++` is used:

* Last devel binary:

```sh
otool -L ~/sire.app/bin/sire_python | grep libc++
	@rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

* Latest build:

```sh
otool -L ~/sire.app/bin/sire_python | grep libc++
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
```

After downgrading `cctools` using:

```sh
~/sire.app/bin/conda install -c conda-forge cctools=949.0.1=h22b1bf0_0
```

(which also downgrades `clang`) we recover the old behaviour. However, `sire_python` still crashes on launch, so this can't be the source of the problem. (Although this seems like a bug in waiting, right?)

Having rolled back to the commit prior to the merge...

```sh
git checkout 6e7fdebcc7bbefb31a15f3140171918167236693
```

...I can build Sire in the updated conda environment and end up with a working `sire_python`. This implies that something introduced during the merge is causing the issue. However, since `sire_python` works fine on Linux (where all development took place) I'm at a loss as to what's going on. I've checked the source to see where `SireMaths::math_error` is thrown and it doesn't seem to appear in any parts of the codebase that I've modified.

[Here](https://github.com/michellab/Sire/commit/83344261e51e7bb0bd5fb7da7950256b97a2bb7f#diff-ff3a88540acc80e3dea3fa4b0373a709) is a link to the files that have changed during the merge. I've made sure to update all Python wrappers that were modified and the test suite would fail on Linux if this wasn't the case.

Perhaps I'm missing something obvious here: @chryswoods do you have any suggestions? This has been really painful to debug since it's required multiple fresh builds, each of which take around an hour on the macBook.

**Comment by lohedges** [comment]
(I can obviously bisect commits to try and pin down where the breakage first occurred, but thought I'd ask for input before doing so.)

**Comment by lohedges** [comment]
Okay, I've narrowed it down to [this](https://github.com/michellab/Sire/commit/d08e884b87f2b956ec2241221eb658e3b8589736) commit. Fingers crossed it's an error in `charmmpsf.cpp` and not one of the autogenerated wrapper files! (Still no idea why this only breaks `sire_python`, though.)

**Comment by lohedges** [comment]
Fixed it. There was a numerical overflow in the default constructor of `TriclinicBox`, which was triggered in [charmmpsf.cpp](https://github.com/michellab/Sire/blob/devel/corelib/src/libs/SireIO/charmmpsf.cpp). Although I followed the approach used in the `PeriodicBox` class to avoid overflow, the additional algebra used within the constructor of `TriclinicBox` meant that this was no longer valid.

It's strange that this resulted in a breakage to `sire_python`, whereas using the wrappers from within the regular python interpreter caused no issues. I guess undefined things cause undefined issues.

Phew!

**Comment by chryswoods** [comment]
That’s really nasty. I’d say it is a bug worthy of a blog post as I’m intrigued how that even gets triggered by sire_python (which will load the SireMaths and SireIO shared libraries at load time rather than a dlopen as a python module load would do - but this should not call the CharmmPSF constructor...). Excellent bug hunting to track that one down!

**Comment by chryswoods** [comment]
Indeed, the obscureness of this makes me reflect on this morning’s survey that showed C++ plateauing and python use soaring. It would be hard to create this subtle a bug in python...

**Comment by lohedges** [comment]
Yes, I'd love to know the reason why this is triggered. In particular why it's OS (maybe compiler) specific, and only with `sire_python`. At least the numerical overflow didn't cause a break in the space-time continuum, or cause an innocent kitten to be squashed.

**Comment by jmichel80** [comment]
Impressive ! I would probably have thrown myself under a bus trying to work out what is going on.

**Comment by lohedges** [comment]
Don't think that the bus option wasn't considered...

You'll be pleased to know that having fixed the bug the pipeline failed at the conda packaging stage with yet another inexplicable conda error. Will this ever end?

**Comment by lohedges** [comment]
Terrific, another dependency of a dependency changed behind our back. This has broken the Sire 2020.1.0 release of macOS. Another package that I now need to manually pin. I think that we'll eventually end up pinning the _entire_ environment, so the conda package provides no benefit over the binary that we already provide!
