### ISSUE TITLE
AmberPrm uses incorrect NATYP pointer

### ISSUE THREAD

**Issue by lohedges** [michellab/Sire#333]
`NATYP` should be the total number of atom types, not the number of _unique_ types, which is currently used. This means that the `FLAG SOLTY` section has an incorrect number of entries. While this `FLAG` isn't currently used it means that our `prm7` files can't currently be read by tools such as `ParmEd`, which expect the `FLAG` to have the correct number of entries.

**Comment by ppxasjsm** [comment]
I have encountered this exact issue very recently. A fix would be greatly appreciated.

**Comment by lohedges** [comment]
I believe that I've fixed it locally, but currently can't rebuild Sire due
to a conda bug. Hopefully I'll fix both things tomorrow!

**Comment by lohedges** [comment]
This is now fixed. However, if you are the system that you are writing to AMBER format contains water molecules with virtual sites then things still won't work (assuming you have solvated with BioSimSpace). See [here](https://github.com/michellab/BioSimSpace/issues/176) for details. I've solved this by converting to the expected AMBER water topology on write, but haven't pushed the change yet.
