### ISSUE TITLE
broken download link

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#344]
On  https://siremol.org/pages/binaries.html

The link to https://siremol.org/largefiles/sire_releases/download.php?name=sire_2020_1_0_linux.run is broken

Hopefully fixed once the new 2021 release is finalised

**Comment by lohedges** [comment]
Thanks, I've already fixed this locally but was waiting for the 2021.1.0
release before pushing changes. Unfortunately that is taking longer than
expected.

**Comment by lohedges** [comment]
Just a reminder to myself to update this link as soon as possible, ref [here](https://github.com/michellab/Sire/issues/346).
