### ISSUE TITLE
Fix conda installation instructions on siremol.org

### ISSUE THREAD

**Issue by agrossfield** [michellab/Sire#346]
Hi,

I just tried to install sire (we're interested in doing some ligand-binding free energy calculations) via conda, and while conda thinks the build worked, in reality it's broken.

This is on a linux box running Fedora 32.

I created a new environment using:
`conda create sire -c conda-forge -c omnia -c michellab sire`

It downloaded a bunch of stuff, but appeared to exit correctly.

However, when I went to try running a tool, I got:

```
trent 7% conda activate sire
(sire) trent 8% waterswap
waterswap: error while loading shared libraries: libboost_python37.so.1.69.0: cannot open shared object file: No such file or directory
```
I got the same error message with ligandswap. 

I think the mistake is in the dependency specification. Conda installed boost-1.73.0 and boost-cpp-1.73.0, but this looks like it's looking for version 1.69.

The version of sire it installed is sire-2019.1.0-py37hf484d3e_0

Please let me know if you need more information.

Alan

**Comment by agrossfield** [comment]
For what it's worth, I copied and pasted the command from the installation web page (although I changed install to create to make it self-contained) -- see [here](https://siremol.org/pages/download.html), I literally used the very first suggested command, so at the very least the web page needs to be updated.

Next, I tried installing the linux binary, using the link from [here](https://siremol.org/pages/binaries.html). However, the link is broken: (https://siremol.org/largefiles/sire_releases/download.php?name=sire_2020_1_0_linux.run) produces "File not found : sire_2020_1_0_linux.run"

Next, I tried `conda install -c conda-forge -c omnia -c michellab sire --all`. That also grabs the 2019 version of sire, so I stopped it without finishing, so I don't know if it works.

Finally, I tried `conda install -c conda-forge -c omnia -c michellab sire=2021.1.0`. This simply failed with a whole bunch of conflicts, see the attached file [sire_conflicts.txt](https://github.com/michellab/Sire/files/6267476/sire_conflicts.txt)

**Comment by agrossfield** [comment]
The link you gave to the devel binary does work, however.

**Comment by lohedges** [comment]
Apologies, I hadn't realise that the conda installation information at [siremol.org](https://siremol.org/pages/download.html) was so out of date. I don't have direct access to this site (I can make push changes to the code, but need to wait until the website is actually updated as this isn't automatic) so the information often lags the GitHub pages. I'll make sure to update when the 2021.1.0 release is finalised. (I generally only update this information every release.)

I can get the 2021.1.0 release to install via conda on Linux using the following:

```sh
conda create -n sire-test python=3.7
conda activate sire-test
conda install -c conda-forge -c omnia -c michellab sire=2021.1.0
```
(Using `--all` does gives the 2019.3.0 release too.)

The development package (which is also fully tested as part of our CI pipeline) can also be installed via conda. In this case, using either `--all` or `sire=2021.1.0` work for me. The devel binary link always points to the most recent version of the code.

**Comment by agrossfield** [comment]
Got it. I’ll try that tomorrow.

Thanks!

Dr. Alan Grossfield
Department of Biochemistry and Biophysics
University of Rochester Medical School


On Apr 6, 2021, at 5:21 PM, Lester Hedges ***@***.***> wrote:

﻿

Apologies, I hadn't realise that the conda installation information at siremol.org<https://urldefense.proofpoint.com/v2/url?u=https-3A__siremol.org_pages_download.html&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=t5rBcHp9LPuBivSA0LuRqZxl5yZKnAmxoCDYI2YM3f8&s=hNP1TrXfNrYwHb1Rhsg0cLHNbYZ39wwYui1cKPlBlmI&e=> was so out of date. I don't have direct access to this site (I can make push changes to the code, but need to wait until the website is actually updated as this isn't automatic) so the information often lags the GitHub pages. I'll make sure to update when the 2021.1.0 release is finalised. (I generally only update this information every release.)

I can get the 2021.1.0 release to install via conda on Linux using the following:

conda create -n sire-test python=3.7
conda activate sire-test
conda install -c conda-forge -c omnia -c michellab sire=2021.1.0

(Using --all does gives the 2019.3.0 release too.)

The development package (which is also fully tested as part of our CI pipeline) can also be installed via conda. In this case, using either --all or sire=2021.1.0 work for me. The devel binary link always points to the most recent version of the code.

**Comment by lohedges** [comment]
Re-opening until the siremol pull request is actually merged and the page updated. I'll close manually once the changes are live.

**Comment by agrossfield** [comment]
Sounds good. The self-contained distribution passed all self-tests and I can at least run the binaries, so I'm happy. Thanks!
