### ISSUE TITLE
Enhanced sampling methods

### ISSUE THREAD

**Issue by kexul** [michellab/Sire#356]
Dear Sire developers: 
     Is it possible to perform enhanced sampling methods such as _Replica Exchange_ in Sire framework?

**Comment by jmichel80** [comment]
Yes see for example https://siremol.org/tutorials/ligandswap/theory.html

**Comment by chryswoods** [comment]
Yes, there is a RepExMove class that can be used for replica exchange moves. It is used to support replica exchange moves across lambda for RETI, REFEP and REBAR simulations. There is a RepExMove2 class that parallelises the moves via Intel TBB. 

https://github.com/michellab/Sire/blob/devel/corelib/src/libs/SireMove/repexmove2.h

**Comment by kexul** [comment]
Great! Thanks for the detailed information 💯 , I'll try it soon.
