### ISSUE TITLE
possible bug in SOMD

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#368]
At
https://github.com/michellab/Sire/blob/devel/corelib/src/libs/SireMove/openmmfrenergyst.cpp#L612-L623

sigma_avg is defined in the string intra_14_fromdummy_todummy at L604. 
And added again to the string L616-L623.
Thus defined twice. 
I think this means geometric rules would not be correctly applied for non bonded interactions between 'from dummy' and 'to dummy' 1,4 atom pairs. This use case was probably never encountered as we largely run simulations with arithmetic combining rules, and 1,4 interactions between this type of atoms is rare. 

Thanks for spotting this @halx 

I think the bugfix is simple --> remove L612.

**Comment by lohedges** [comment]
Thanks for this. I'm happy to remove the line and push a new commit, which would create a new development conda package. (This seems okay, since the issue doesn't seem too serious.) If needed, I could retag so we rebuild the 2022.1.0 release.
