### ISSUE TITLE
RepExMove2 error 

### ISSUE THREAD

**Issue by shiyx409** [michellab/Sire#381]
Hi. When I was running waterswap & ligandswap, both jobs failed. The endtrace was as shown below, and I was confused about how to switch to RepExMove.

waterswap(+0x4464) [0x55b277491464]
__EndTrace__
Exception 'SireError::incomplete_code' thrown by the thread 'master:main'.
tbb has removed tbb::task, so we now need to rewrite RepExMove2. If this affects you, please switch to RepExMove, and then raise a GitHub issue asking us to conduct a rewrite.
Thrown from FILE: /usr/share/miniconda/envs/sire_build/conda-bld/sire_1648126914782/work/corelib/src/libs/SireMove/repexmove2.cpp, LINE: 567, FUNCTION: void SireMove::RepExMove2::performMove(SireMove::Replicas&, bool)

ligandswap(+0x4464) [0x5585d0e66464]
__EndTrace__
Exception 'SireError::incomplete_code' thrown by the thread 'master:main'.
tbb has removed tbb::task, so we now need to rewrite RepExMove2. If this affects you, please switch to RepExMove, and then raise a GitHub issue asking u
Thrown from FILE: /usr/share/miniconda/envs/sire_build/conda-bld/sire_1648126914782/work/corelib/src/libs/SireMove/repexmove2.cpp, LINE: 567, FUNCTION: &, bool)

**Comment by chryswoods** [comment]
Sorry about that. Threading Building Blocks changed their API, which broke our RepExMove2 class. As it is quite a bit of work to rewrite, and we didn't think the class is much used, we left in this message to see if anyone is still using the code and would benefit from the rewrite.

You can switch to RepExMove by editing `WSRC.py`. This is in the `Sire.Tools` library. Either edit the file in the source (`Sire_source/wrapper/Tools/WSRC.py`) or in the installed version in your miniconda environment (it will be in `miniconda_dir/libs/python3.8/site-packages/Sire/Tools/WSRC.py`).

Just add in the following line near the top of the file;

```
RepExMove = RepExMove2
```

e.g.

```
import os
import shutil
import copy

wsrc_tools_dir = "%s/Tools/WSRC" % Sire.Config.share_directory

# Switch to use RepExMove while RepExMove2 is unavailable
RepExMove2 = RepExMove
```

You should also do this in `LSRC.py`, which is used for ligandswap. This is in the same directory as `WSRC.py`, e.g.

```
import os
import shutil
import copy

# We will use the waterbox held in the WSRC tools directory
wsrc_tools_dir = "%s/Tools/WSRC" % Sire.Config.share_directory

# Switch to use RepExMove while RepExMove2 is unavailable
RepExMove2 = RepExMove
```

**Comment by shiyx409** [comment]
Thank you for replying. Following your methods, the RepExMove was successfully switched and both ligandswap & waterswap work well.

Cheers.
