### ISSUE TITLE
Velocities lost during read/write with Gro87 parser

### ISSUE THREAD

**Issue by kexul** [michellab/Sire#387]
Dear BioSimSpace developers: 
I found that velocities in Gromacs `.gro` file would lose during reading and saving by BioSimSpace, is this a bug or feature? 

Steps to reproduce: 
```python 
import BioSimSpace as BSS
sys = BSS.IO.readMolecules(['gromacs.gro', 'gromacs.top'])
BSS.IO.saveMolecules('new', sys, ['gro87', 'grotop'])
```

Inputs:
[temp.zip](https://github.com/michellab/BioSimSpace/files/8891181/temp.zip)

Diff: 
![d5d69e82b417f9e77f6eb77d619d853](https://user-images.githubusercontent.com/5920217/173358634-e8fb2281-2f06-4e64-8bca-3a3a1d5d3855.png)

**Comment by lohedges** [comment]
Okay, I've now fixed this. There were numerous incorrect unit conversions on reading / storing / extracting / writing the velocities. In some cases, (different) unit conversions were applied multiple times and the forward / reverse (read / write) procedure was also not symmetric.

Will close when I push to `devel`. Note that we still haven't resolved the [issue with our macOS pipeline](https://github.com/michellab/Sire/issues/386), so there won't be an updated conda package until we figure out a fix.

**Comment by lohedges** [comment]
Looks like some unit tests failed due to precision errors in comparisons. Will fix those when I get a chance and re-push. Ironically they passed before, despite the numbers being complete nonsense.

**Comment by lohedges** [comment]
Actually, there was an incorrect unit conversion in the test too, i.e. going from AMBER to GROMACS units. I think this was the original issue too, i.e. the GROMACS code had been copied from the AMBER parser, with various unit conversions not replaced.
