### ISSUE TITLE
Do we need a separate somd and somd-freenrg apps ? 

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#39]
At the moment users have to decide which app to use if they want to run MD or free energy calculations. 

Internally this is because we call OpenMMMD.run() or OpenMMMD.runFreeNrg()

However both subroutines are fairly similar. Every time we implement a new feature in one subroutine that may be relevant to the other, we have to duplicate code (for instance hydrogen mass repartition). 

It could be possible to have a single somd app that calls OpenMMMD.run(), and use the appropriate free energy specific subroutines if free energy keywords have been passed. Or we could require that free energy calculations are activated with a command line or config file keyword. 

For instance

if  freenrg:
        system = createSystemFreeEnergy(molecules)
else:
        system = createSystem(molecules)

Thoughts?

**Comment by ppxasjsm** [comment]
I think there should only be one command. As soon as there is a morph file and a lambda value(s) provided a free energy calculation is run. (c.f. mdrun in Gromacs)
This makes it much easier to maintain the code and certain things will not need to be duplicated in both scripts, it will also shorten the overall content of OpenMMMD.py

**Comment by jmichel80** [comment]
Agreed. For 15_1 we should remove somd-freenrg, OpenMMMD.runFreeNrg,  and have logic to enable free energy calculations in OpenMMMD.run
