### ISSUE TITLE
somd-freenrg runs ok but somd fails on a solvated protein

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#40]
On feature_HMR, but with HMR flag disabled so code should be equivalent to devel before branch.

Running 
rm *.s3 *.dat *.dcd *.pdb ; ~/sire.app/bin/somd -C ../../input/freenrg.cfg
produces a segfault
(...) 
### Running Molecular Dynamics simulation on unknown ###
###================Setting up calculation=====================###
New run. Loading input and creating restart
Reading topology file "../../input/solvated.parm7" 
Reading coordinate file "../../input/solvated.rst7" 
Building 11221 molecule(s)... 
...building molecule 1000 ... 
...building molecule 2000 ... 
...building molecule 3000 ... 
...building molecule 4000 ... 
...building molecule 5000 ... 
...building molecule 6000 ... 
...building molecule 7000 ... 
...building molecule 8000 ... 
...building molecule 9000 ... 
...building molecule 10000 ... 
...building molecule 11000 ... 
 Getting space information  
Read space "PeriodicBox( ( 69.5294, 73.0467, 75.3992 ) )" 
...complete 
Creating the system...
Creating force fields... 
Setting up the simulation with random seed 325675
Setting up moves...
Created a MD move that uses OpenMM for all molecules on 0 
Generated random seed number 325675 
Saving restart
There are 38319 atoms in the group 
###===========================================================###

###=======================Minimisation========================###
Running minimisation.
Segmentation fault (core dumped)

* Doing 1 step of MD without minimisation also fails

julien@ubuntu:/mnt/hgfs/sims/somd/thrombin-HMR/bound/debug-gradients/output/debug$ rm *.s3 *.dat *.dcd *.pdb ; ~/sire.app/bin/somd -C ../../input/freenrg.cfg
(...)
### Running Molecular Dynamics simulation on unknown ###
###================Setting up calculation=====================###
New run. Loading input and creating restart
Reading topology file "../../input/solvated.parm7" 
Reading coordinate file "../../input/solvated.rst7" 
Building 11221 molecule(s)... 
...building molecule 1000 ... 
...building molecule 2000 ... 
...building molecule 3000 ... 
...building molecule 4000 ... 
...building molecule 5000 ... 
...building molecule 6000 ... 
...building molecule 7000 ... 
...building molecule 8000 ... 
...building molecule 9000 ... 
...building molecule 10000 ... 
...building molecule 11000 ... 
 Getting space information  
Read space "PeriodicBox( ( 69.5294, 73.0467, 75.3992 ) )" 
...complete 
Creating the system...
Creating force fields... 
Setting up the simulation with random seed 608133
Setting up moves...
Created a MD move that uses OpenMM for all molecules on 0 
Generated random seed number 608133 
Saving restart
There are 38319 atoms in the group 
###===========================================================###

###=======================somd run============================###
Starting somd run...
1 moves 1 cycles, 0.002 ps simulation time

Cycle =  1
NaN or Inf has been generated along the simulation 

* But running somd-freenrg works 

julien@ubuntu:/mnt/hgfs/sims/somd/thrombin-HMR/bound/debug-gradients/output/debug$ rm *.s3 *.dat *.dcd *.pdb ; ~/sire.app/bin/somd-freenrg -C ../../input/freenrg.cfg
(...)
Running a somd-freenrg calculation using files ../../input/solvated.parm7, ../../input/solvated.rst7 and ../../input/MORPH.pert.
### Running Single Topology Molecular Dynamics Free Energy on unknown ###
###================Setting up calculation=====================###
New run. Loading input and creating restart
lambda is 0.1
Reading topology file "../../input/solvated.parm7" 
Reading coordinate file "../../input/solvated.rst7" 
Building 11221 molecule(s)... 
...building molecule 1000 ... 
...building molecule 2000 ... 
...building molecule 3000 ... 
...building molecule 4000 ... 
...building molecule 5000 ... 
...building molecule 6000 ... 
...building molecule 7000 ... 
...building molecule 8000 ... 
...building molecule 9000 ... 
...building molecule 10000 ... 
...building molecule 11000 ... 
 Getting space information  
Read space "PeriodicBox( ( 69.5294, 73.0467, 75.3992 ) )" 
...complete 
Create the System...
Selecting dummy groups
Creating force fields... 
Setting up the simulation with random seed 994931
Setting up moves...
Created a MD move that uses OpenMM for all molecules on 0 
Generated random seed number 994931 
Saving restart
There are 38319 atoms in the group 
###===========================================================###

###=======================Minimisation========================###
Running minimisation.
(....) 

Minimisation starts but it takes forever on CPU On my laptop. No immediate segfaults. 

I can also do 1 step of MD without minimisation without error. 

julien@ubuntu:/mnt/hgfs/sims/somd/thrombin-HMR/bound/debug-gradients/output/debug$ rm *.s3 *.dat *.dcd *.pdb ; ~/sire.app/bin/somd-freenrg -C ../../input/freenrg.cfg
Running a somd-freenrg calculation using files ../../input/solvated.parm7, ../../input/solvated.rst7 and ../../input/MORPH.pert.
### Running Single Topology Molecular Dynamics Free Energy on unknown ###
###================Setting up calculation=====================###
New run. Loading input and creating restart
lambda is 0.1
Reading topology file "../../input/solvated.parm7" 
Reading coordinate file "../../input/solvated.rst7" 
Building 11221 molecule(s)... 
...building molecule 1000 ... 
...building molecule 2000 ... 
...building molecule 3000 ... 
...building molecule 4000 ... 
...building molecule 5000 ... 
...building molecule 6000 ... 
...building molecule 7000 ... 
...building molecule 8000 ... 
...building molecule 9000 ... 
...building molecule 10000 ... 
...building molecule 11000 ... 
 Getting space information  
Read space "PeriodicBox( ( 69.5294, 73.0467, 75.3992 ) )" 
...complete 
Create the System...
Selecting dummy groups
Creating force fields... 
Setting up the simulation with random seed 669245
Setting up moves...
Created a MD move that uses OpenMM for all molecules on 0 
Generated random seed number 669245 
Saving restart
There are 38319 atoms in the group 
###===========================================================###

###====================somd-freenrg run=======================###
Starting somd-freenrg run...
1 moves 1 cycles, 0.002 ps simulation time

Cycle =  1 

Saving atom coordinates every  1 
 
Simulation took 25 s 
###===========================================================###

Clearing buffers...
Backing up previous restart
Saving new restart

* I can email input files if useful.

**Comment by ppxasjsm** [comment]
yes can you please email the input files. I have just run a solvated ligand with somd and it ran fine.

**Comment by jmichel80** [comment]
See #43
