### ISSUE TITLE
current gradients code is convoluted and needs to be updated for 15_1

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#46]
With the current code we have in OpenMMDD.py

gradients = integrator.getGradients()
mean_gradient = np.average(gradients)
outgradients.write("%5d %20.10f\n" % (i, mean_gradient))

Thus we take an arithmetic average of values stored in gradients. 

This is done around line 3500 of openmmfrenergyst.cpp

        if (sample_count != (n_samples))
        {
            energies.append(avg_pot_energy_lambda * OpenMM::KcalPerKJ);
            gradients.append(actual_gradient * OpenMM::KcalPerKJ);
        }
        if (sample_count == (n_samples))
        {
            gradients.append(actual_gradient * OpenMM::KcalPerKJ);
            energies.append(avg_pot_energy_lambda * OpenMM::KcalPerKJ);
        }

(Note that energies is a cumulative average, but gradients is not)

* Actual gradient is computed line 3475
        actual_gradient = (minv_beta * log((plus) / (minus))) / double_increment;

* plus and minus are given around line 3455-3473 with expressions of the form 

         plus = exp(-beta * (potential_energy_lambda_plus_delta - potential_energy_lambda));

So after simplifications the gradient amounts to (\Delta Uplus - \DeltaUminus) over (2 * \Delta lambda).

It's ok but convoluted...When the code is rewritten to handle calculation of energies at other lambda values, we should just compute in C++ ensemble averages of differences in energies between a reference and perturbed state. Ideally this is all that should be needed for analysis by another code.
We should avoid averaging energies before output as we may end up with too few datapoints for various analyses (e.g. autocorrelation functions). The datastorage requirements should still be modest compared to the size of the output trajectories.

**Comment by ppxasjsm** [comment]
Yes it is very hard to understand what is going on there. 
I will work on updating this from today. I would vote for not outputting averages at all but do averaging in post processing. The gradients are a great way to figure out how correlated your data is and therefore can be used to as a gauge to what subsampling you should consider to improve your gradient estiamtes. I would vote to write out files similar to those of gromacs output, with gradients and either biased energies or energy differences. They should still be much smaller than the .dcd files with the simulation that is currently being written.

**Comment by jmichel80** [comment]
Yes we should just collect and output 'raw data'

We should write out:

- energy differences to perturbed states. 

-  gradients computed via Finite Difference TI through the Zwanzig equation
DG / DL = Delta G(L->L+DeltaL) - DeltaG(L->L-DeltaL) / 2* DeltaL

- gradients computed via finite difference approximation on energies
DG / DL = DU / DL = DeltaU(L->L+DeltaL) - DeltaU(L->L-DeltaL) / 2 * DeltaL

Both gradients should be equal ? They can be computed in OpenMMMD.py. This could be done regardless of the value of DeltaL, but will not be very meaningful if the DeltaL values are too large/too small. 

- What do you call a biased energy in this context ?

**Comment by ppxasjsm** [comment]
Done.
