### ISSUE TITLE
Disable/save rarely simulation snapshots 

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#47]
We should have a  keyword to save less frequently snapshots in dcd files for intermediate states that do not correspond to chemically meaningful molecules. Many users will want to complement their free energy calculations with analysis of the end-states, but are less likely to perform such analyses on intermediate states. Storing structural data for these states less frequently will significantly reduce disk usage.

**Comment by ppxasjsm** [comment]
Should we again replace this rather convoluted way of doing things here with something clearer in this case:
```
  // Because looping from 1 to n_samples
        int modulo = 1;

        if (coord_freq > 0)
            modulo = sample_count % ((coord_freq / energy_frequency));

        if (Debug)
            qDebug() << "modulo is " << modulo;

        if (coord_freq > 0 and modulo == 0)
        {
            if (Debug)
                qDebug() << "buffering coordinates and dimensions";

            positions_openmm = state_openmm.getPositions();
            buffered_positions.append(positions_openmm);

            if (MCBarostat_flag == true)
            {
                state_openmm.getPeriodicBoxVectors(a, b, c);
                Vector dims = Vector(a[0] * OpenMM::AngstromsPerNm, b[1] * OpenMM::AngstromsPerNm, c[2] * OpenMM::AngstromsPerNm);
                buffered_dimensions.append(dims);
            }
        }
```
Or should this be done purely in python?

**Comment by jmichel80** [comment]
The code can be cleaned up, but buffering coordinates must be done in C++
to avoid overheads associated with frequent context creation/destruction.


--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

On Tue, Aug 11, 2015 at 4:02 PM, ppxasjsm <notifications@github.com> wrote:

> Should we again replace this rather convoluted way of doing things here
> with something clearer in this case:
>
>   // Because looping from 1 to n_samples
>         int modulo = 1;
>
>         if (coord_freq > 0)
>             modulo = sample_count % ((coord_freq / energy_frequency));
>
>         if (Debug)
>             qDebug() << "modulo is " << modulo;
>
>         if (coord_freq > 0 and modulo == 0)
>         {
>             if (Debug)
>                 qDebug() << "buffering coordinates and dimensions";
>
>             positions_openmm = state_openmm.getPositions();
>             buffered_positions.append(positions_openmm);
>
>             if (MCBarostat_flag == true)
>             {
>                 state_openmm.getPeriodicBoxVectors(a, b, c);
>                 Vector dims = Vector(a[0] * OpenMM::AngstromsPerNm, b[1] * OpenMM::AngstromsPerNm, c[2] * OpenMM::AngstromsPerNm);
>                 buffered_dimensions.append(dims);
>             }
>         }
>
> Or should this be done purely in python?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/47#issuecomment-129920013>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
Done.
