### ISSUE TITLE
Switch github default branch to "devel"

### ISSUE THREAD

**Issue by chryswoods** [michellab/Sire#55]
Would it be possible to switch the default branch on github for Sire from "master" to "devel"? All of the statistics on the front page are generated for the default branch, and it currently looks like Sire only has one contributor and few commits. Also, by default, I think that users should see the "devel" branch when they try to check out or see anything, as it shows the bleeding edge of Sire. We should use "master" for merging back stable chunks of code in preparation for release (e.g. as "trunk" was used in google code)

**Comment by ppxasjsm** [comment]
I agree that switching to devel as default branch would be a good idea. I'll have a look at this now. However, master only gets 'release' pushes and nothing else. Devel gets stable chunks of code in preparation for release and any development is done on feature branches, I would say.

**Comment by ppxasjsm** [comment]
Done.

**Comment by chryswoods** [comment]
Thanks :-)
