### ISSUE TITLE
Sire test data is too large - should we split this into a separate download?

### ISSUE THREAD

**Issue by chryswoods** [michellab/Sire#61]
I've just about got the packaging (sire.app/bin/package_sire) working with the anaconda install. Now that I have done this, I have noticed that the size of the Sire directory has increased significantly. This is because the Sire test directory is now very large:

du -hs sire.app = 717 MB
du -hs sire.app/pkgs/sire-0.0.1 = 516 MB
du -hs sire.app/pkgs/sire-0.0.1/test = 397 MB

This results in a sire.run binary package that is 148 MB in size.

If we remove the test directory, then we have;

du -hs sire.app = 320 MB
du -hs sire.app/pkgs/sire-0.0.1 = 118 MB

This results in a sire.run binary package that is 111 MB in size.

The data in the Sire test directory is only likely to grow. I suggest that we create a new git repository for the sire test data and move all of the test data to there. We could then add a small command to the sire_test script that runs a git clone or git pull to download or update the test data before running any tests.

What do you think?

**Comment by ppxasjsm** [comment]
Yes definitely! I wanted to suggest this a while ago too. Also we should really optimise test data and keep them as small as possible. 
Also repository sizes only grow with more and more history so its a good idea to try and minimise the size of unnecessary data (or ideally avoid them all together).

**Comment by jmichel80** [comment]
Yes that's a good idea !

- - -
Julien
Sent from my phone.
On 7 Sep 2015 12:32, "Christopher Woods" <notifications@github.com> wrote:

> I've just about got the packaging (sire.app/bin/package_sire) working with
> the anaconda install. Now that I have done this, I have noticed that the
> size of the Sire directory has increased significantly. This is because the
> Sire test directory is now very large:
>
> du -hs sire.app = 717 MB
> du -hs sire.app/pkgs/sire-0.0.1 = 516 MB
> du -hs sire.app/pkgs/sire-0.0.1/test = 397 MB
>
> This results in a sire.run binary package that is 148 MB in size.
>
> If we remove the test directory, then we have;
>
> du -hs sire.app = 320 MB
> du -hs sire.app/pkgs/sire-0.0.1 = 118 MB
>
> This results in a sire.run binary package that is 111 MB in size.
>
> The data in the Sire test directory is only likely to grow. I suggest that
> we create a new git repository for the sire test data and move all of the
> test data to there. We could then add a small command to the sire_test
> script that runs a git clone or git pull to download or update the test
> data before running any tests.
>
> What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/61>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by jmichel80** [comment]
Would it make sense to have two repisitories. One for 'atomic' unit tests
and one for high-level tests that are almost tutorials (e.g. running full
nautilus workflow or somd ethane methanol).

- - -
Julien
Sent from my phone.
On 7 Sep 2015 12:49, "ppxasjsm" <notifications@github.com> wrote:

> Yes definitely! I wanted to suggest this a while ago too. Also we should
> really optimise test data and keep them as small as possible.
> Also repository sizes only grow with more and more history so its a good
> idea to try and minimise the size of unnecessary data (or ideally avoid
> them all together).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/61#issuecomment-138268543>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
I have thought about this a bit more. Git really isn't meant for storing large data/datasets for tests. Does anyone know of any infrastructure where we could keep the test datasets? These would have to be pulled too, but the repository and its history will get unnecessarily large that way.

**Comment by chryswoods** [comment]
Yes, we will risk running out of repository space if we store these datasets in git. I have a lot of space on my web hosting for large downloads (e.g. tgz files), or alternatively we could just host them on university departmental servers. I envisage something like;

import Sire.Config
if not os.path.exists(Sire.Config.test_directory):
    if not os.path.exists("%s/sire_tests.tar.gz" % Sire.Config.share_directory):
        os.system("wget http://somewhere.com/sire_tests.tar.gz -o %s/sire_tests.tar.gz" % Sire.Config.shared_directory)
        os.system("tar -zxvf ....")
        etc. etc.

**Comment by ppxasjsm** [comment]
Yes, this sounds like a good idea and is the concrete version of what I was looking for.

**Comment by ppxasjsm** [comment]
Useful link for a tidy up in the near future:
https://help.github.com/articles/removing-files-from-a-repository-s-history/

**Comment by chryswoods** [comment]
Actually, perhaps we should just separate out the test data (e.g. coordinate files, trajectory files etc.) but still have the test python scripts in the repository? This will make it easier to develop and amend tests without having to retar up the sire_tests.tar.gz file. We could also then move towards having a standard set of test systems, e.g. thrombin with ligand in water etc., so that these can be stored in both top/crd and also Sire binary .s3 format. This will allow the data to be loaded up once during the test run from the .s3 file, rather than being continually reloaded for each test. This will speed up the running of tests.

Also, on travis I now have the complete install with python wrappers and a mini test. I think the travis build should also download the sire_test.tar.gz file and run through all of the unit tests at the end of the build.

**Comment by ppxasjsm** [comment]
Done there is now a SireUnitTests github repository.
