### ISSUE TITLE
sire install script

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#63]
I just tested the sire install script. It supposedly installs everything correctly, but when it tries to run the test it fails:
```
 ./compile_sire.sh: line 73: 28270 Illegal instruction     (core dumped) ${INSTALL_DIR}/bin/python build/build_sire.py
```
same happens if I try and do it manually:
```
$:~/Projects/Sire/corelib: ~/dev_sire.app/bin/ipython
Python 3.4.3 |Continuum Analytics, Inc.| (default, Jun  4 2015, 15:29:08) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import Sire.CAS
Illegal instruction (core dumped)
```

All I did was try to run the compile_sire bash script.

**Comment by jmichel80** [comment]
Check if SIRE_DISABLE_AVX IS OFF or ON and if the machine you compile on
doesn't support AVX.
If so we should by default compile without any CPU specific optimisation
flags.


On Monday, September 14, 2015, ppxasjsm <notifications@github.com> wrote:

> I just tested the sire install script. It supposedly installs everything
> correctly, but when it tries to run the test it fails:
>
>  ./compile_sire.sh: line 73: 28270 Illegal instruction     (core dumped) ${INSTALL_DIR}/bin/python build/build_sire.py
>
> same happens if I try and do it manually:
>
> $:~/Projects/Sire/corelib: ~/dev_sire.app/bin/ipython
> Python 3.4.3 |Continuum Analytics, Inc.| (default, Jun  4 2015, 15:29:08)
> Type "copyright", "credits" or "license" for more information.
>
> IPython 4.0.0 -- An enhanced Interactive Python.
> ?         -> Introduction and overview of IPython's features.
> %quickref -> Quick reference.
> help      -> Python's own help system.
> object?   -> Details about 'object', use 'object??' for extra details.
>
> In [1]: import Sire.CAS
> Illegal instruction (core dumped)
>
> All I did was try to run the compile_sire bash script.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/63>.
>


-- 
--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
Does not seem to solve the problem. (I just tried a manual install with customised compiler flags). Importing Sire fails still.

**Comment by ppxasjsm** [comment]
(Oddly enough it passes on travis, which is a very similar system to the one I am running.)

**Comment by chryswoods** [comment]
Make sure you have an empty pythonpath. I see that you are running ipython, but this can pull in the wrong ipython if pythonpath is not empty, thereby causing a crash.

**Comment by chryswoods** [comment]
Also try:

gdb /path/to/sire.app/bin/python

Then type "run"
Then type 

import Sire
import Sire.CAS

If it crashes, type "bt" to get a backtrace. This should tell us exactly where things have crashed. Post the full output of gdb here and we can debug.

**Comment by chryswoods** [comment]
p.s. Regarding AVX, the compile will only switch on AVX if it detects it is supported on the machine. There should be no need to switch it off, unless you are compiling on a machine that supports AVX, but are then copying and reusing those binaries on machines that don't support AVX.

**Comment by ppxasjsm** [comment]
Sorry for the slow reply here. 
So the error I get is:
```
In [1]: import Sire

Program received signal SIGILL, Illegal instruction.
0x00007fffed5e2c93 in _GLOBAL__sub_I_angle.cpp ()
   from /home/ppxasjsm/sire.app/bin/../lib/./libSireUnits.so.2015
```

I can use either python or ipython. This was just using python.

**Comment by chryswoods** [comment]
I've now pushed a fix that auto detects whether or not AVX is supported on the processor in the CMakeLists.txt file. This should hopefully fix the problem ;-)

**Comment by chryswoods** [comment]
Closing as I assume this is now fixed?
