### ISSUE TITLE
Sire install fail?

### ISSUE THREAD

**Issue by Steboss** [michellab/Sire#66]
Hi,

I am trying to install sire by ./compile_sire
Everything goes perfectly till the last seconds of installation when it says:
```
force copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/lib to /home/steboss/sire.app/lib
copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/lib/cmake/Qt5Concurrent to /home/steboss/sire.app/lib/cmake/Qt5Concurrent
copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/lib/cmake/Qt5Sql to /home/steboss/sire.app/lib/cmake/Qt5Sql
copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/lib/cmake/Qt5Network to /home/steboss/sire.app/lib/cmake/Qt5Network
copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/lib/cmake/Qt5 to /home/steboss/sire.app/lib/cmake/Qt5
copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/lib/cmake/Qt5Xml to /home/steboss/sire.app/lib/cmake/Qt5Xml
copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/lib/cmake/Qt5Core to /home/steboss/sire.app/lib/cmake/Qt5Core
copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/lib/cmake/Qt5Test to /home/steboss/sire.app/lib/cmake/Qt5Test
copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/lib/cmake to /home/steboss/sire.app/lib/cmake
copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/lib/pkgconfig to /home/steboss/sire.app/lib/pkgconfig
copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/lib to /home/steboss/sire.app/lib
force copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/bin to /home/steboss/sire.app/bin
force copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/share/Sire/Tools/WSRC to /home/steboss/sire.app/share/Sire/Tools/WSRC
force copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/share/Sire/Tools to /home/steboss/sire.app/share/Sire/Tools
force copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/share/Sire/build to /home/steboss/sire.app/share/Sire/build
force copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/share/Sire/scripts to /home/steboss/sire.app/share/Sire/scripts
force copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/share/Sire/parameters to /home/steboss/sire.app/share/Sire/parameters
force copying files from /home/steboss/sire.app/pkgs/sire-2015.0.0/share/Sire to /home/steboss/sire.app/share/Sire
CANNOT REMOVE "bin" FROM "." AS IT IS NOT IN THE PATH? 
Something went wrong when trying to test the Sire installation.
Please check things manually yourself...

```

**Comment by chryswoods** [comment]
Interesting... The error message is actually coming from Sire after installation. It is printed by the stripDir() function in corelib/src/libs/SireBase/getinstalldir.cpp, and is part of the mechanism that Sire uses to work out where it is installed and how to get the absolute paths to, e.g. parameter or share directories. This is strange as the error implies that the arguments to stripDir were "bin" and ".", and I know that this is called to strip "bin" from the full absolute path to the sire.app/bin/python executable (the function should be called using the full absolute path to /dir/sire.app/bin, and then this function removes the "/bin" on the end to get the absolute path to /dir/sire.app.

Looking deeper into the code, the problem is probably the failure of this code in getInstallDir() (also in getinstalldir.cpp)

======
        #ifdef Q_OS_LINUX
            QFileInfo f( "/proc/self/exe" );
        
            if (not f.exists())
                throw SireError::program_bug( QObject::tr(
                        "For some reason /proc/self/exe does not exist for your "
                        "version of Linux. Let the developers know and we will get it "
                        "working for you."), CODELOC );
        
            setInstallDir( stripDir(SIRE_BIN_DIR,f.canonicalPath()) );
            return install_dir;
        #else
=====

If seems that "f.canonicalPath()" may be returning "." rather than the required absolute path. This is strange as f.canonicalPath() should return an absolute path without redundant data (e.g. extra .. or slashes).

Could you edit the C++ code and change the above to read;

======
        #ifdef Q_OS_LINUX
            QFileInfo f( "/proc/self/exe" );
        
            if (not f.exists())
                throw SireError::program_bug( QObject::tr(
                        "For some reason /proc/self/exe does not exist for your "
                        "version of Linux. Let the developers know and we will get it "
                        "working for you."), CODELOC );

            // printing out the values of f.canonicalPath() and f.absolutePath()
            qDebug() << "PATH IS" << f.canonicalPath() << f.absolutePath();
        
            setInstallDir( stripDir(SIRE_BIN_DIR,f.canonicalPath()) );
            return install_dir;
        #else
===================

Recompile using the compile_sire.sh script and then post what is printed out (hopefully we should see the debug statement telling us what the PATH is...

**Comment by Steboss** [comment]
Hi Chris,

that's the results

```
PATH IS "." "/proc/self" 
CANNOT REMOVE "bin" FROM "." AS IT IS NOT IN THE PATH? 
Something went wrong when trying to test the Sire installation.
Please check things manually yourself...
```

**Comment by chryswoods** [comment]
That's a bit frustrating. f should be equal to /proc/self/exe, which is a symbolic link to the running executable. The fact that it is not equalling that suggests either that /proc/self/exe doesn't exist, or that QFileInfo is not working properly.

/proc/self is an alias for /proc/PID where PID is the process ID number of the running process. Could you find the process ID of one of your running processes, e.g. your bash shell, e.g. via "ps -ef | grep YOUR_USERNAME | grep bash". Then could you type 

ls /proc/PID

where PID is the PID of one of your running processes. For example, for my bash shell I get

ps -ef | grep chzcjw | grep bash
chzcjw    5353 24638  0 15:30 pts/76   00:00:00 grep bash
chzcjw   24638 24637  0 14:34 pts/76   00:00:00 -bash

PID = 24638

ls -l /proc/24638
dr-xr-xr-x.  2 chzcjw chem 0 Oct 29 15:31 attr
-rw-r--r--.  1 chzcjw chem 0 Oct 29 15:31 autogroup
-r--------.  1 chzcjw chem 0 Oct 29 15:31 auxv
-r--r--r--.  1 chzcjw chem 0 Oct 29 15:31 cgroup
--w-------.  1 chzcjw chem 0 Oct 29 15:31 clear_refs
-r--r--r--.  1 chzcjw chem 0 Oct 29 15:24 cmdline
-rw-r--r--.  1 chzcjw chem 0 Oct 29 15:31 coredump_filter
-r--r--r--.  1 chzcjw chem 0 Oct 29 15:31 cpuset
lrwxrwxrwx.  1 chzcjw chem 0 Oct 29 15:31 cwd -> /panfs/panasas01/chem/chzcjw/versioned_dir
-r--------.  1 chzcjw chem 0 Oct 29 15:31 environ
lrwxrwxrwx.  1 chzcjw chem 0 Oct 29 15:24 exe -> /bin/bash
dr-x------.  2 chzcjw chem 0 Oct 29 15:25 fd
dr-x------.  2 chzcjw chem 0 Oct 29 15:31 fdinfo
-r--------.  1 chzcjw chem 0 Oct 29 15:31 io
-rw-------.  1 chzcjw chem 0 Oct 29 15:31 limits
etc. etc.

You should see that /proc/PID/exe is a symbolic link pointing to the exectuable, e.g. here is it pointing to /bin/bash

Please do the above and report the output

**Comment by Steboss** [comment]
Here:
```
ps -ef | grep steboss | grep bash

steboss   8094  3769  0 14:37 pts/0    00:00:00 bash
steboss  18194  3769  0 Oct23 pts/10   00:00:00 bash
steboss  28937  8094  0 15:55 pts/0    00:00:00 grep --color=auto bash


ls -l /proc/18194

total 0
dr-xr-xr-x 2 steboss steboss 0 Oct 29 15:49 attr
-rw-r--r-- 1 steboss steboss 0 Oct 29 15:49 autogroup
-r-------- 1 steboss steboss 0 Oct 29 15:49 auxv
-r--r--r-- 1 steboss steboss 0 Oct 29 15:49 cgroup
--w------- 1 steboss steboss 0 Oct 29 15:49 clear_refs
-r--r--r-- 1 steboss steboss 0 Oct 23 13:07 cmdline
-rw-r--r-- 1 steboss steboss 0 Oct 29 15:49 comm
-rw-r--r-- 1 steboss steboss 0 Oct 29 15:49 coredump_filter
-r--r--r-- 1 steboss steboss 0 Oct 29 15:49 cpuset
lrwxrwxrwx 1 steboss steboss 0 Oct 26 07:45 cwd -> /home/steboss
-r-------- 1 steboss steboss 0 Oct 24 14:22 environ
lrwxrwxrwx 1 steboss steboss 0 Oct 26 07:45 exe -> /bin/bash
dr-x------ 2 steboss steboss 0 Oct 23 12:16 fd
dr-x------ 2 steboss steboss 0 Oct 29 15:49 fdinfo
...
```

**Comment by Steboss** [comment]
Actually, it seems Sire is installed
I have tried to run a simulation, but it crashes with this error:
```
Loading configuration information from file sim.cfg

 
Running a somd-freenrg calculation using files reversed_top.prmtop, reversed.rst7 and MORPH.pert.
Using parameters:
===============
#distance restraints dictionary == {(3, 47): (6.45, 10.0, 1.0), (3, 34): (5.32, 10.0, 1.0), (3, 22): (5.06, 10.0, 1.0), (3, 53): (6.2, 10.0, 1.0)}
andersen == True
barostat == True
buffered coordinates frequency == 500
center solute == True
constraint == hbonds
crdfile == reversed.rst7
cutoff distance == 14 angstrom
cutofftype == cutoffperiodic
energy frequency == 100
equilibrate == True
equilibration iterations == 5000
lambda_val == 0.0
minimize == True
morphfile == MORPH.pert
ncycles == 500
nmoves == 10000
platform == CUDA
precision == mixed
save coordinates == True
topfile == reversed_top.prmtop
use distance restraints == True
===============

### Running Single Topology Molecular Dynamics Free Energy on unknown ###
###================Setting up calculation=====================###
New run. Loading input and creating restart
lambda is 0.0
Create the System...
Selecting dummy groups
[]
Creating force fields... 
Setting up the simulation with random seed 276648
Setting up moves...
Traceback (most recent call last):
  File "/home/steboss/sire.app/share/Sire/scripts/somd-freenrg.py", line 142, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/home/steboss/sire.app/lib/python3.4/site-packages/Sire/Tools/__init__.py", line 140, in inner
    retval = func()
  File "/home/steboss/sire.app/lib/python3.4/site-packages/Sire/Tools/OpenMMMD.py", line 1440, in runFreeNrg
    moves = setupMovesFreeEnergy(system, ranseed, gpu.val, lambda_val.val)
  File "/home/steboss/sire.app/lib/python3.4/site-packages/Sire/Tools/OpenMMMD.py", line 1115, in setupMovesFreeEnergy
    Integrator_OpenMM = OpenMMFrEnergyST(molecules, solute, solute_hard, solute_todummy, solute_fromdummy)
Boost.Python.ArgumentError: Python argument types in
    OpenMMFrEnergyST.__init__(OpenMMFrEnergyST, MoleculeGroup, MoleculeGroup, MoleculeGroup, MoleculeGroup, MoleculeGroup)
did not match C++ signature:
    __init__(_object*)
```

**Comment by Steboss** [comment]
I tried the installation on another workstation, mounting Ubuntu 14.04 as well, but nothing to do
This error is still present

CANNOT REMOVE "bin" FROM "." AS IT IS NOT IN THE PATH? 
Something went wrong when trying to test the Sire installation.
Please check things manually yourself..

**Comment by chryswoods** [comment]
Very strange. Sire seems to work fine and the getInstallDir function is working after installation (the crash is because of another reason). However, it is not working immediately during the install, despite /proc/PID/exe appearing to exist and being correct.

The OpenMM error looks like it is caused by Sire compiling without OpenMM support. Is this because OpenMM didn't install into miniconda?

**Comment by Steboss** [comment]
Is at that stage the Sire installation finished? So, could/should Sire actually work?
The OpenMM error unfortunately I don't know  when it comes from
Conda correctly downloads and finds OpenMM during the  installation :s

**Comment by chryswoods** [comment]
Yes, the error comes from a final test run after installation that checks whether or not Sire has been correctly installed. This test looks like it is giving a false negative, and in fact Sire is ok.

For the OpenMM error, could you cd into the build/corelib directory and run cmake, and then paste the output here. The cmake output should indicate whether or not OpenMM is being found.

**Comment by Steboss** [comment]
Hi Chris

here the output:

'''
    SIRE_VERSION
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Disabling any code that requires compilation or linking to Fortran
-- C++11 supported features: HAS_CXX11_AUTO;HAS_CXX11_NULLPTR;HAS_CXX11_LAMBDA;HAS_CXX11_STATIC_ASSERT;HAS_CXX11_RVALUE_REFERENCES;HAS_CXX11_DECLTYPE;HAS_CXX11_CSTDINT_H;HAS_CXX11_LONG_LONG;HAS_CXX11_VARIADIC_TEMPLATES;HAS_CXX11_CONSTEXPR;HAS_CXX11_SIZEOF_MEMBER;HAS_CXX11_FUNC
-- Detected and using GCC C and C++ compilers
-- Using GCC version 4.6
-- Compiling with AVX enabled. Resulting binary will only work on newer Intel CPUs
-- Sire will be compiled to use its own copy of bundled libraries.
-- Compiling and installing a bundled version of Intel's Threaded Building Blocks (TBB)
-- EXECUTE INFO_COMMAND GET OS: linux
arch=intel64
compiler=gcc
runtime=cc4.6_libc2.19_kernel3.13.0
tbb_build_prefix=linux_intel64_gcc_cc4.6_libc2.19_kernel3.13.0

-- TBB will be built in the directory /home/steboss/Software/Sire/build/corelib/build_bundled/tbb/build/linux_intel64_gcc_cc4.6_libc2.19_kernel3.13.0_release
-- Patience... Compiling TBB from source...
Created ./build/linux_intel64_gcc_cc4.6_libc2.19_kernel3.13.0_release and ..._debug directories
/usr/bin/make -C "./build/linux_intel64_gcc_cc4.6_libc2.19_kernel3.13.0_debug"  -r -f ../../build/Makefile.tbb cfg=debug tbb_root=../..
../../build/Makefile.tbb:39: CONFIG: cfg=debug arch=intel64 compiler=gcc os=linux runtime=cc4.6_libc2.19_kernel3.13.0
make[1]: Entering directory `/home/steboss/Software/Sire/build/corelib/build_bundled/tbb/build/linux_intel64_gcc_cc4.6_libc2.19_kernel3.13.0_debug'
make[1]: Nothing to be done for `default_tbb'.
make[1]: Leaving directory `/home/steboss/Software/Sire/build/corelib/build_bundled/tbb/build/linux_intel64_gcc_cc4.6_libc2.19_kernel3.13.0_debug'
/usr/bin/make -C "./build/linux_intel64_gcc_cc4.6_libc2.19_kernel3.13.0_release"  -r -f ../../build/Makefile.tbb cfg=release tbb_root=../..
../../build/Makefile.tbb:39: CONFIG: cfg=release arch=intel64 compiler=gcc os=linux runtime=cc4.6_libc2.19_kernel3.13.0
make[1]: Entering directory `/home/steboss/Software/Sire/build/corelib/build_bundled/tbb/build/linux_intel64_gcc_cc4.6_libc2.19_kernel3.13.0_release'
make[1]: Nothing to be done for `default_tbb'.
make[1]: Leaving directory `/home/steboss/Software/Sire/build/corelib/build_bundled/tbb/build/linux_intel64_gcc_cc4.6_libc2.19_kernel3.13.0_release'
-- ...complete
-- Patience... Compiling TBB malloc from source...
Created ./build/linux_intel64_gcc_cc4.6_libc2.19_kernel3.13.0_release and ..._debug directories
/usr/bin/make -C "./build/linux_intel64_gcc_cc4.6_libc2.19_kernel3.13.0_debug"  -r -f ../../build/Makefile.tbbmalloc cfg=debug malloc tbb_root=../..
make[1]: Entering directory `/home/steboss/Software/Sire/build/corelib/build_bundled/tbb/build/linux_intel64_gcc_cc4.6_libc2.19_kernel3.13.0_debug'
make[1]: Nothing to be done for `malloc'.
make[1]: Leaving directory `/home/steboss/Software/Sire/build/corelib/build_bundled/tbb/build/linux_intel64_gcc_cc4.6_libc2.19_kernel3.13.0_debug'
/usr/bin/make -C "./build/linux_intel64_gcc_cc4.6_libc2.19_kernel3.13.0_release"  -r -f ../../build/Makefile.tbbmalloc cfg=release malloc tbb_root=../..
make[1]: Entering directory `/home/steboss/Software/Sire/build/corelib/build_bundled/tbb/build/linux_intel64_gcc_cc4.6_libc2.19_kernel3.13.0_release'
make[1]: Nothing to be done for `malloc'.
make[1]: Leaving directory `/home/steboss/Software/Sire/build/corelib/build_bundled/tbb/build/linux_intel64_gcc_cc4.6_libc2.19_kernel3.13.0_release'
-- ...complete
-- Using TBB from /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/include
-- Libraries /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/lib/libtbb.so.2 | /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/lib/libtbbmalloc.so.2
-- Have already compiled a bundled version of libcpuid
-- Using libcpuid from /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/lib/libcpuid.so
-- Have already compiled a bundled version of GSL
-- Using GSL from /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/lib/libgsl.so | /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/lib/libgslcblas.so
-- Have already unpacked a bundled version of Boost
-- Using Boost headers in /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/include/boost
-- Have already compiled a bundled version of Qt5Core
-- Using Qt5Core from /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled
-- Library: /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/lib/libQt5Core.so.5.2.0
-- Found OpenMM at /home/steboss/sire.app
-- Qt5Core location /home/steboss/sire.app/pkgs/sire-2015.0.0/bundled/lib
-- A library with BLAS API found.
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- Found BLAS library /usr/lib/libf77blas.so;/usr/lib/libatlas.so
-- Found LAPACK library /usr/lib/liblapack.so;/usr/lib/libf77blas.so;/usr/lib/libatlas.so
-- CMAKE_SYSTEM_NAME      == Linux
-- CMAKE_C_COMPILER       == /usr/bin/cc
-- CMAKE_CXX_COMPILER     == /usr/bin/c++
-- CMAKE_Fortran_COMPILER == 
-- SIRE_CXX11_FLAGS       == 
-- SIRE_SMALL_FLAGS       == -Os
-- SIRE_WARNALL_FLAGS     == -Wall -Wno-attributes
-- SIRE_DEBUG_FLAGS       == -g
-- SIRE_RELEASE_FLAGS     == -O3 -ffast-math -fomit-frame-pointer
-- SIRE_OPENMP_FLAGS      == -fopenmp
-- SIRE_VECTOR_FLAGS      == -mavx -DSIRE_USE_AVX
-- SIRE_VISIBILITY_FLAGS  == -DSIRE_VISIBILITY_AVAILABLE -fvisibility=hidden -fvisibility-inlines-hidden
-- SIRE_PLATFORM_FLAGS    == -pipe -Wno-strict-aliasing
-- SIRE_SHARE_LINK_FLAGS  ==  -rdynamic -Wl,--no-undefined
-- SIRE_STATIC_LINK_FLAGS == -static
-- SIRE_EXE_LINK_FLAGS    == 
-- Compiling Sire using a default (RELEASE) build
-- C compiler flags       == -O3 -DNDEBUG -Wall -Wno-attributes -pipe -Wno-strict-aliasing -DSIRE_VISIBILITY_AVAILABLE -fvisibility=hidden -fvisibility-inlines-hidden -mavx -DSIRE_USE_AVX -O3 -ffast-math -fomit-frame-pointer  -Wall -Wno-attributes -pipe -Wno-strict-aliasing -DSIRE_VISIBILITY_AVAILABLE -fvisibility=hidden -fvisibility-inlines-hidden -mavx -DSIRE_USE_AVX -O3 -ffast-math -fomit-frame-pointer 
-- C++ compiler flags     ==  -Wall -Wno-attributes -pipe -Wno-strict-aliasing -DSIRE_VISIBILITY_AVAILABLE -fvisibility=hidden -fvisibility-inlines-hidden -mavx -DSIRE_USE_AVX  -O3 -ffast-math -fomit-frame-pointer   -Wall -Wno-attributes -pipe -Wno-strict-aliasing -DSIRE_VISIBILITY_AVAILABLE -fvisibility=hidden -fvisibility-inlines-hidden -mavx -DSIRE_USE_AVX  -O3 -ffast-math -fomit-frame-pointer  
-- Shared library flags    ==    -rdynamic -Wl,--no-undefined -DSIRE_VISIBILITY_AVAILABLE -fvisibility=hidden -fvisibility-inlines-hidden
-- Static library flags    ==  -static
-- Executable link flags   ==   
-- SireCluster will be compiled without MPI support.
-- Backtrace functionality is available.
-- Disabling SireMaths BLAS/LAPACK/LINPACK interfaces.
-- Have to do this as Fortran code has been disabled.
-- Adding in OpenMM support to SireMove using OpenMM /home/steboss/sire.app
-- /home/steboss/sire.app/lib/libOpenMM.so | /home/steboss/sire.app/include
-- REPOSITORY_URL = git@github.com:michellab/Sire.git | devel
-- VERSION_NUMBER = 80fbed788262264a12e8487fda5834231bb16a6e/Christopher Woods/%aI
-- Configuring done
-- Generating done
-- Build files have been written to: /home/steboss/Software/Sire/build/corelib
'''

**Comment by Steboss** [comment]
Uh wait
I am exporting OpenMM on the bashrc 
Could it interfere with conda/openmm? 
I am going to  try

**Comment by Steboss** [comment]
No I was wrong
Nothing changes, still problem with openMM

**Comment by chryswoods** [comment]
Strange. It is finding and it is compiling and install OpenMM. Could you create a tgz of the directory (or use /home/steboss/sire.app/bin/package_sire to package sire) and then send the result to me via dropbox or google drive? I want to check your binary as I don't understand why it seems to have compiled the wrappers without OpenMM support, while cmake is showing that OpenMM is installed and being found.

**Comment by chryswoods** [comment]
Thanks - the problem is that the new Sire python wrapper generator is not actually generating the OpenMM-enabled wrappers! I am now working on updating the wrapper generator and will regenerate the correct, OpenMM-enabled wrappers. I will let you know when I am done. Currently I am having issues because Py++ doesn't like the OpenMM header files...

**Comment by Steboss** [comment]
Great Chris 
Don't worry and thank you  very much for you help

**Comment by chryswoods** [comment]
Ok - I've now pushed up a version to devel that has OpenMM wrappers that actually link to OpenMM ;-)

Pull this and recompile and (hopefully) it should work (it works locally)

**Comment by Steboss** [comment]
Great Chris!

The installation is fine and finished with a Congratulations :) 
OpenMM doesn't give problems
Simulations run fine :) 
:+1: 

Thank you very much

Stefano

**Comment by chryswoods** [comment]
Excellent. Sorry for not noticing that the OpenMM wrappers were incorrectly generated. This is definitely something that I should add to the unit tests....
