### ISSUE TITLE
cutofftype or cutoff type?

### ISSUE THREAD

**Issue by Steboss** [michellab/Sire#69]
That's the problem

I am running a simulation of ligand in cyclohexane, on CUDA, with latest Sire
in the configuration file I have:
```
cutofftype = cutoffperiodic

```
and it works fine 

I am performing  a vacuum simulation of the same ligand, but this time Sire crashes with this error:

```

Loading configuration information from file sim.cfg

 
Running a somd-freenrg calculation using files SYSTEM.top, SYSTEM.crd and MORPH.pert.
Using parameters:
===============
andersen == True
barostat == False
buffered coordinates frequency == 500
center solute == True
constraint == hbonds
crdfile == SYSTEM.crd
cutoff distance == 10 angstrom
cutofftype == cutoffnonperiodic
energy frequency == 100
equilibrate == True
equilibration iterations == 5000
gpu == 0
lambda array == (0.0, 0.0625, 0.125, 0.1875, 0.25, 0.3125, 0.375, 0.4375, 0.5, 0.5625, 0.625, 0.6875, 0.75, 0.8125, 0.875, 0.9375, 1)
lambda_val == 0.0
minimise == True
morphfile == MORPH.pert
ncycles == 100
nmoves == 12500
platform == Reference
precision == mixed
save coordinates == True
timestep == 0.002 ps
topfile == SYSTEM.top
===============

### Running Single Topology Molecular Dynamics Free Energy on unknown ###
###================Setting up calculation=====================###
New run. Loading input and creating restart
lambda is 0.0
Reading topology file "SYSTEM.top" 
Reading coordinate file "SYSTEM.crd" 
Building 1 molecule(s)... 
 Getting space information  
Read space "Infinite cartesian space" 
...complete 
Create the System...
Selecting dummy groups
Creating force fields... 
Setting up the simulation with random seed 568384
Setting up moves...
Created a MD move that uses OpenMM for all molecules on 0 
Generated random seed number 568384 
Saving restart
Setting up sim file. 
There are 18 atoms in the group 
###===========================================================###

###=======================Minimisation========================###
Running minimisation.
Traceback (most recent call last):
  File "/home/steboss/sire.app/share/Sire/scripts/somd-freenrg.py", line 142, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/home/steboss/sire.app/lib/python3.5/site-packages/Sire/Tools/__init__.py", line 140, in inner
    retval = func()
  File "/home/steboss/sire.app/lib/python3.5/site-packages/Sire/Tools/OpenMMMD.py", line 1496, in runFreeNrg
    system = integrator.minimiseEnergy(system, minimise_tol.val, minimise_max_iter.val)
UserWarning: Exception 'SireError::invalid_cast' thrown by the thread 'master:main'.
Cannot cast from an object of class "SireVol::Cartesian" to an object of class "SireVol::PeriodicBox".
Thrown from FILE: /home/steboss/Software/Sire/corelib/src/libs/SireBase/property.cpp, LINE: 120, FUNCTION: void SireBase::Property::throwInvalidCast(const char*) const
__Backtrace__
(  0) /home/steboss/sire.app/bin/../lib/libSireError.so.2015 ([0x2b39311cf45c] ++0x2c)
  -- SireError::getBackTrace()

(  1) /home/steboss/sire.app/bin/../lib/libSireError.so.2015 ([0x2b39311cc55e] ++0x9e)
  -- SireError::exception::exception(QString, QString)

(  2) /home/steboss/sire.app/bin/../lib/libSireBase.so.2015 ([0x2b3931b57a80] ++0x200)
  -- SireBase::Property::throwInvalidCast(char const*) const

(  3) /home/steboss/sire.app/bin/../lib/libSireMove.so.2015 ([0x2b394014eab3] ++0xa3)
  -- SireVol::PeriodicBox const& SireBase::Property::asA<SireVol::PeriodicBox>() const

(  4) /home/steboss/sire.app/bin/../lib/libSireMove.so.2015 ([0x2b394016e480] ++0x120)
  -- SireMove::OpenMMFrEnergyST::createContext(SireMove::IntegratorWorkspace&, SireUnits::Dimension::PhysUnit<0, 0, 1, 0, 0, 0, 0>)

(  5) /home/steboss/sire.app/bin/../lib/libSireMove.so.2015 ([0x2b3940172f87] ++0xf7)
  -- SireMove::OpenMMFrEnergyST::minimiseEnergy(SireSystem::System&, double, int)

/home/steboss/sire.app/lib/python3.5/site-packages/Sire/Move/_Move.so(+0xfaa3c) [0x2b3940c9aa3c]
(  7) /home/steboss/sire.app/bin/../lib/libboost_python.so ([0x2b3935937665] ++0x1b5)
  -- boost::python::objects::function::call(_object*, _object*) const

/home/steboss/sire.app/bin/../lib/libboost_python.so(+0x29898) [0x2b3935937898]
(  9) /home/steboss/sire.app/bin/../lib/libboost_python.so ([0x2b393592b703] ++0x43)
  -- boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const

/home/steboss/sire.app/lib/python3.5/site-packages/Sire/Error/_Error.so(+0x24cd) [0x2b3935b5e4cd]
( 11) /home/steboss/sire.app/bin/../lib/libboost_python.so ([0x2b393592b6e6] ++0x26)
  -- boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const

/home/steboss/sire.app/lib/python3.5/site-packages/Sire/Error/_Error.so(+0x248b) [0x2b3935b5e48b]
( 13) /home/steboss/sire.app/bin/../lib/libboost_python.so ([0x2b393592b4e9] ++0x29)
  -- boost::python::handle_exception_impl(boost::function0<void>)

/home/steboss/sire.app/bin/../lib/libboost_python.so(+0x280c4) [0x2b39359360c4]
( 15) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b393143ff36] ++0x56)
  -- PyObject_Call

( 16) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b393151af02] ++0x7ac2)
  -- PyEval_EvalFrameEx

( 17) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b393151bc21] ++0x87e1)
  -- PyEval_EvalFrameEx

/home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0(+0x144179) [0x2b393151d179]
( 19) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b393151b704] ++0x82c4)
  -- PyEval_EvalFrameEx

/home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0(+0x144179) [0x2b393151d179]
( 21) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b393151d308] ++0x48)
  -- PyEval_EvalCodeEx

( 22) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b393151d34b] ++0x3b)
  -- PyEval_EvalCode

( 23) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b3931542580] ++0x130)
  -- PyRun_FileExFlags

( 24) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b3931543b53] ++0x173)
  -- PyRun_SimpleFileExFlags

( 25) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b393155eb77] ++0xca7)
  -- Py_Main

/home/steboss/sire.app/bin/somd-freenrg() [0x403012]
( 27) /lib/x86_64-linux-gnu/libc.so.6 ([0x2b3932cbfec5] ++0xf5)
  -- __libc_start_main

/home/steboss/sire.app/bin/somd-freenrg() [0x403b20]
__EndTrace__
Exception 'SireError::invalid_cast' thrown by the thread 'master:main'.
Cannot cast from an object of class "SireVol::Cartesian" to an object of class "SireVol::PeriodicBox".
Thrown from FILE: /home/steboss/Software/Sire/corelib/src/libs/SireBase/property.cpp, LINE: 120, FUNCTION: void SireBase::Property::throwInvalidCast(const char*) const


```

I compared my sim.cfg with  ones of Julien and the only difference is

```
cutoff type = cutoffnonperiodic
```
with a space between cutoff and type
And the simulation is running now

Could be a problem/typo error  somewhere?

**Comment by jmichel80** [comment]
Hi Stefano,

So your problem is that the correct syntax is
'cutoff type'

If you type 'cutofftype' in your config file you have actually defined a
new parameter. This is silently ignored  by the parser, and you end up
using the default value for 'cutoff type' which is 'cutoffperiodic'.
This happens to be what you want for simulations with periodic boundaries,
but not for vacuum hence the crash.

Julien




--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

On Fri, Nov 6, 2015 at 4:02 PM, Steboss <notifications@github.com> wrote:

> That's the problem
>
> I am running a simulation of ligand in cyclohexane, on CUDA, with latest
> Sire
> in the configuration file I have:
>
> cutofftype = cutoffperiodic
>
>
> and it works fine
>
> I am performing a vacuum simulation of the same ligand, but this time Sire
> crashes with this error:
>
>
> Loading configuration information from file sim.cfg
>
>
> Running a somd-freenrg calculation using files SYSTEM.top, SYSTEM.crd and MORPH.pert.
> Using parameters:
> ===============
> andersen == True
> barostat == False
> buffered coordinates frequency == 500
> center solute == True
> constraint == hbonds
> crdfile == SYSTEM.crd
> cutoff distance == 10 angstrom
> cutofftype == cutoffnonperiodic
> energy frequency == 100
> equilibrate == True
> equilibration iterations == 5000
> gpu == 0
> lambda array == (0.0, 0.0625, 0.125, 0.1875, 0.25, 0.3125, 0.375, 0.4375, 0.5, 0.5625, 0.625, 0.6875, 0.75, 0.8125, 0.875, 0.9375, 1)
> lambda_val == 0.0
> minimise == True
> morphfile == MORPH.pert
> ncycles == 100
> nmoves == 12500
> platform == Reference
> precision == mixed
> save coordinates == True
> timestep == 0.002 ps
> topfile == SYSTEM.top
> ===============
>
> ### Running Single Topology Molecular Dynamics Free Energy on unknown ###
> ###================Setting up calculation=====================###
> New run. Loading input and creating restart
> lambda is 0.0
> Reading topology file "SYSTEM.top"
> Reading coordinate file "SYSTEM.crd"
> Building 1 molecule(s)...
>  Getting space information
> Read space "Infinite cartesian space"
> ...complete
> Create the System...
> Selecting dummy groups
> Creating force fields...
> Setting up the simulation with random seed 568384
> Setting up moves...
> Created a MD move that uses OpenMM for all molecules on 0
> Generated random seed number 568384
> Saving restart
> Setting up sim file.
> There are 18 atoms in the group
> ###===========================================================###
>
> ###=======================Minimisation========================###
> Running minimisation.
> Traceback (most recent call last):
>   File "/home/steboss/sire.app/share/Sire/scripts/somd-freenrg.py", line 142, in <module>
>     OpenMMMD.runFreeNrg(params)
>   File "/home/steboss/sire.app/lib/python3.5/site-packages/Sire/Tools/__init__.py", line 140, in inner
>     retval = func()
>   File "/home/steboss/sire.app/lib/python3.5/site-packages/Sire/Tools/OpenMMMD.py", line 1496, in runFreeNrg
>     system = integrator.minimiseEnergy(system, minimise_tol.val, minimise_max_iter.val)
> UserWarning: Exception 'SireError::invalid_cast' thrown by the thread 'master:main'.
> Cannot cast from an object of class "SireVol::Cartesian" to an object of class "SireVol::PeriodicBox".
> Thrown from FILE: /home/steboss/Software/Sire/corelib/src/libs/SireBase/property.cpp, LINE: 120, FUNCTION: void SireBase::Property::throwInvalidCast(const char*) const
> __Backtrace__
> (  0) /home/steboss/sire.app/bin/../lib/libSireError.so.2015 ([0x2b39311cf45c] ++0x2c)
>   -- SireError::getBackTrace()
>
> (  1) /home/steboss/sire.app/bin/../lib/libSireError.so.2015 ([0x2b39311cc55e] ++0x9e)
>   -- SireError::exception::exception(QString, QString)
>
> (  2) /home/steboss/sire.app/bin/../lib/libSireBase.so.2015 ([0x2b3931b57a80] ++0x200)
>   -- SireBase::Property::throwInvalidCast(char const*) const
>
> (  3) /home/steboss/sire.app/bin/../lib/libSireMove.so.2015 ([0x2b394014eab3] ++0xa3)
>   -- SireVol::PeriodicBox const& SireBase::Property::asA<SireVol::PeriodicBox>() const
>
> (  4) /home/steboss/sire.app/bin/../lib/libSireMove.so.2015 ([0x2b394016e480] ++0x120)
>   -- SireMove::OpenMMFrEnergyST::createContext(SireMove::IntegratorWorkspace&, SireUnits::Dimension::PhysUnit<0, 0, 1, 0, 0, 0, 0>)
>
> (  5) /home/steboss/sire.app/bin/../lib/libSireMove.so.2015 ([0x2b3940172f87] ++0xf7)
>   -- SireMove::OpenMMFrEnergyST::minimiseEnergy(SireSystem::System&, double, int)
>
> /home/steboss/sire.app/lib/python3.5/site-packages/Sire/Move/_Move.so(+0xfaa3c) [0x2b3940c9aa3c]
> (  7) /home/steboss/sire.app/bin/../lib/libboost_python.so ([0x2b3935937665] ++0x1b5)
>   -- boost::python::objects::function::call(_object*, _object*) const
>
> /home/steboss/sire.app/bin/../lib/libboost_python.so(+0x29898) [0x2b3935937898]
> (  9) /home/steboss/sire.app/bin/../lib/libboost_python.so ([0x2b393592b703] ++0x43)
>   -- boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const
>
> /home/steboss/sire.app/lib/python3.5/site-packages/Sire/Error/_Error.so(+0x24cd) [0x2b3935b5e4cd]
> ( 11) /home/steboss/sire.app/bin/../lib/libboost_python.so ([0x2b393592b6e6] ++0x26)
>   -- boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const
>
> /home/steboss/sire.app/lib/python3.5/site-packages/Sire/Error/_Error.so(+0x248b) [0x2b3935b5e48b]
> ( 13) /home/steboss/sire.app/bin/../lib/libboost_python.so ([0x2b393592b4e9] ++0x29)
>   -- boost::python::handle_exception_impl(boost::function0<void>)
>
> /home/steboss/sire.app/bin/../lib/libboost_python.so(+0x280c4) [0x2b39359360c4]
> ( 15) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b393143ff36] ++0x56)
>   -- PyObject_Call
>
> ( 16) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b393151af02] ++0x7ac2)
>   -- PyEval_EvalFrameEx
>
> ( 17) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b393151bc21] ++0x87e1)
>   -- PyEval_EvalFrameEx
>
> /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0(+0x144179) [0x2b393151d179]
> ( 19) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b393151b704] ++0x82c4)
>   -- PyEval_EvalFrameEx
>
> /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0(+0x144179) [0x2b393151d179]
> ( 21) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b393151d308] ++0x48)
>   -- PyEval_EvalCodeEx
>
> ( 22) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b393151d34b] ++0x3b)
>   -- PyEval_EvalCode
>
> ( 23) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b3931542580] ++0x130)
>   -- PyRun_FileExFlags
>
> ( 24) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b3931543b53] ++0x173)
>   -- PyRun_SimpleFileExFlags
>
> ( 25) /home/steboss/sire.app/bin/../lib/libpython3.5m.so.1.0 ([0x2b393155eb77] ++0xca7)
>   -- Py_Main
>
> /home/steboss/sire.app/bin/somd-freenrg() [0x403012]
> ( 27) /lib/x86_64-linux-gnu/libc.so.6 ([0x2b3932cbfec5] ++0xf5)
>   -- __libc_start_main
>
> /home/steboss/sire.app/bin/somd-freenrg() [0x403b20]
> __EndTrace__
> Exception 'SireError::invalid_cast' thrown by the thread 'master:main'.
> Cannot cast from an object of class "SireVol::Cartesian" to an object of class "SireVol::PeriodicBox".
> Thrown from FILE: /home/steboss/Software/Sire/corelib/src/libs/SireBase/property.cpp, LINE: 120, FUNCTION: void SireBase::Property::throwInvalidCast(const char*) const
>
>
>
> I compared my sim.cfg with ones of Julien and the only difference is
>
> cutoff type = cutoffnonperiodic
>
> with a space between cutoff and type
> And the simulation is running now
>
> Could be a problem/typo error somewhere?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/69>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by Steboss** [comment]
Ah 
Ok perfect 
so cutoff type
Perfect
Thanks Julien
