### ISSUE TITLE
Error on somd

### ISSUE THREAD

**Issue by s1040362** [michellab/Sire#70]
Trying to run test md - 

config.cfg file contents: 

# Length of simulation and platform
nmoves = 1000
ncycles = 1
#platform = OpenCL

# Input files
topfile = solvated.parm7
crdfile = solvated.rst7

# Poiential energy function parameters
cutoff type = cutoffperiodic
cutoff distance = 10 * angstrom
reaction field dielectric = 78.3
shift delta = 2.0
coulomb power = 0

# MD integration parameters
timestep = 2 * femtosecond
constraint = hbonds
integrator type = leapfrogverlet 
center of mass frequency = 10

# Temperature/Pressure control
temperature = 298.15 * kelvin
pressure = 1 * atm
andersen = True
andersen frequency = 10
barostat = True
barostat frequency = 25
center of mass frequency = 10 

# Equilibration protocol
minimise = True

# Output control 
save coordinates = True
buffered coordinates frequency = 1000
energy frequency = 100

Run the above file using: 

./sommmd.sh

Details of error:
```
### Running Molecular Dynamics simulation on unknown ###
###================Setting up calculation=====================###
New run. Loading input and creating restart
Creating the system...
Creating force fields... 
Setting up the simulation with random seed 557910
Setting up moves...
Traceback (most recent call last):
  File "/home/lisa/sire.app/share/Sire/scripts/somd.py", line 119, in <module>
    OpenMMMD.run(params)
  File "/home/lisa/sire.app/lib/python3.4/site-packages/Sire/Tools/__init__.py", line 140, in inner
    retval = func()
  File "/home/lisa/sire.app/lib/python3.4/site-packages/Sire/Tools/OpenMMMD.py", line 1295, in run
    moves = setupMoves(system, ranseed, gpu.val)
  File "/home/lisa/sire.app/lib/python3.4/site-packages/Sire/Tools/OpenMMMD.py", line 433, in setupMoves
    Integrator_OpenMM = OpenMMMDIntegrator(molecules)
Boost.Python.ArgumentError: Python argument types in
    OpenMMMDIntegrator.__init__(OpenMMMDIntegrator, MoleculeGroup)
did not match C++ signature:
    __init__(_object*)
```

**Comment by jmichel80** [comment]
Hi Lisa,

Could you post your problem on

https://groups.google.com/forum/#!forum/sire-users

Github is better suited for discussions about code changes.

Before you do that, can you check that you get the same output if you type:

~/sire.app/bin/somd ?

Please also show the path to the file sommmd.sh . It looks like you have
been using an old sire script.
What version of sire are you trying to run ?

Best wishes,

Julien


--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

On Tue, Nov 10, 2015 at 1:19 PM, s1040362 <notifications@github.com> wrote:

> Trying to run test md -
>
> config.cfg file contents:
> Length of simulation and platform
>
> nmoves = 1000
> ncycles = 1
> #platform = OpenCL
> Input files
>
> topfile = solvated.parm7
> crdfile = solvated.rst7
> Poiential energy function parameters
>
> cutoff type = cutoffperiodic
> cutoff distance = 10 * angstrom
> reaction field dielectric = 78.3
> shift delta = 2.0
> coulomb power = 0
> MD integration parameters
>
> timestep = 2 * femtosecond
> constraint = hbonds
> integrator type = leapfrogverlet
> center of mass frequency = 10
> Temperature/Pressure control
>
> temperature = 298.15 * kelvin
> pressure = 1 * atm
> andersen = True
> andersen frequency = 10
> barostat = True
> barostat frequency = 25
> center of mass frequency = 10
> Equilibration protocol
>
> minimise = True
> Output control
>
> save coordinates = True
> buffered coordinates frequency = 1000
> energy frequency = 100
>
> Run the above file using:
>
> ./sommmd.sh
>
> Details of error:
>
> ### Running Molecular Dynamics simulation on unknown ###
> ###================Setting up calculation=====================###
> New run. Loading input and creating restart
> Creating the system...
> Creating force fields...
> Setting up the simulation with random seed 557910
> Setting up moves...
> Traceback (most recent call last):
>   File "/home/lisa/sire.app/share/Sire/scripts/somd.py", line 119, in <module>
>     OpenMMMD.run(params)
>   File "/home/lisa/sire.app/lib/python3.4/site-packages/Sire/Tools/__init__.py", line 140, in inner
>     retval = func()
>   File "/home/lisa/sire.app/lib/python3.4/site-packages/Sire/Tools/OpenMMMD.py", line 1295, in run
>     moves = setupMoves(system, ranseed, gpu.val)
>   File "/home/lisa/sire.app/lib/python3.4/site-packages/Sire/Tools/OpenMMMD.py", line 433, in setupMoves
>     Integrator_OpenMM = OpenMMMDIntegrator(molecules)
> Boost.Python.ArgumentError: Python argument types in
>     OpenMMMDIntegrator.__init__(OpenMMMDIntegrator, MoleculeGroup)
> did not match C++ signature:
>     __init__(_object*)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/70>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
@jmichel80 I actually suggested github, since I am more likely to read this than google groups. 
She installed the latest dev version of Sire a week ago or so and the sommmd.sh file is just:
```
~/sire.app/bin/somd -C config.cfg --platfrom CPU
```
This might be a CPU GPU problem and I wanted to have a look at this. 
I'll look into it, it was just for me to have a reminder of the problem.
