### ISSUE TITLE
compile_sire.sh install problem

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#71]
Hi, 

I'm trying to do a fresh instal of sire on a Ubuntu 14.04 32 bit VM

julien@ubuntu:~/software/devel/sire$ ./compile_sire.sh 
Where would you like to install Sire? [/home/julien/sire.app]: 
Installing into directory '/home/julien/sire.app'
Downloading miniconda from http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh...
--2015-11-10 08:28:33--  http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 23.21.145.66, 23.23.112.241, 54.83.3.29, ...
Connecting to repo.continuum.io (repo.continuum.io)|23.21.145.66|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 29010771 (28M) [application/octet-stream]
Saving to: ‘build/miniconda.sh’
100%[=====================================================================================================================================================>] 29,010,771  7.78MB/s   in 3.6s   
2015-11-10 08:28:36 (7.78 MB/s) - ‘build/miniconda.sh’ saved [29010771/29010771]
Unpacking miniconda into /home/julien/sire.app...
WARNING:
    Your operating system appears not to be 64-bit, but you are trying to
    install a 64-bit version of Miniconda3.
    Are sure you want to continue the installation? [yes|no]
================

Is there a reason why we should support only 64-bit OS? 
If so, shouldn't we modify the compile_sire.sh script to complain if it is run on a 32 bit OS ?

**Comment by ppxasjsm** [comment]
There certainly is a miniconda 32 bit installer available:
http://conda.pydata.org/miniconda.html

I guess this would have to be added to the super awesome install script that it would grab either version depending on the computer architecture.

**Comment by jmichel80** [comment]
I switched to a 64 bit image to carry on. 

I believe the files README.rst and INSTALL.rst should be updated with the new installation instructions. 

I have also noted that to start running compile_sire.sh I needed to install 

sudo-apt get install git
sudo-apt get install cmake
sudo apt-get install g++

Arguably I cannot even checkout the source without installing git...but it might be good to be absolutely explicit on what must be available on the system and how it can installed quickly for say ubuntu. 

This for the sake of aiming for the 'must work under 5 minutes' rule...

**Comment by ppxasjsm** [comment]
only that the install will take more than 5 minutes....

**Comment by jmichel80** [comment]
Here is a good one. 
I typed ./compire-sire.sh 1> compile.log 2> compile.err 
because I wanted to launch remote compilation of my source on a cluster node. 
Then I realised this doesn't work since I didn't define $INSTALL_SIRE_DIR
So I cancelled this and then tried again but to no avail

julien@node009:~/software/devel/sire$ export INSTALL_SIRE_DIR=/home/julien/sire.app
julien@node009:~/software/devel/sire$ ./compile_sire.sh 1> compile.log 2> compile.err 
julien@node009:~/software/devel/sire$ cat compile.log 
Installing into directory '/home/julien/sire.app'
Unpacking miniconda into /home/julien/sire.app...
** FATAL **
** Cannot find /home/julien/sire.app/bin/python **
** Something went wrong with the miniconda install! **

julien@node009:~/software/devel/sire$ rm build/miniconda.sh 
julien@node009:~/software/devel/sire$ ./compile_sire.sh 1> compile.log 2> compile.err 

Does work....

Ok maybe it was my fault.

**Comment by chryswoods** [comment]
No, there isn't a reason that we should only support 64bit. I will take a look at the installer and will add a 32bit/64bit test.

The "working under 5 minutes" rule applies to the binaries. You need to download and install a binary and have that working in less than 5 minutes (not that this would excuse making it hard to compile from source). I agree that we should be clear that compilation depends on git, gcc/clang and cmake, and just say that these have to be installed before starting compilation. Anyone wanting to compile from source should be able to understand this...

Then, we must really push to get the 15.1 binaries out. I have mostly created the new website and am just tweaking the design and colours. I will share it with you for evaluation soon (probably after next week when I have my interview). I think that all of the showstopper bugs have been fixed, so we just need to finish tidying up the test cases, add a few more for completeness, and then package up some binaries ;-)

**Comment by jmichel80** [comment]
I agree that compilation doesn't have to be necessarily quick. 
I don't know how much work needs to go in making the compilation script idiot proof. 
I had a spectacular moment yesterday. I checked out sire in ~/software/sire and compiled from there initially. I then decided it would be better to have the sources in ~/software/devel/sire so i moved them. 
Then I wanted to recompile after some code changes. 
It wasn't instantly obvious whether I should run again ./compile-sire.sh or if I should cd build/corelib ; make install ; cd ../wrapper ; make install

In any event this didn't work out for me because all the CMake files were then pointing to ~/software/sire. I tried deleting CMakeCache.txt but there were still a lot of nested Makefiles so in the end I just re-installed from scratch, starting with the sources in ~/software/devel/sire

This requires manually deleting some, but not all, files in ~/software/devel/sire/build/

I'm sharing my experience in details so we think how to update the documentation to deal with future idiots (future me could be particularly ingenious...). 

I believe we have dealt with all the bugs that were bothering me for 15.1 
Antonia, can you comment on any other code changes needed in somd  & somd-freenrg ? 


We talked about moving the nautilus tests in a separate sire tests repository. 

We should also have single point energy calculations: 

- all the vacuum single point energy calculations for the test Chris and I used to debug the ImproperID bug.
- single point energy calculations for a solvated protein-ligand complex (Antonia can you provide one case?)
- single point energy calculations for a ligand in water (Antonia)

We should also have a few somd free energy calculation tests as well. I suggest:
  
- ethane to methanol in vacuum (all windows)
- ethane to methanol in water (one window, run long enough to converge free energy changes to a good precision)

Anything else? 

Chris, should you go ahead and create a new github project to store the tests?

**Comment by chryswoods** [comment]
Yes, I've created a new github project (https://github.com/chryswoods/SireTests). Please feel free to fork and then we will merge using pull requests. I do not know how to add teams to GitHub yet...

I think that you are right that the compilation script does need a "cleanup" to "refresh" option that will completely clean out the build directory in case of moves or other changes. I do want to keep it as simple as possible though, as it should be very easy for someone to work out which commands are being run. Perhaps I just need to get it to print out the commands used as they are going?

**Comment by jmichel80** [comment]
Sent from my iPhone

> On 12 Nov 2015, at 14:09, Christopher Woods <notifications@github.com> wrote:
> 
> Yes, I've created a new github project (https://github.com/chryswoods/SireTests). Please feel free to fork and then we will merge using pull requests. I do not know how to add teams to GitHub yet...
> 
> I think that you are right that the compilation script does need a "cleanup" to "refresh" option that will completely clean out the build directory in case of moves or other changes. I do want to keep it as simple as possible though, as it should be very easy for someone to work out which commands are being run. Perhaps I just need to get it to print out the commands used as they are going?
> 

Yes this sounds like a good easy improvement.

**Comment by chryswoods** [comment]
I've updated compile_sire.sh to do all of the above (print out the commands run, add an option to clean the entire build directory, add in automatic detection of 32bit and 64bit miniconda etc.).

I have also set a MINICONDA_VERSION variable that is set to 3.9.1. Change this to "latest" for the latest miniconda. I think we should stick to a particular miniconda for each Sire release, and only update it when we know it compiles and passes unit tests. It is too dangerous to use miniconda-latest for most users.

Please could you look at compile_sire.sh and let me know what you think. It is important that the three of us fully understand this script as it is the most crucial to get easy compilation working.

**Comment by chryswoods** [comment]
Interesting - the travis auto build of my commit fails with the same error that @Steboss  was seeing, i.e. everything compiles ok, but the tests run at the end of compile fail. This is perhaps an issue with miniconda 3.9.1. I will debug it to work out what is wrong...

**Comment by chryswoods** [comment]
The compile on my Mac has just finished (which shows how long it takes...) and I get the same error as on travis. I've disabled the error and made it print out more information so that we can debug, as inspection of the Sire installation shows that it is working and the error message is false.

**Comment by chryswoods** [comment]
The error output from travis shows that this is a problem with the libm library, e.g.

"Something went wrong when trying to test the Sire installation.
/home/travis/sire.app/bin/../lib/libm.so.6: version `GLIBC_2.15' not found (required by /home/travis/sire.app/bin/../lib/libSireMaths.so.2015)"

This is weird, as libm.so.6 is not present in the final install, and is not used when Sire is run normally. It seems to only be an issue when run within the build script, so I will close this issue and park it for a day when I have time to track down obscure, but potentially interesting, library path bugs. I will leave my "fix" in for now, which disables the test if it detects a problem and will monitor things as we move to more install hosts.
