### ISSUE TITLE
New Website - Request for images

### ISSUE THREAD

**Issue by chryswoods** [michellab/Sire#72]
Hi Everyone :-). I am putting the finishing touches to the new Sire website (no sneak peeks yet as I don't want to ruin the surprise). As part of the refresh I would like to showcase a range of images from simulations that were run using Sire. These will be used as backdrops to the main navigation buttons, e.g. as in <http://chryswoods.com/main/courses.html>.

Please email me any and all images that you have, and that you would like included. If you want, I can provide credit, and also add some text describing the image (e.g. add some detail about where the image comes from, what it shows, and links to a paper or talk). You don't need to add any extra data if you don't want to - I just want as many images as I can get.

Thanks for your help,

  Christopher

p.s. Once I have enough images I will showcase the new website at http://siremol.org/new-website, and will then ask you all for comments.

**Comment by ppxasjsm** [comment]
How is this coming along? Did Gaetano get back to you with some stuff?

**Comment by chryswoods** [comment]
Julien sent me some images in a powerpoint. The resolution was ok, but it would be nice to have some that have a higher resolution.

**Comment by ppxasjsm** [comment]
Ok. I'll see if I can generate something in the next few days.
