### ISSUE TITLE
Editing Parameter() data and re-using forcefields setup code

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#73]
Hi, 

I am working on a tool that requires I setup two systems that only differ in the cutoff values used.
One way to implement this would be to write the code below:

     from Sire.Tools.OpenMMMD import *
     from Sire.Tools import Parameter, resolveParameters
     (...)
    amber = Amber()
    (molecules, space) = amber.readCrdTop(crdfile.val, topfile.val)
    system = createSystemFreeEnergy(molecules)
    cutoff_dist.val = 10 * angstrom
    system_shortc = setupForceFieldsFreeEnergy(system, space)
    cutoff_dist.val = 14 * angstrom
    system_longc = setupForceFieldsFreeEnergy(system, space)

    This code doesn't work for two reasons:

*
   (Pdb) cutoff_dist.val = 14 * angstrom
    *** AttributeError: can't set attribute

    Is it impossible to edit the values of Parameter objects after they have been resolved?

*
(Pdb) system_shortc = setupForceFieldsFreeEnergy(system, space)
Creating force fields... 
(Pdb) system_longc = setupForceFieldsFreeEnergy(system, space)
Creating force fields... 
*** UserWarning: Exception 'SireFF::duplicate_forcefield' thrown by the thread 'master:main'.
Cannot have two forcefields in the same set that both have the same name! (solute_intraff, {2c9d2d15-b46d-4b20-8cc6-f979c60acb71} version 2 vs. {302218a1-5455-4ce6-9e36-dd646d72742b} version 3)

setupForceFieldsFreeEnergy comes straight from OpenMMMD and I'm hoping to reuse the code. But it looks like this doesn't work because the names of the force fields defined in the subroutine are hardcoded.

I think that I could fix these issues by writing a custom setupForceFields subroutine. This subroutine would
- take cutoff parameters as keywords arguments so I can easily pass a value that does not come from Parameter("cutoff_dist")
- build force fields with cutoff specific names to avoid name clashes

Before I do that I'm wondering 
- if what I'm proposing is likely to work
- if there isn't a better way to reuse existing code. I will likely need a bit of time to make sure that a new setupForceFields subroutine works correctly.

Best wishes,

Julien

**Comment by jmichel80** [comment]
Ok I have realised that the forcefields error was because my systems were pointers to the same system. I have changed a bit the code, but have stumbled onto another issue

    system_shortc = System()
    system_shortc.copy(system)
    system_shortc = setupLJFF(system_shortc, space, \
                              cutoff=cutoff_dist.val)

And in setupLJFF...

def setupLJFF(system, space, cutoff=10* angstrom):

     (...)
    solvent = system[MGName("solvent")]

    #Solvent intramolecular LJ energy
    solvent_intralj = IntraLJFF("solvent_intralj")
    solvent_intralj.add(solvent)

    This code fails with the following error


### Running LJ tail correction calculation on unknown ###
lambda is 0.0
Create the System...
Selecting dummy groups
Traceback (most recent call last):
  File "/home/julien/sire.app/share/Sire/scripts/somd-lj-tailcorrection.py", line 124, in <module>
    LJcutoff.runLambda(params)
  File "/home/julien/sire.app/lib/python3.5/site-packages/Sire/Tools/__init__.py", line 140, in inner
    retval = func()
  File "/home/julien/sire.app/lib/python3.5/site-packages/Sire/Tools/LJcutoff.py", line 95, in runLambda
    cutoff=cutoff_dist.val)
  File "/home/julien/sire.app/lib/python3.5/site-packages/Sire/Tools/LJcutoff.py", line 29, in setupLJFF
    solvent_intralj.add(solvent)
UserWarning: Exception 'SireError::invalid_cast' thrown by the thread 'master:main'.
Cannot cast from an object of class "SireMM::CLJNBPairs" to an object of class "SireMM::LJNBPairs".
Thrown from FILE: /home/julien/software/devel/sire/corelib/src/libs/SireBase/property.cpp, LINE: 120, FUNCTION: void SireBase::Property::throwInvalidCast(const char*) const


I'm surprise we cannot cast CLJNBPairs to LJNBPairs. The problem likely comes from the molecule property "intrascale" that was set by the amber topology parser.

A workaround for me would be to set all charges to 0 and to carry on using CLJ forcefields regardless. But is there a way to simply use a LJ force field? This sounds like the most natural solution.

**Comment by chryswoods** [comment]
Are you able to use ff.components().lj() rather than ff.components().total() when you create the energy expression? This will allow you to continue to use a cljff without needing to set the charges to 0. You can also use components().lj() for the intramolecular energy too. Sire will only calculate what you need from the energy expression, so cliff.energy( cljff.components().lj() ) will only calculate the LJ energy, and will not even attempt to calculate the coulomb energy (so should be very quick).

**Comment by jmichel80** [comment]
Nice ! Yes that seems to work.

**Comment by chryswoods** [comment]
Excellent :-). Sounds like one thing to add to the TODO is a tutorial on how to use components of a forcefield ;-)
