### ISSUE TITLE
Reading units from the command line

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#74]
Units are correctly parsed only if read from a config file.
The command line UI needs modifications in order to pass command line arguments with units. 

e.g. to make this work
~/sire.app/bin/somd-lj-tailcorrection -C ../sim.cfg -b "0.5 \* gram/(centimeter_centimeter_centimeter)"

I needed to modify python/scripts/somd-lj-tailcorrection.py to insert

(...)
from Sire.Units import *
(...)
if args.bulk_rho:
    exec("bulk_rho = %s" % args.bulk_rho, globals())
    params["bulk_rho"] = bulk_rho

This is not a big deal, but I'd like to raise an issue so we can all think how to consistently handle this situation across various apps.

**Comment by chryswoods** [comment]
Thanks. This also would be an easy fix (along the lines you suggest, using an "exec" on each argument, but placing that exec code into the Parameter constructor). Could you add this to the TODO document?

**Comment by chryswoods** [comment]
I've made the fix and committed to devel. The parser will now automatically parse options that are passed via the command line and also the config file. The parser is also now more intelligent, and will automatically add '*' if it is a number with a unit, i.e.

distance = 5 angstrom

should now work.
