### ISSUE TITLE
compile_sire.sh error

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#75]
Hi, 

I've just done a fresh compile of sire on a new system running ubuntu 14.04

./compile_sire.sh
(...)
force copying files from /home/julien/sire.app/pkgs/sire-2015.0.0/share/Sire to /home/julien/sire.app/share/Sire
Something went wrong when trying to test the Sire installation.
/home/julien/sire.app/bin/../lib/libm.so.6: version `GLIBC_2.15' not found (required by /home/julien/sire.app/bin/../lib/libSireMaths.so.2015)
Please check things manually yourself...
# 

Congratulations. Everything has installed :-)

julien@mechagodzilla:~$ ~/sire.app/bin/somd-freenrg 
/home/julien/sire.app/bin/somd-freenrg: /home/julien/sire.app/bin/../lib/./libm.so.6: version `GLIBC_2.15' not found (required by /home/julien/sire.app/bin/../lib/./libSireMaths.so.2015)

Any idea what packages I should install ?

**Comment by chryswoods** [comment]
Ahhh - this is related to issue 71. For some reason the install is pulling in a new maths library into sire.app/lib/libm.so.6. This libm.so.6 is compiled against a too new version of GLIBC, which causes a runtime error. This caused an issue when compiling and running the initial tests, but not for subsequent runs (as subsequent runs correctly used libm.so.6 from /usr/lib. Could you delete the libm.so.6 from sire.app/lib and let me know what happens?

The fix is not to install more packages, but for us to work out why libm.so.6 is being installed during the compile (I think it is put there either by miniconda or when conda installing another package).

**Comment by jmichel80** [comment]
Deleting libm.so.6 seems to fix the issue. See the transcript below.  I have also listed all the packages installed by conda so far.

julien@mechagodzilla:~/sire.app/lib$ ll libm.*
lrwxrwxrwx 1 julien julien 11 Nov 24 16:23 libm.so -> libm-2.5.so*
lrwxrwxrwx 1 julien julien 11 Nov 24 16:23 libm.so.6 -> libm-2.5.so*
julien@mechagodzilla:~/sire.app/lib$ mkdir temp
julien@mechagodzilla:~/sire.app/lib$ mv libm.* temp
julien@mechagodzilla:~/sire.app/lib$ ~/sire.app/bin/somd-freenrg 
"/home/julien/sire.app/share/Sire/scripts/somd-freenrg.py" 
Starting /home/julien/sire.app/bin/somd-freenrg: number of threads equals 16
Traceback (most recent call last):
  File "/home/julien/sire.app/share/Sire/scripts/somd-freenrg.py", line 2, in <module>
    from Sire.Tools import OpenMMMD
  File "/home/julien/sire.app/lib/python3.4/site-packages/Sire/Tools/OpenMMMD.py", line 41, in <module>
    import numpy as np
ImportError: No module named 'numpy'
julien@mechagodzilla:~/sire.app/lib$ ~/sire.app/bin/conda install numpy
Fetching package metadata: ......
Solving package specifications: ....................
Package plan for installation in environment /home/julien/sire.app:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgfortran-1.0            |                0         170 KB  defaults
    openblas-0.2.14            |                3         3.5 MB  defaults
    numpy-1.10.1               |           py34_0         5.8 MB  defaults
    ------------------------------------------------------------
                                           Total:         9.4 MB

The following NEW packages will be INSTALLED:

    libgfortran: 1.0-0         defaults
    numpy:       1.10.1-py34_0 defaults
    openblas:    0.2.14-3      defaults

Proceed ([y]/n)? Y

Fetching packages ...
libgfortran-1. 100% |#########################################################################################################################################################| Time: 0:00:00 396.64 kB/s
openblas-0.2.1 100% |#########################################################################################################################################################| Time: 0:00:01   2.03 MB/s
numpy-1.10.1-p 100% |#########################################################################################################################################################| Time: 0:00:02   3.04 MB/s
Extracting packages ...
[      COMPLETE      ]|############################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|############################################################################################################################################################################| 100%
julien@mechagodzilla:~/sire.app/lib$ ~/sire.app/bin/somd-freenrg 
"/home/julien/sire.app/share/Sire/scripts/somd-freenrg.py" 
Starting /home/julien/sire.app/bin/somd-freenrg: number of threads equals 16

usage: somd-freenrg [-h] [-C [CONFIG]] [-H] [--author] [--version]
                    [-t [TOPOLOGY_FILE]] [-c [COORDINATE_FILE]]
                    [-m [MORPH_FILE]] [-d [DEVICE]] [-n [NMOVES]]
                    [-p [PLATFORM]] [-l [LAMBDA_VAL]]

Perform molecular dynamics single topology free energy calculations using
OpenMM

optional arguments:
  -h, --help            show this help message and exit
  -C [CONFIG], --config [CONFIG]
                        Supply an optional CONFIG file to control the
                        calculation.
  -H, --help-config     Get additional help regarding all of the parameters
                        (and their default values) that can be set in the
                        optionally-supplied CONFIG file
  --author              Get information about the authors of this script.
  --version             Get version information about this script.
  -t [TOPOLOGY_FILE], --topology_file [TOPOLOGY_FILE]
                        The Amber topology file containing the system.
  -c [COORDINATE_FILE], --coordinate_file [COORDINATE_FILE]
                        The Amber coordinate file giving the coordinates of
                        all of the atoms in the passed topology file.
  -m [MORPH_FILE], --morph_file [MORPH_FILE]
                        The morph file describing the single topology
                        calculation to be performed.
  -d [DEVICE], --device [DEVICE]
                        The device ID of the GPU on which you want to run the
                        simulation.
  -n [NMOVES], --nmoves [NMOVES]
                        The number of Molecular Dynamics moves you want to
                        run.
  -p [PLATFORM], --platform [PLATFORM]
                        The OpenMM platform on which you want to run the
                        simulation.
  -l [LAMBDA_VAL], --lambda_val [LAMBDA_VAL]
                        The lambda value at which you want to run the
                        simulation.

somd-freenrg is built using Sire and OpenMM and is distributed under the GPL.
For more information please visit http://siremol.org

Please supply the name of an existing topology, coordinate and morph file.
(cannot find coordinate file system.crd)
(cannot find topology file system.top)
(cannot find morph file system.morph)


julien@mechagodzilla:~/sire.app/lib$ ~/sire.app/bin/conda list
# packages in environment at /home/julien/sire.app:
#
conda                     3.18.6                   py34_0    http://repo.continuum.io/pkgs/free/linux-64/conda-3.18.6-py34_0.tar.bz2
conda-env                 2.4.4                    py34_0    http://repo.continuum.io/pkgs/free/linux-64/conda-env-2.4.4-py34_0.tar.bz2
decorator                 4.0.4                    py34_0    defaults
fftw3f                    3.3.4                         2    http://conda.binstar.org/omnia/linux-64/fftw3f-3.3.4-2.tar.bz2
ipython                   4.0.0                    py34_0    defaults
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py34_0    defaults
libgfortran               1.0                           0    defaults
nose                      1.3.7                    py34_0    defaults
numpy                     1.10.1                   py34_0    defaults
openblas                  0.2.14                        3    defaults
openmm                    6.3                      py34_1    http://conda.binstar.org/omnia/linux-64/openmm-6.3-py34_1.tar.bz2
openssl                   1.0.2d                        0    http://repo.continuum.io/pkgs/free/linux-64/openssl-1.0.2d-0.tar.bz2
path.py                   8.1.2                    py34_0    defaults
pexpect                   3.3                      py34_0    defaults
pickleshare               0.5                      py34_0    defaults
pip                       7.1.2                    py34_0    http://repo.continuum.io/pkgs/free/linux-64/pip-7.1.2-py34_0.tar.bz2
pycosat                   0.6.1                    py34_0    <unknown>
python                    3.4.3                         2    http://repo.continuum.io/pkgs/free/linux-64/python-3.4.3-2.tar.bz2
pyyaml                    3.11                     py34_1    http://repo.continuum.io/pkgs/free/linux-64/pyyaml-3.11-py34_1.tar.bz2
readline                  6.2                           2    <unknown>
requests                  2.8.1                    py34_0    http://repo.continuum.io/pkgs/free/linux-64/requests-2.8.1-py34_0.tar.bz2
setuptools                18.5                     py34_0    http://repo.continuum.io/pkgs/free/linux-64/setuptools-18.5-py34_0.tar.bz2
simplegeneric             0.8.1                    py34_0    defaults
sqlite                    3.8.4.1                       1    http://repo.continuum.io/pkgs/free/linux-64/sqlite-3.8.4.1-1.tar.bz2
system                    5.8                           1    <unknown>
tk                        8.5.18                        0    http://repo.continuum.io/pkgs/free/linux-64/tk-8.5.18-0.tar.bz2
traitlets                 4.0.0                    py34_0    defaults
wheel                     0.26.0                   py34_1    http://repo.continuum.io/pkgs/free/linux-64/wheel-0.26.0-py34_1.tar.bz2
xz                        5.0.5                         0    <unknown>
yaml                      0.1.6                         0    http://repo.continuum.io/pkgs/free/linux-64/yaml-0.1.6-0.tar.bz2
zlib                      1.2.8                         0    <unknown>

**Comment by chryswoods** [comment]
Thanks - very useful to know. I will move the "mysterious case of an appearing libm.so.6" from being something I will debug later, to something I will look at next week. I think that this needs fixing before we ship 2015.1. I hope the fix is not me adding a "rm lib/libm.so*" to the end of compile_sire.sh.... ;-)

The weird thing about this is that on travis and on my mac the libm.so.6 only exists during compilation, but mysteriously vanishes at installation. Definitely one of the most puzzling things I have come across.
