### ISSUE TITLE
Manipulating units

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#76]
Is there a way to compute the power or square root of a GeneralUnit ? 

e.g. 

(Pdb) epsilon
0.152 kcal mol-1
(Pdb) epsilon.what()
'SireUnits::Dimension::MolarEnergy'
(Pdb) epsilon_epsilon
0.023104 M^2 L^4 T-4 Q-2
(Pdb) epsilon__2
*_\* TypeError: unsupported operand type(s) for *\* or pow(): 'GeneralUnit' and 'int'
(Pdb) sqrt(epsilon_epsilon)
*_\* Boost.Python.ArgumentError: Python argument types in
    Sire.CAS._CAS.sqrt(GeneralUnit)
did not match C++ signature:
    sqrt(SireCAS::Expression ex0)

**Comment by chryswoods** [comment]
No, not yet. It would be relatively simple code to write. Could you create a TODO document and add this as a wish list item.

**Comment by jmichel80** [comment]
I will compile a list of comments. In general I find it difficult to use SireUnits because some mathematical operations can be performed on units, but other operations must operate on floats. Since it is often unclear what can/cannot be done I tend to end up writing python scripts where I start using SireUnits, then drop them (using .value()), carry on and then multiply the final result by the desired unit. This means that the benefits of automated units conversion are largely lost.

**Comment by chryswoods** [comment]
I agree that this is annoying. SireUnits has a lot of functionality in C++ that was challenging to expose to Python. In C++ it uses template metaprogramming to achieve most of what we want. However, in Python, all of this had to be converted to GeneralUnit, which only exists in the Python wrapper. I agree that this is not great, and admit to also doing most of the work using .value() and then adding the units at the end...

Could you compile a list of mathematical operations that you would want to support and we will make this the priority for 2016.1?

**Comment by jmichel80** [comment]
On Wednesday, November 25, 2015, Christopher Woods <notifications@github.com>
wrote:

> I agree that this is annoying. SireUnits has a lot of functionality in C++
> that was challenging to expose to Python. In C++ it uses template
> metaprogramming to achieve most of what we want. However, in Python, all of
> this had to be converted to GeneralUnit, which only exists in the Python
> wrapper. I agree that this is not great, and admit to also doing most of
> the work using .value() and then adding the units at the end...
>
> Could you compile a list of mathematical operations that you would want to
> support and we will make this the priority for 2016.1?
>

I will do that before we meet next week.
 I'm also wondering whether it may be possible to convert Sire C++ units to
OpenMM units in the python layer. This could save time and help improve the
compatibility of the two pieces of code.




-- 
--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by chryswoods** [comment]
I have added this request to the roadmap
