### ISSUE TITLE
Meaning of error estimate in SireMaths::FreeEnergyAverage

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#77]
Hi, 

So it is possible to use the Zwanzing equation with  code like:   

deltaG= FreeEnergyAverage(temperature.val)
for delta_nrg in delta_nrgs:
    deltaG.accumulate(delta_nrg.value())

print(deltaG)
FreeEnergyAverage( dG = -20.403 kcal mol-1, average = -20.3971 kcal mol-1 stderr = 0.0842614 kcal mol-1, skew = -6.50389 kcal mol-1, nSamples = 20, isForwardsFreeEnergy() = 1 )

Couple of points
There is no deltaG.stderr() method. 
Rather digging through the code suggests that what is listed as stderr in the .toString() method is actually

histogram().standardDeviation())

Looking at SireMaths::histogram this seems to be the true standard deviation of the full set of accumulated  delta_nrg values.

So does this mean what is listed as the stderr estimate of the *free energy difference* is actually the stdev estimate of the distribution of *energy difference* values ?  
This doesn't sound correct to me. FreeEnergyAverage.toString should write in the generated string 'stdev', assuming this can be safely considered the standard deviation of the free energy estimate. 

Could a better error estimate for the free energy be produced by bootstrapping?

**Comment by chryswoods** [comment]
Yes. This is a bug. I've just pushed a fix to change the print out from stderr to stdev.

I agree that we could do a better job of estimating the error. The toString() just prints out a summary of everything recorded. I built the histogram and associated classes in the hope that it would help us collect more data from the simulation and thus be able to write better error estimators.

On this subject, I have found that simultaneously calculating FEP, FDTI and BAR does give a reasonable estimate of the error, or at least signal that things have converged. BAR gets the right value first, with FDTI not too far behind. Once FEP is close I know that the average is pretty good.
