### ISSUE TITLE
somd-freenrg does not run after a fresh install of sire/devel

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#78]
Hi, 

The problem is that OpenMMMD.py should check whether numpy has been installed before attempting to run. If not the code should stop and issue a useful error message. e.g.

try:
    import numpy as np
except ImportError:
    raise "somd depends on a working install of the python module numpy. Please install numpy in your sire python using the command ~/sire.app/bin/conda install numpy"
    sys.exit(-1)

OR we could even have the script attempt to run the conda install automatically.

**Comment by ppxasjsm** [comment]
yeah the analysis script does that already. I'll change that!

**Comment by ppxasjsm** [comment]
Done
