### ISSUE TITLE
dcd_writer.h and dcd_writer.cpp 

### ISSUE THREAD

**Issue by ggerogiokas** [michellab/Sire#8]
Hi, just noticed that dcd_writer.h and dcd_writer.cpp is under both the openmm dependent and 
openmm independent cmake lists.

Thanks,
George

**Comment by jmichel80** [comment]
I believe this code is no longer used in any of the sire openmm subroutines and could be removed from the make files. 
Antonia) Could you check whether it is indeed possible to remove dcd_writer when you tidy up the code?

**Comment by ppxasjsm** [comment]
I'll have a look tomorrow.

**Comment by nividic** [comment]
I was developing that part of the code. Actually you can remove that files without problems. 
GAC
