### ISSUE TITLE
Gradients calculation

### ISSUE THREAD

**Issue by Steboss** [michellab/Sire#80]
Hi all,

There's an issue in the way  the actual gradients are calculated and printed out both in gradients.dat and gradients.s3
Comparison made on ethane to methanol between  Sire 15.1 and a version of Sire around April/May 2015 gives different results
In particular using both analyse_freenrg and analysse_freenrg_mbar the TI estimates is enormously wrong
Using analyse_freenrg on a Sire April/May 2015 instead gives the right results.

Checking through openmmfreenrgst.cpp, around line 3518, we have modified the calculation on the actual gradients, giving it as a finite difference between perturbed potential energy:
```
gradient = (potential_energy_lambda_plus_delta-potential_energy_lambda_minus_delta)/double_increment;
```

There's nothing wrong, but once we integrate this function the result is totally wrong

Should we save it only as : 
```
backward_m = exp(-beta * (potential_energy_lambda_minus_delta - p_energy_lambda));
forward_m = exp(-beta * (potential_energy_lambda_plus_delta - p_energy_lambda));
gradient = forward_m - backward_m
```

Even if we should not get a huge error using finite difference on potential energies

**Comment by ppxasjsm** [comment]
Mhh I think this was the result of a discussion on how best save gradients. It may well be the case that analyse_freenrg is broken. I don't see how analyse_freenrg_mbar gives wrong results. They are consistent within each other and give expected results for ethane -> methanol.

**Comment by ppxasjsm** [comment]
Can you give me info where I can find your data to have a look at what you were doing?

**Comment by Steboss** [comment]
Hi Toni

the simulations are on the cluster  at: /home/steboss/projects/SAMPL/reference/
There you find:
ethane ~ methanol : simulation run with dev_sire 
ethane ~ methanol_oldsire : simulation run with my own sire, installed locally

methanol : absolute free energy  with dev_sire
mehtanol_oldsire:  absolute with my Sire 

I remember we spoke about too
It's rather strange, but all the simulations I run so far, analysed with analyse_freenrg give wrong results

**Comment by Steboss** [comment]
I think the TI free energy that we get is divided by k_BT 0.593 kcal/mol 
maybe we have dimensionless potential in gradients.dat and .s3

**Comment by ppxasjsm** [comment]
It is not a maybe but they are dimensionless!

**Comment by Steboss** [comment]
OK
So found out where is the problem
We just have to print them out as kcal/mol

**Comment by ppxasjsm** [comment]
Stefano, everything has been resolved here right? It is just a unit issue? So I can close the issue?

**Comment by Steboss** [comment]
Yeah, we can close it
