### ISSUE TITLE
integration of analyse_freenrg_mbar and analyse_freenrg

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#81]
Before 2015.1 is released we should merge these two apps together such that users  will run:

analyse_freenrg 

and obtain FEP, TI, BAR free energy estimates via Chris's code (if the required data is available)
and MBAR free energy estimates via Antonia's code  (if the required data is available).

This to avoid the future repeats of the recent debacle.

**Comment by jmichel80** [comment]
looks like I can't assign tasks to multiple developers ! Probably a bad idea anyway...

**Comment by ppxasjsm** [comment]
I think we had agreed at some point to move to MBAR and merge code later. analysis_freerng was used by other apps and there was the debate whether to implement MBAR in the C code. Maybe we can have a quick discussion about this tomorrow, to not make things worse.

**Comment by jmichel80** [comment]
Here is my view on the UI we should aim for 

Users should run 
~/sire.app/bin/analyse_free_nrg -l lambda-*/ 

The script should:

- automatically attempt a conda install of dependencies if missing some
- workout if there is data to do TI, FEP, BAR using code currently in analyse_free_nrg
- workout if there is the data needed to to MBAR using code currently in analyse_free_nrg_mbar
- workout temperature from the simulation data
- Use a consistent methodology to estimate uncertainties

Report the calculated free energies using
                          kcal/mol           kJ/mol       
FEP
TI
BAR
MBAR

We should then all use the same script for future analyses of any free energy data with Sire

**Comment by ppxasjsm** [comment]
fixed with commit 7e5e3074f445b2ecfa89289b89a26e91badad824.
