### ISSUE TITLE
somd-freenrg sometimes crash, possibly because of HMR

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#84]
Example available here:

julien@node009:~/projects/somd/SAMPL/reference/phenol/cyc/run001-short/vanish/output$ pwd
/home/julien/projects/somd/SAMPL/reference/phenol/cyc/run001-short/vanish/output

julien@node009:~/projects/somd/SAMPL/reference/phenol/cyc/run001-short/vanish/output$ cat somd-array-gpu-994.5.out 
CUDA DEVICES: 3
lambda is:  0.500
"/home/julien/sire.app/share/Sire/scripts/somd-freenrg.py" 
Reading topology file "../../input/SYSTEM.top" 
Reading coordinate file "../../input/SYSTEM.crd" 
Building 333 molecule(s)... 
 Getting space information  
Read space "PeriodicBox( ( 39.4548, 41.2483, 37.6316 ) )" 
...complete 

Loading configuration information from file ../../input/sim.cfg

 
Running a somd-freenrg calculation using files ../../input/SYSTEM.top, ../../input/SYSTEM.crd and ../../input/MORPH.pert.
Using parameters:
===============
andersen == True
barostat == True
buffered coordinates frequency == 500
center solute == True
constraint == allbonds
crdfile == ../../input/SYSTEM.crd
cutoff distance == 12 angstrom
cutoff type == cutoffperiodic
energy frequency == 100
equilibrate == True
equilibration iterations == 5000
hydrogen mass repartitioning factor == 4.0
lambda array == (0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 1.0)
lambda_val == 0.5
minimal coordinate saving == True
minimise == True
morphfile == ../../input/MORPH.pert
ncycles == 2
nmoves == 10000
platform == CUDA
precision == mixed
reaction field dielectric == 1.0
save coordinates == True
timestep == 0.004 ps
topfile == ../../input/SYSTEM.top
===============

### Running Single Topology Molecular Dynamics Free Energy on mechagodzilla ###
###================Setting up calculation=====================###
New run. Loading input and creating restart
lambda is 0.5
Create the System...
Selecting dummy groups
Applying Hydrogen Mass repartition to input using a factor of 4.0 
Creating force fields... 
Setting up the simulation with random seed 581323
Setting up moves...
Created a MD move that uses OpenMM for all molecules on 0 
Generated random seed number 581323 
Saving restart
Setting up sim file. 
There are 5989 atoms in the group 
###===========================================================###

###=======================Minimisation========================###
Running minimisation.
###===========================================================###

###======================Equilibration========================###
Running lambda equilibration to lambda=0.5.
Starting /home/julien/sire.app/bin//somd-freenrg: number of threads equals 16
Traceback (most recent call last):
  File "/home/julien/sire.app/share/Sire/scripts/somd-freenrg.py", line 142, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/home/julien/sire.app/lib/python3.4/site-packages/Sire/Tools/__init__.py", line 140, in inner
    retval = func()
  File "/home/julien/sire.app/lib/python3.4/site-packages/Sire/Tools/OpenMMMD.py", line 1510, in runFreeNrg
    system = integrator.annealSystemToLambda(system, equil_timestep.val, equil_iterations.val)
RuntimeError: The periodic box size has decreased to less than twice the nonbonded cutoff.
srun: error: mechagodzilla: task 0: Exited with exit code 1

--> We should add this system to our test cases to validate the somd minimisaton-equilibration-production workflow.

**Comment by jmichel80** [comment]
Quick update. I have tested changing constraints, HMR and the above example still fails. Disabling equilibration does make it work.

**Comment by ppxasjsm** [comment]
Yes that is exactly what I saw, when I was playing with the crashed files.
