### ISSUE TITLE
ipython/python

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#87]
I have observed something else very curious on my Mac installation:

if I start ```~/sire.app/bin/python``` and ```import Sire.Stream```, I don't have any problems and things seem to work fine.

On the other hand if I try and do ```~/sire.app/bin/ipython``` and ```import Sire.Stream```, I get the following error:

```  
dlopen(/Users/toni_brain/feat_sire.app/lib/python3.5/site-packages/Sire/Qt/_Qt.so, 2): Library not loaded: @rpath/libSireBase.2015.dylib
  Referenced from: /Users/toni_brain/feat_sire.app/lib/python3.5/site-packages/Sire/Qt/_Qt.so
  Reason: image not found
```

**Comment by ppxasjsm** [comment]
Same if I use ~/sire.app/bin/python.app

**Comment by ppxasjsm** [comment]
Just to confirm on Linux I don't get that problem

**Comment by chryswoods** [comment]
Interesting... I see this on my mac as well. Thanks for finding this. It is because ipython and python.app are pointing to a "hidden" python interpreter in sire.app/python.app/Contents/MacOS/python. I see this when I wrote the code that automatically fixed RPATH for python executables. I will add this to the list and will commit a fix when I have some time...

**Comment by chryswoods** [comment]
To give more info to help understand how this works, every executable on OS X has to be told where to find its libraries. This is set in the @RPATH for the executable, and is a path specified relative to the executable.

For example, if the executable is installed in somewhere/bin and its libraries are in somewhere/lib, then it should have an @RPATH that is @rpath/../lib (i.e. go up a directory and look in lib).

An executable can have many @RPATHS as its libraries can be in many directories. The file 

wrapper/bundled/install_python.cmake

is used when running cmake to find the python interpreter and to use "install_name_tool" on OS X to manually add the @RPATH for the Sire libraries. As this is only run on the python interpreter, it hasn't been run for the other Python binaries (such as the python binary in python.app/Contents/MacOS/python), and so they cannot find any Sire libraries.

The code in install_python.cmake to do this is;

```
  if (APPLE)
    # we have to make sure that the anaconda python library is called @rpath/libpython...
    # and that the anaconda python process has the correct executable path
    execute_process( COMMAND chmod u+w ${PYTHON_LIBRARY} )
    execute_process( COMMAND ${CMAKE_INSTALL_NAME_TOOL} -id "@rpath/libpython${PYTHON_VERSION}${PYTHON_ABIFLAGS}.dylib" ${PYTHON_LIBRARY} )
    execute_process( COMMAND ${CMAKE_INSTALL_NAME_TOOL} -add_rpath "@executable_path/../lib" ${PYTHON_EXECUTABLE} )
  endif()
```

I will now write a script that can be run by "build/build_sire.py" that will scan for Python binaries and will add the correct @RPATH using 'install_name_tool --add_rpath "@executable_path/../something" binary'.

**Comment by chryswoods** [comment]
Ok - I've now committed a fix that runs install_name_tool correctly. I ended up putting this in install_python.cmake so to keep everything together.

I also then had to update getInstallDir() in Sire.Base as this got very confused by the strange location of the python interpreter...
