### ISSUE TITLE
analyse_freenrg_mbar sometimes predicts extremely large error estimates

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#88]
Example here:

section6.chem.ed.ac.uk:/home/julien/projects/somd/SAMPL/dataset/SAMPL5_065_charged/wat/run001/vanish/output

julien@node009:~/projects/somd/SAMPL/dataset/SAMPL5_065_charged/wat/run001/vanish/output$ cat freenrg-MBAR.dat 
# Writing all output to file mbar.pmf

We are doing a timeseries analysis using the timeseries analysis module in pymbar and will subsample according to that.
We are doing a timeseries analysis using the timeseries analysis module in pymbar and will subsample according to that.
K (total states) = 12, total samples = 25368
N_k = 
[ 2114.  2114.  2114.  2114.  2114.  2114.  2114.  2114.  2114.  2114.
1.  2114.]
   There are 12 states with samples.
   Initializing free energies to zero.
   Initial dimensionless free energies with method zeros
   f_k = 
   [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
   Final dimensionless free energies
   f_k = 
   [  0.         -67.69832185 -67.49147366 -60.99669806 -57.68105356
   -61.82172384 -69.42765624 -72.25621116 -68.9760699  -63.71821926
   -61.39709311 -58.40205469]
   MBAR initialization complete.
   Free energy difference estimated with MBAR is: -34.584969 kcal/mol +/- 40.850858 kcal/mol
   Free energy difference estimated with MBAR is: -85.691513 kJ/mol +/- 170.919787 kJ/mol
   Free energy difference estimated with TI is: -71.775062 kcal/mol
   Starting /home/julien/sire.app/bin/analyse_freenrg_mbar: number of threads equals 16

But the output from an independent repeat shows
julien@node009:~/projects/somd/SAMPL/dataset/SAMPL5_065_charged/wat/run002/vanish/output$ cat freenrg-MBAR.dat 
# Writing all output to file mbar.pmf

We are doing a timeseries analysis using the timeseries analysis module in pymbar and will subsample according to that.
We are doing a timeseries analysis using the timeseries analysis module in pymbar and will subsample according to that.
K (total states) = 12, total samples = 23796
N_k = 
[ 1983.  1983.  1983.  1983.  1983.  1983.  1983.  1983.  1983.  1983.
1.  1983.]
   There are 12 states with samples.
   Initializing free energies to zero.
   Initial dimensionless free energies with method zeros
   f_k = 
   [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
   Final dimensionless free energies
   f_k = 
   [  0.         -70.56921376 -69.95123836 -61.91441143 -59.05646234
   -62.75560215 -70.96775346 -73.83026208 -70.53541284 -65.2620644
   -62.94129886 -59.94998875]
   MBAR initialization complete.
   Free energy difference estimated with MBAR is: -35.501636 kcal/mol +/- 816.266755 kcal/mol
   Free energy difference estimated with MBAR is: -87.962749 kJ/mol +/- 3415.256037 kJ/mol
   Free energy difference estimated with TI is: -72.641008 kcal/mol
   Starting /home/julien/sire.app/bin/analyse_freenrg_mbar: number of threads equals 16

The two MBAR results are within 1 kcal/mol from each other, much much better than what the crazy error estimates suggest.

**Comment by ppxasjsm** [comment]
Maybe this is due to a poor overlap in terms of energy at the different lambdas? I can look into this.

**Comment by jmichel80** [comment]
Possibly, but surprising. The calculations are clearly more reproducible than what the error estimates suggest. Yes please look into as it could also be a bug.
