### ISSUE TITLE
Compilation of Sire without openmm on openSUSE 12.2 (x86_64)

### ISSUE THREAD

**Issue by ggerogiokas** [michellab/Sire#9]
Hi,
Just posting all the compilations issues I had so far when compiling Sire without openmm on openSUSE 12.2 (x86_64):

First when compiling the corelib library in a folder called buildcorelib I get the following error after typing make install -j 7(after first configuring things in ccmake):
In file included from /usr/users/gerogiokas/Software/sire_nautilus/corelib/src/libs/SireMove/dcd_writer.cpp:1:0:
/usr/users/gerogiokas/Software/sire_nautilus/corelib/src/libs/SireMove/dcd_writer.h:3:45: fatal error: OpenMM.h: No such file or directory
compilation terminated.
make[2]: *** [src/libs/SireMove/CMakeFiles/SireMove.dir/dcd_writer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/libs/SireMove/CMakeFiles/SireMove.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX shared library libSireAnalysis.so
[ 81%] Built target SireAnalysis
make: *** [all] Error 2

I get around this issue by deleting the dcd_writer.cpp and dcd_writer.h in the SIREMOVE lists and left them in the SIREMOVE_OPENMM lists set in the cmake lists files in SireMove folder of the source.

Once I do that the compilation has trouble finding the bundled TBB libraries:
TBB_LIBRARY
    linked by target "SireMM" in directory /usr/users/gerogiokas/Software/sire_nautilus/corelib/src/libs/SireMM
TBB_MALLOC_LIBRARY
    linked by target "SireMM" in directory /usr/users/gerogiokas/Software/sire_nautilus/corelib/src/libs/SireMM

I set them using ccmake then corelib is compiled properly when I use make install -j 7.

I begin compiling the wrappers in the folder buildwrappers.  And get the following error:
make[2]: *** [Move/CMakeFiles/Move.dir/OpenMMIntegrator.pypp.cpp.o] Error 1
make[1]: *** [Move/CMakeFiles/Move.dir/all] Error 2
make: *** [all] Error 2

So, now it still thinks its trying to install openmm with it even though corelib compilation explictly 
had openmm turned off in ccmake.

I am now stuck here.

George

**Comment by jmichel80** [comment]
Hi George, 

Can you try this 

cd wrapper/Move
mkdir noopenmm
mv OpenMM* noOpenMM/
vim CMakeAutogenFile.txt
and remove all instances of OpenMM*

Then try again to compile the wrappers in your build folder. 

Please post an update if it worked.

**Comment by ggerogiokas** [comment]
Hi Julien,

If I do that I get:
Linking CXX shared library _Move.so
CMakeFiles/Move.dir/_Move.main.cpp.o: In function `init_module__Move()':
_Move.main.cpp:(.text+0xbb): undefined reference to `register_OpenMMAMDIntegrator_class()'
_Move.main.cpp:(.text+0xc0): undefined reference to `register_OpenMMFrEnergyDT_class()'
_Move.main.cpp:(.text+0xc5): undefined reference to `register_OpenMMFrEnergyST_class()'
_Move.main.cpp:(.text+0xca): undefined reference to `register_OpenMMIntegrator_class()'
_Move.main.cpp:(.text+0xcf): undefined reference to `register_OpenMMMDIntegrator_class()'
collect2: error: ld returned 1 exit status
make[2]: *** [Move/_Move.so.0.0.1] Error 1
make[1]: *** [Move/CMakeFiles/Move.dir/all] Error 2
make: *** [all] Error 2

George

**Comment by ggerogiokas** [comment]
Hi Julien,

I get the following error after doing that:
Scanning dependencies of target Move
[ 77%] Building CXX object Move/CMakeFiles/Move.dir/_Move.main.cpp.o
/usr/users/gerogiokas/Software/sire_nautilus/wrapper/Move/_Move.main.cpp:72:40: fatal error: OpenMMAMDIntegrator.pypp.hpp: No such file or directory
compilation terminated.
make[2]: *** [Move/CMakeFiles/Move.dir/_Move.main.cpp.o] Error 1
make[1]: *** [Move/CMakeFiles/Move.dir/all] Error 2
make: *** [all] Error 2

George

**Comment by ggerogiokas** [comment]
Hi Julien,

I removed all mention of openmm on _Move.main.cpp and it has compiled.

George

**Comment by jmichel80** [comment]
Hi George, 

The issue we have to fix is that the wrappers have been generated assuming openmm is present. Fixing this requires editing CMakeFiles and doing tests. In the meantime it's safer to install openmm and link sire to openmm rather than hack wrappers further.  While you could proceed with your hack this will cause problem when trying to merge new features from sire in your local copy. 

Julien
