### ISSUE TITLE
analyse_free_nrg_mbar gives widely different results when run with different command line options

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#90]
Using code as available on feature_ljtail

Example trajectory folder:
julien@node009:~/projects/somd/SAMPL/runs/minnesota-GAFFCM5-cyc/cyclohexane/cyc/run002/vanish/output$ pwd
/home/julien/projects/somd/SAMPL/runs/minnesota-GAFFCM5-cyc/cyclohexane/cyc/run002/vanish/output
- First call, ''default options'', gives MBAR 7.47 kcal/mol TI -2.2 (not kcal/mol)

julien@node009:~/projects/somd/SAMPL/runs/minnesota-GAFFCM5-cyc/cyclohexane/cyc/run002/vanish/output$ ~/sire.app/bin/analyse_freenrg_mbar -i lambda-0.000/simfile.dat lambda-0.100/simfile.dat lambda-0.200/simfile.dat lambda-0.300/simfile.dat lambda-0.400/simfile.dat lambda-0.500/simfile.dat lambda-0.600/simfile.dat lambda-0.700/simfile.dat lambda-0.800/simfile.dat lambda-0.900/simfile.dat lambda-0.950/simfile.dat lambda-1.000/simfile.dat --lam 0.000 0.100 0.200 0.300 0.400 0.500 0.600 0.700 0.800 0.900 0.950 1.000 --temperature 298.0 -o mbar.pmf --subsampling timeseries
"/users/julien/sire.app/share/Sire/scripts/analyse_freenrg_mbar.py" 
Starting /home/julien/sire.app/bin/analyse_freenrg_mbar: number of threads equals 16
# Writing all output to file mbar.pmf

We are doing a timeseries analysis using the timeseries analysis module in pymbar and will subsample according to that.
We are doing a timeseries analysis using the timeseries analysis module in pymbar and will subsample according to that.
/home/julien/sire.app/lib/python3.5/site-packages/pymbar/utils.py:70: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if N_k == None:
K (total states) = 12, total samples = 48
N_k = 
[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
There are 12 states with samples.
Initializing free energies to zero.
Initial dimensionless free energies with method zeros
f_k = 
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
/home/julien/sire.app/lib/python3.5/site-packages/scipy/optimize/minpack.py:236: RuntimeWarning: xtol=0.000000 is too small, no further improvement in the approximate
  solution is possible.
  warnings.warn(msg, RuntimeWarning)
Final dimensionless free energies
f_k = 
[  0.          -2.6018972    0.15882301   4.18072595   6.91998994
   8.19448186   9.06278165   9.46762391  10.41097006  11.56991839
  12.05615255  12.63082401]
MBAR initialization complete.
Free energy difference estimated with MBAR is: 7.479817 kcal/mol +/- 1.123100 kcal/mol
Free energy difference estimated with MBAR is: 18.532814 kJ/mol +/- 4.699046 kJ/mol
Free energy difference estimated with TI is: -2.194679 kcal/mol
- With --subsampling percentage --percentage 1 gives MBAR 0.80 kcal/mol TI 1.47 (reduced units?)
- With --subsampling percentage --percentage 10 MBAR gives -0.17 kcal/mol, TI -0.53 
- With --subsampling percentage --percentage 20 MBAR gives -0.49 kcal/mol, TI -1.00 
- With --subsampling percentage --percentage 50 MBAR gives -0.70 kcal/mol, TI -1.47 
- With --subsampling percentage --percentage 100 (amazed the code runs!) MBAR gives 0.27 kcal/mol, TI -0.33 (not kcal/mol I believe)
- For comparison analyse_free_nrg gives
  ~/sire.app/bin/analyse_freenrg -g lambda-*/gradients.s3 
  TI = 0.0 (quadrature 0.19) (don't think there are kcal/mol?)

My feeling is that the timeseries code doesn't handle well the data of this particular run. I think this is related to #88 and indicates that the default protocol to subsample timeseries is not robust.

**Comment by jmichel80** [comment]
Ok, maybe I misunderstood the meaning of the percentage keyword. It seems that --percentage indicates the percentage of the trajectory to RETAIN rather than the percentage to DISCARD ? 

There seem to be issues with using this keyword with some values of --percentage. See below.

julien@node009:~/projects/somd/SAMPL/runs/minnesota-GAFFCM5-cyc/cyclohexane/cyc/run002/vanish/output$ ~/sire.app/bin/analyse_freenrg_mbar -i lambda-0.000/simfile.dat lambda-0.100/simfile.dat lambda-0.200/simfile.dat lambda-0.300/simfile.dat lambda-0.400/simfile.dat lambda-0.500/simfile.dat lambda-0.600/simfile.dat lambda-0.700/simfile.dat lambda-0.800/simfile.dat lambda-0.900/simfile.dat lambda-0.950/simfile.dat lambda-1.000/simfile.dat --lam 0.000 0.100 0.200 0.300 0.400 0.500 0.600 0.700 0.800 0.900 0.950 1.000 --temperature 298.0 -o mbar.pmf --subsampling percentage --percentage 99
"/users/julien/sire.app/share/Sire/scripts/analyse_freenrg_mbar.py" 
Starting /home/julien/sire.app/bin/analyse_freenrg_mbar: number of threads equals 16

# Writing all output to file mbar.pmf
We are only eliminating samples from the beginning of the data and are still working with highly correlated data!
We are only eliminating samples from the beginning of the data and are still working with highly correlated data!
/home/julien/sire.app/lib/python3.5/site-packages/pymbar/utils.py:70: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if N_k == None:
K (total states) = 12, total samples = 118800
N_k = 
[ 9900.  9900.  9900.  9900.  9900.  9900.  9900.  9900.  9900.  9900.
  9900.  9900.]
There are 12 states with samples.
Initializing free energies to zero.
Initial dimensionless free energies with method zeros
f_k = 
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
/home/julien/sire.app/lib/python3.5/site-packages/scipy/optimize/minpack.py:236: RuntimeWarning: xtol=0.000000 is too small, no further improvement in the approximate
  solution is possible.
  warnings.warn(msg, RuntimeWarning)
Final dimensionless free energies
f_k = 
[ 0.         -3.55788766 -1.43284095 -0.59490505 -1.18705162 -2.19634405
 -2.88855729 -2.80238659 -2.13077743 -0.91296079 -0.33818796  0.41026344]
MBAR initialization complete.
Free energy difference estimated with MBAR is: 0.242953 kcal/mol +/- 0.042156 kcal/mol
Free energy difference estimated with MBAR is: 0.601967 kJ/mol +/- 0.176380 kJ/mol
Free energy difference estimated with TI is: -0.346510 kcal/mol
julien@node009:~/projects/somd/SAMPL/runs/minnesota-GAFFCM5-cyc/cyclohexane/cyc/run002/vanish/output$ ~/sire.app/bin/analyse_freenrg_mbar -i lambda-0.000/simfile.dat lambda-0.100/simfile.dat lambda-0.200/simfile.dat lambda-0.300/simfile.dat lambda-0.400/simfile.dat lambda-0.500/simfile.dat lambda-0.600/simfile.dat lambda-0.700/simfile.dat lambda-0.800/simfile.dat lambda-0.900/simfile.dat lambda-0.950/simfile.dat lambda-1.000/simfile.dat --lam 0.000 0.100 0.200 0.300 0.400 0.500 0.600 0.700 0.800 0.900 0.950 1.000 --temperature 298.0 -o mbar.pmf --subsampling percentage --percentage 90
"/users/julien/sire.app/share/Sire/scripts/analyse_freenrg_mbar.py" 
Starting /home/julien/sire.app/bin/analyse_freenrg_mbar: number of threads equals 16

# Writing all output to file mbar.pmf
We are only eliminating samples from the beginning of the data and are still working with highly correlated data!
Traceback (most recent call last):
  File "/users/julien/sire.app/share/Sire/scripts/analyse_freenrg_mbar.py", line 173, in <module>
    subsample_obj.subsample_energies()
  File "/home/julien/sire.app/lib/python3.5/site-packages/Sire/Tools/FreeEnergyAnalysis.py", line 198, in subsample_energies
    self._subsampled_u_kln[i,j,:] = self._u_kln[i,j,percentage_removal[j]:]
ValueError: could not broadcast input array from shape (9001) into shape (9000)
julien@node009:~/projects/somd/SAMPL/runs/minnesota-GAFFCM5-cyc/cyclohexane/cyc/run002/vanish/output$ ~/sire.app/bin/analyse_freenrg_mbar -i lambda-0.000/simfile.dat lambda-0.100/simfile.dat lambda-0.200/simfile.dat lambda-0.300/simfile.dat lambda-0.400/simfile.dat lambda-0.500/simfile.dat lambda-0.600/simfile.dat lambda-0.700/simfile.dat lambda-0.800/simfile.dat lambda-0.900/simfile.dat lambda-0.950/simfile.dat lambda-1.000/simfile.dat --lam 0.000 0.100 0.200 0.300 0.400 0.500 0.600 0.700 0.800 0.900 0.950 1.000 --temperature 298.0 -o mbar.pmf --subsampling percentage --percentage 80
"/users/julien/sire.app/share/Sire/scripts/analyse_freenrg_mbar.py" 
Starting /home/julien/sire.app/bin/analyse_freenrg_mbar: number of threads equals 16

# Writing all output to file mbar.pmf
We are only eliminating samples from the beginning of the data and are still working with highly correlated data!
Traceback (most recent call last):
  File "/users/julien/sire.app/share/Sire/scripts/analyse_freenrg_mbar.py", line 173, in <module>
    subsample_obj.subsample_energies()
  File "/home/julien/sire.app/lib/python3.5/site-packages/Sire/Tools/FreeEnergyAnalysis.py", line 198, in subsample_energies
    self._subsampled_u_kln[i,j,:] = self._u_kln[i,j,percentage_removal[j]:]
ValueError: could not broadcast input array from shape (8001) into shape (8000)
julien@node009:~/projects/somd/SAMPL/runs/minnesota-GAFFCM5-cyc/cyclohexane/cyc/run002/vanish/output$ ~/sire.app/bin/analyse_freenrg_mbar -i lambda-0.000/simfile.dat lambda-0.100/simfile.dat lambda-0.200/simfile.dat lambda-0.300/simfile.dat lambda-0.400/simfile.dat lambda-0.500/simfile.dat lambda-0.600/simfile.dat lambda-0.700/simfile.dat lambda-0.800/simfile.dat lambda-0.900/simfile.dat lambda-0.950/simfile.dat lambda-1.000/simfile.dat --lam 0.000 0.100 0.200 0.300 0.400 0.500 0.600 0.700 0.800 0.900 0.950 1.000 --temperature 298.0 -o mbar.pmf --subsampling percentage --percentage 70
"/users/julien/sire.app/share/Sire/scripts/analyse_freenrg_mbar.py" 
Starting /home/julien/sire.app/bin/analyse_freenrg_mbar: number of threads equals 16

# Writing all output to file mbar.pmf
We are only eliminating samples from the beginning of the data and are still working with highly correlated data!
We are only eliminating samples from the beginning of the data and are still working with highly correlated data!
/home/julien/sire.app/lib/python3.5/site-packages/pymbar/utils.py:70: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if N_k == None:
K (total states) = 12, total samples = 84000
N_k = 
[ 7000.  7000.  7000.  7000.  7000.  7000.  7000.  7000.  7000.  7000.
  7000.  7000.]
There are 12 states with samples.
Initializing free energies to zero.
Initial dimensionless free energies with method zeros
f_k = 
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
/home/julien/sire.app/lib/python3.5/site-packages/scipy/optimize/minpack.py:236: RuntimeWarning: xtol=0.000000 is too small, no further improvement in the approximate
  solution is possible.
  warnings.warn(msg, RuntimeWarning)
Final dimensionless free energies
f_k = 
[ 0.         -3.41256374 -1.26114473 -0.82002013 -1.87786147 -2.93929231
 -3.66109326 -3.56657564 -2.88932409 -1.6707961  -1.09537775 -0.34591163]
MBAR initialization complete.
Free energy difference estimated with MBAR is: -0.204845 kcal/mol +/- 0.052349 kcal/mol
Free energy difference estimated with MBAR is: -0.507545 kJ/mol +/- 0.219028 kJ/mol
Free energy difference estimated with TI is: -0.890694 kcal/mol

**Comment by jmichel80** [comment]
So to summarise, the problem with the subsampling timeseries method is that it throws away almost all data in some instances. This seems to occur with calculations that do not start from a well equilibrated trajectory, or for calculations that have less overlap between windows.

**Comment by chryswoods** [comment]
Yes, that sounds reasonable. Also, you are right that --percent specifies the percent of the trajectory to retain, rather than throw away. The documentation string for --percent is

"Supply the percentage of iterations over which to average. By default the average will be over the last 60 percent of iterations."

If this isn't clear, we should update the documentation to make it clearer.

**Comment by ppxasjsm** [comment]
I think the confusion is a mix of scripts. I have almost fixed all of these issues now and I will make sure the documentation is comprehensive. 
I would still like to use subsampling in general rather than using only say the last 60 percent of the data. For the error estimate coming from MBAR it is better to have uncorrelated data samples, which would make the subsampling a good option. 

Reporting errors in general:
I think this was briefly discussed, but I have failed to take notes on this. What should be the consistent way of reporting error for all estimation methods? At the moment different estimators report errors in a different way.

**Comment by jmichel80** [comment]
I like subsampling as it removes the need to decide what is a good
percentage of data to keep. However at the moment the subsampling option
can fail catastrophically on some datasets. It should be doable to make the
method less sensitive to noisy datasets, or to introduce some sanity checks
to make sure it does not excessively throw away data.

Perhaps discarding the first 5% and then subsampling the rest would help
deal with poorly equilibrated lambda trajectories. Also keeping at least
100 snapshots.

Regarding errors, the strategy is to use bootstrapping for everything and
to report +/- 1 standard deviation.







On Sat, Dec 19, 2015 at 11:17 AM, ppxasjsm <notifications@github.com> wrote:

> I think the confusion is a mix of scripts. I have almost fixed all of
> these issues now and I will make sure the documentation is comprehensive.
> I would still like to use subsampling in general rather than using only
> say the last 60 percent of the data. For the error estimate coming from
> MBAR it is better to have uncorrelated data samples, which would make the
> subsampling a good option.
>
> Reporting errors in general:
> I think this was briefly discussed, but I have failed to take notes on
> this. What should be the consistent way of reporting error for all
> estimation methods? At the moment different estimators report errors in a
> different way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/90#issuecomment-165977209>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by chryswoods** [comment]
Closing as no progress
