### ISSUE TITLE
conda install ipython notebook breaks sire install

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#91]
I am not sure how important or desirable this is, but I just managed to break my sire install by running ~/sire.bin/app/conda install ipython notebook. This resulted in an upgrade to python 3.5. 
After recompiling the wrapper...which for no apparent reason was necessary, I get the following error:

```
~/feat_sire.app/bin/somd
dyld: Library not loaded: libpython3.5m.dylib
  Referenced from: /Users/toni_brain/feat_sire.app/bin/somd
  Reason: image not found
Trace/BPT trap: 5
```

I haven't googled this yet.

**Comment by chryswoods** [comment]
Interesting. This will be one of our conda problems, I think, in that conda will occasionally upgrade things beyond what we can support with Sire. I'll play with this and will try to debug the process...

**Comment by chryswoods** [comment]
Closing as newer builds compile against Python 3.5. A better solution will be discovered when we get "conda install sire" working
