### ISSUE TITLE
catching incompatible simulation settings

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#93]
I just ran into this problem
I was trying to use somd to energy minimise a molecule in vacuum and got this error message.
## Running minimisation.

UserWarning                               Traceback (most recent call last)
/mnt/hgfs/sims/stefano/reproducibility/neopentane-methane/3step/run001/step2/vacuum/debug/sp.py in <module>()
   1503             print ('Tolerance for minimisation: ' + str(minimise_tol.val))
   1504             print ('Maximum number of minimisation iterations: ' + str(minimise_max_iter.val))
-> 1505         system = integrator.minimiseEnergy(system, minimise_tol.val, minimise_max_iter.val)
   1506         system.mustNowRecalculateFromScratch()
   1507         if verbose.val:
UserWarning: Exception 'SireError::invalid_cast' thrown by the thread 'master'.
Cannot cast from an object of class "SireVol::Cartesian" to an object of class "SireVol::PeriodicBox".
Thrown from FILE: /home/julien/software/devel/sire/corelib/src/libs/SireBase/property.cpp, LINE: 120, FUNCTION: void SireBase::Property::throwInvalidCast(const char*) const

The error was that I had kep the default value for
cutoff_type = Parameter("cutoff type", "cutoffperiodic", """The cutoff method to use during the simulation.""")

Changing cutoff_type to cutoffnonperiodic does the trick.

It may be hard to systematically catch all errors, but It might be good to give more informative error messages. Most people don't know how to deal with the Traceback. 

One option is to catch exceptions and channel them into a class that may also inspect the Parameters dictionary to identify known incompatibilities.  We may even be able to do that prior to launching a simulation to avoid wasting time.

**Comment by ppxasjsm** [comment]
Yes I agree. There should be a whole parameter set check done anyway. It is definitely on the enhancement list.

**Comment by chryswoods** [comment]
I'll add this to the roadmap as part of the upgrade to the Parameter class.
