### ISSUE TITLE
Single point SOMD energies?

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#94]
It would be useful to extend the Sire/OpenMM interface classes to compute and return a single point potential energy using the Hamiltonian defined at initialisation. 

For instance, one could add to the public interface of the relevant classes:

SireUnits::Dimension::MolarEnergy OpenMMFrEnergyST::singlePointEnergy(System &system);

Such that we can do from python

somd_energy = integrator.singlePointEnergy(system)
assert ( system.energy() almost equal to somd_energy)

This would facilitate comparison with Sire's single point energies. 

At the moment my workaround is to do 1 step of MD with a timestep of 0 fs (or almost 0), add debug statements in the integrate(...) in the relevant.cpp source, recompile corelib, run tests. If ok, remove debug statements and recompile corelib.

**Comment by jmichel80** [comment]
Will fork from devel, get that done and let you consider whether merging is ok

**Comment by jmichel80** [comment]
Amazingly i failed to spot ::getPotentialEnergy(system) this morning.

**Comment by chryswoods** [comment]
Thanks Julien - we are making good progress and are on target with the plan we sent out. We hope to finalise the release this evening.

**Comment by chryswoods** [comment]
Just some last minute regressions to fix... (ligandswap crashing in 2016.1 versus 2014.4...)
