### ISSUE TITLE
somd-freeenergy crashes on a system that involves significant changes in internal geometry

### ISSUE THREAD

**Issue by jmroldan1975** [michellab/Sire#96]
Hi, 

I have been trying to do a relative free energy calculation between a dithiolane and a dioxolane ring. 

If using the following keywords in the cfg file:

timestep = 4 * femtosecond
constraint = allbonds
hydrogen mass repartitioning factor = 4.0

The job crashes with the following error message if lambda != 0

...complete 
Starting /home/julien/sire.app/bin/somd-freenrg: number of threads equals 32
somd-freenrg: /anaconda/conda-bld/work/openmm-6.3/libraries/quern/src/quern_factorization.cpp:88: bool apply_givens(SparseVector&, SparseVector&, int, double&, double&): Assertion `!y.empty() && y.front().index==diagonal && y.front().value' failed.
srun: error: node010: task 0: Aborted (core dumped)

This seems to be related to a failure of the constraints code in OpenMM. 
Indeed chancing the sim.cfg settings to 

timestep = 2.0 * femtosecond
constraint = hbonds
hydrogen mass repartitioning factor = 1.0

Enables completion of simulations at all lambda values. 

Most likely, the code fails to minimize and satisfy constraints when the Hamiltonian is changed, but the input geometry is far from the target constraint values (C-S and C-O bond lengths change a lot and inside a ring there are additional geometric constraints to satisfy). 

A possible fix during equilibration would be to minimize without constraint, and then apply constraints. This would require code changes in OpenMMMD.py. An alternative work-around is to manually minimize all crd files for each specific lambda value.

Best wishes, 

Jose

**Comment by ppxasjsm** [comment]
Yes this is a known issues and I am working on a fix there, the free energy feature branch will hopefully resolve this problem. Thanks for raising this. 
What are you referring to regarding the constraints code in OpenMM? Do you have a link to that?

**Comment by jmichel80** [comment]
On Tuesday, May 24, 2016, ppxasjsm <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Yes this is a known issues and I am working on a fix there, the free
> energy feature branch will hopefully resolve this problem. Thanks for
> raising this.
> What are you referring to regarding the constraints code in OpenMM? Do you
> have a link to that?
>

This isn't 100% confirmed, but searching the OpenMM source code shows that
the assertion error is triggered by a third party library (quern) as part
of QR factorisation calculation. This library is only included in OpenMM
code

platforms/cuda/src/CudaIntegrationUtilities.cpp
platforms/cuda/src/OpenCLIntegrationUtilities.cpp

and the calls to QUERN seem to be related to matrices manipulation
operations for solving e.o.m under constraints.


Best wishes,

Julien



> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/issues/96#issuecomment-221302840>
>


-- 
--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by jmichel80** [comment]
The above error happens randomly on some D3R LitD1 systems (always in the bound state), despite using a customise OpenMMMD.py that performs minimisation without constraints. 
It seems that the culprit is assertion failure in the constraint code used during the MD part. 

Could be related to:
https://github.com/pandegroup/openmm/issues/1352 

Are we able pulling the openmm packages in 'release mode' ?

**Comment by jmroldan1975** [comment]
Let´s hope that it can be solved and it is the same error I was facing. Thanks for letting me know.

  Best

**Comment by jmichel80** [comment]
I ran additional tests on 2016.1 and frequent crashes also occur with constraint "allbonds" , 2 fs timestep & noHMR. 

It seems that we should only use constraint "hbonds" with recent code releases.
